### ISSUE TITLE
Exiting osu!lazer crashes entire hyprland session

### ISSUE THREAD

**Issue by Estebiu** [hyprwm/Hyprland#1418]
Exactly as the title says, exiting osu!lazer (running on wayland; no xwayland) crashes the entire session. 

I'm using latest hyprland-git, just compiled, and latest osu-lazer-bin from the AUR.

Hyprland log+coredump: https://files.estebiu.com/filebrowser/share/8zxKLi6Q

I'm not attaching my hyprland config as it still crashes with the default one.

**Comment by vaxerski** [comment]
coredump seems completely broken, try the debug build

**Comment by JustSimplyKyle** [comment]
debug coredump: https://0x0.st/oFMv.txt
```
(gdb) bt -full
#0  0x00007f5332a84aba in  () at /usr/lib/libwayland-server.so.0
#1  0x00007f5332a8901c in  () at /usr/lib/libwayland-server.so.0
#2  0x00007f5332a879e2 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#3  0x00007f5332a88197 in wl_display_run () at /usr/lib/libwayland-server.so.0
#4  0x000055ef7845cd39 in main(int, char**) (argc=1, argv=0x7ffcd51dec38)
    at /usr/include/c++/12.2.1/bits/unique_ptr.h:191
        cmd = "/usr/local/bin/Hyprland"
        configPath = ""
        ignoreSudo = <optimized out>
        LOGWLR = <optimized out>
```
The asan log didn't produce anything

**Comment by JustSimplyKyle** [comment]
![image](https://user-images.githubusercontent.com/68589851/214995944-f77a153f-59f1-4a94-b01d-c3505fda558d.png)
This is the faulty commit

**Comment by vaxerski** [comment]
uh... huh.

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/10518325/patch.txt)

try this patch

**Comment by vaxerski** [comment]
committed anyways cuz it was a bug, see with 666c8051016609d77c5651fb42113474832434d2

**Comment by JustSimplyKyle** [comment]
Fixed for me
