### ISSUE TITLE
Can't launch applications using lutris

### ISSUE THREAD

**Issue by ThePhantomGM** [hyprwm/Hyprland#2582]
When trying to launch an application using lutris, the launcher sends the error pop-up "not enough values to unpack (expected 3, got 1)". This seems to happen as the launcher uses xrandr to get the current resolution of the display and the latest change makes it so that hyprland no longer sends scaling information to xwayland.

### Detailed error message from console log: 

ValueError: not enough values to unpack (expected 3, got 1)
2023-06-24 21:14:41,544: The Void Rains Upon Her Heart (linux) has encountered an error: not enough values to unpack (expected 3, got 1)
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/exceptions.py", line 89, in wrapper
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/game.py", line 628, in configure_game
    self.original_outputs = DISPLAY_MANAGER.get_config()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/util/graphics/xrandr.py", line 192, in get_config
    return get_outputs()
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/util/graphics/xrandr.py", line 59, in get_outputs
    _, x_pos, y_pos = geometry.split("+")
    ^^^^^^^^^^^^^^^

### Steps to reproduce: 
1. Use the latest hyprland-git AUR package
2. Use the latest release or git release of lutris
3. Try to launch any application within lutris

### Expected outcome:
The app should launch as normal

### Noted outcome: 
The apps don't launch and the error pop-up appears

**Comment by ThePhantomGM** [comment]
Sorry, duplicate of #2580
