### ISSUE TITLE
Freeze on window close

### ISSUE THREAD

**Issue by TheSunCat** [hyprwm/Hyprland#2882]
### Hyprland Version

Hyprland, built from branch main at commit 5c50fac907df3463492a019f01f84d547ab93650 dirty (windowrules: add workspace param). Tag: v0.27.2-65-g5c50fac9

### Bug or Regression?

Bug

### Description

Hyprland freezes sometimes when closing a window. This is recoverable by SSHing in and doing `killall Hyprland -9`. Switching VTs does not work.

### How to reproduce

- Label: `loop`
  - Open `foot`
  - Close `foot`
- Goto `loop`
- Eventually, Hyprland will freeze one or two frames into the animation of closing the window

### Crash reports, logs, images, videos

GDB backtrace (OCR'd from screenshot):
```ini
[New LWP 2321]
[New LWP 2322]
[New LWP 2323]
[New LWP 2324]
[New LWP 2478]
[New LWP 2479]
[New LWP 2726]
[New LWP 2845]
[New LWP 2846]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
0x000077d9f09a0fb in __lll_lock_wait_private ()
from /usr/lib/libc.so.6
(gdb) bt
#0 0x00007f7d9f09a0fb in __lll_lock_wait_private ()
at /usr/lib/libc.so.6
#1  0x00007f7d9f0ad960 in malloc () at /usr/lib/libc.so.6
#2  0x00007f7d9f087c11 in _IO_file_doallocate ()
at /usr/lib/libc.so.6
#3  0x00007f7d9f096d20 in _IO_doallocbuf ()
at /usr/lib/libc.so.6
#4  0x00007f7d9f095a9d in _IO_file_underflow ()
at /usr/lib/libc.so.6
#5 0x00007f7d9f096dd6 in _IO_default_uflow ()
at /usr/lib/libc.so.6
#6 0x00007f7d9f0897db in _IO_getline_info ()
at /usr/lib/libc.so.6
#7 0x00007f7d9f088570 in fgets () at /usr/lib/libc.so.6
#8 0x00005584214b1e38 in execAndGet[abi:cxx11](char const*) ()
#9 0x0000558421481e78 in CrashReporter::createAndSaveCrash(int) ()
#10 0x000055842141affc in handleUnrecoverableSignal(int) ()
#11 0x00007f7d9f04fab0 in <signal handler called> ()
at /usr/lib/libc.so.6
#12 0x00007f7d9f09f26c in () at /usr/lib/libc.so.6
#13 0x00007f7d9f04fa08 in raise () at /usr/lib/libc.so.6
#14 0x00007f7d9f038538 in abort () at /usr/lib/libc.so.6
#15 0x00007f7d9f0392db in () at /usr/lib/libc.so.6
#17 0x00007f7d9f0ab3d8 in () at /usr/lib/libc.so.6
#18 0x00007f7d9f0adcb3 in free () at /usr/lib/libc.so.6
#19 0x00007f7d9fc7e9d9 in () at /usr/lib/libwayland-server.so.0
#20 0x00007f7d9fc807a9 in wl_resource_destroy ()
at /usr/lib/libwayland-server.so.
#21 0x000055842152fa30 in CWaylandResource::~CWaylandResource() ()
#22 0x0000558421530025 in destroyManagerResource(wl_client*, wl_resource*) ()
#23 0x00007f7d9ebdd4f6 in () at /usr/lib/libffi.so.8
#24 0x00007f7d9ebd9f5e in () at /usr/lib/libffi.so.8
#25 0x00007f7d9ebdcb73 in ffi_call () at /usr/lib/libffi.so.8
#26 0x00007f7d9fc7bada in () at /usr/lib/libwayland-server.so.0
#27 0x00007f7d9fc80180 in () at /usr/lib/libwayland-server.so.0
#28 0x00007f7d9fc7eae2 in wl_event_loop_dispatch ()
at /usr/lib/libwayland-server.so.0
#29 0x00007f7d9fc7f2d7 in wl_display_run ()
at /usr/lib/libwayland-server.so.0
#30 0x000055842140b061 in main ()
```

![](https://cdn.discordapp.com/attachments/961694014615208048/1136201140816580698/Screenshot_20230802-093612_Termux.png)

**Comment by vaxerski** [comment]
this is a crash, but an odd one.

[patch.txt](https://github.com/hyprwm/Hyprland/files/12254767/patch.txt)
?

**Comment by TheSunCat** [comment]
I can't seem to repro with the patch applied, nice!

**Comment by vaxerski** [comment]
wtf

**Comment by vaxerski** [comment]
ef0d97153ac121a75be1478808123ab8e7cdf4de
