### ISSUE TITLE
Waybar transparency not working with either 0.32.1 or 0.32.2, soft locks when trying to launch wofi (please disregard version info in this issue, as I had to revert to a stable build)

### ISSUE THREAD

**Issue by ronasimi** [hyprwm/Hyprland#3832]
### Hyprland Version

Hyprland, built from branch HEAD at commit 5b8cfdf2efc44106b61e60c642fd964823fd89f3  (props: bump ver to v0.31.0). Tag: v0.31.0  flags: (if any)

### Bug or Regression?

Bug

### Description

Waybar initially loads with transparency, then immediately loses transparency.  pkill waybar soft locks desktop, unable to switch to a different TTY. Launching wofi also causes soft lock. Reverted back to 0.31, no issue  Building using a modified PKGBUILD on arch, which I've included.
![2023-11-11T13:01:26,914231486-05:00](https://github.com/hyprwm/Hyprland/assets/3991859/a36872a0-f2a1-41c2-a20f-64c5d49bc68e)
[config.txt](https://github.com/hyprwm/Hyprland/files/13326166/config.txt)
[hyprland.conf.txt](https://github.com/hyprwm/Hyprland/files/13326167/hyprland.conf.txt)
[PKGBUILD.txt](https://github.com/hyprwm/Hyprland/files/13326168/PKGBUILD.txt)
[style.css.txt](https://github.com/hyprwm/Hyprland/files/13326169/style.css.txt)
[waybar.sh.txt](https://github.com/hyprwm/Hyprland/files/13326170/waybar.sh.txt)

### How to reproduce

Install 0.32.1 or 0.32.2

**Comment by vaxerski** [comment]
ssh to a softlocked machine, run `sudo gdb attach $(pidof Hyprland)` and provide the output of `bt -full`.

Waybar transparency - is that to do with 10 bit again? Maybe #3126 ?

**Comment by ronasimi** [comment]
```
❯ sudo gdb attach $(pidof Hyprland)
GNU gdb (GDB) 13.2
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
attach: No such file or directory.
Attaching to process 1512
[New LWP 1535]
[New LWP 1538]
[New LWP 1539]
[New LWP 1540]
[New LWP 1541]
[New LWP 1542]
[New LWP 1543]
--Type <RET> for more, q to quit, c to continue without paging--
[New LWP 1544]
[New LWP 1545]
[New LWP 1546]
[New LWP 1547]
[New LWP 1548]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
0x00007fcfe1ca769b in __lll_lock_wait_private () from /usr/lib/libc.so.6
```

`(gdb) bt -full
#0  0x00007fcfe1ca769b in __lll_lock_wait_private () at /usr/lib/libc.so.6
#1  0x00007fcfe1cbaee0 in malloc () at /usr/lib/libc.so.6
#2  0x00007fcfe1c9549a in _IO_file_doallocate () at /usr/lib/libc.so.6
#3  0x00007fcfe1ca4279 in _IO_doallocbuf () at /usr/lib/libc.so.6
#4  0x00007fcfe1ca2055 in _IO_file_underflow () at /usr/lib/libc.so.6
#5  0x00007fcfe1ca431f in _IO_default_uflow () at /usr/lib/libc.so.6
#6  0x00007fcfe1c9703b in _IO_getline_info () at /usr/lib/libc.so.6
#7  0x00007fcfe1c95de0 in fgets () at /usr/lib/libc.so.6
#8  0x0000559dea421dba in execAndGet[abi:cxx11](char const*) ()
#9  0x0000559dea3d1a25 in CrashReporter::createAndSaveCrash(int) ()
#10 0x0000559dea33ce94 in handleUnrecoverableSignal(int) ()
#11 0x00007fcfe1c5c710 in <signal handler called> () at /usr/lib/libc.so.6
#12 0x00007fcfe1cac83c in  () at /usr/lib/libc.so.6
#13 0x00007fcfe1c5c668 in raise () at /usr/lib/libc.so.6
#14 0x00007fcfe1c444b8 in abort () at /usr/lib/libc.so.6
#15 0x00007fcfe1c45390 in  () at /usr/lib/libc.so.6
#16 0x00007fcfe1cb67b7 in  () at /usr/lib/libc.so.6
#17 0x00007fcfe1cb883c in  () at /usr/lib/libc.so.6
#18 0x00007fcfe1cb8b29 in  () at /usr/lib/libc.so.6
#19 0x00007fcfe1cbb353 in free () at /usr/lib/libc.so.6
#20 0x00007fcfe26bae4f in  () at /usr/lib/libwlroots.so.12032
#21 0x00007fcfe25fe9ba in  () at /usr/lib/libwayland-server.so.0
#22 0x00007fcfe25ff0db in wl_client_destroy ()
--Type <RET> for more, q to quit, c to continue without paging--
    at /usr/lib/libwayland-server.so.0
#23 0x00007fcfe25ff60e in  () at /usr/lib/libwayland-server.so.0
#24 0x00007fcfe25feae2 in wl_event_loop_dispatch ()
    at /usr/lib/libwayland-server.so.0
#25 0x00007fcfe25ff2d7 in wl_display_run () at /usr/lib/libwayland-server.so.0
#26 0x0000559dea354cc8 in CCompositor::startCompositor() ()
#27 0x0000559dea3278e7 in main ()
`

**Comment by ronasimi** [comment]
```
(gdb) bt -full
#0  0x00007fcfe1ca769b in __lll_lock_wait_private () at /usr/lib/libc.so.6
#1  0x00007fcfe1cbaee0 in malloc () at /usr/lib/libc.so.6
#2  0x00007fcfe1c9549a in _IO_file_doallocate () at /usr/lib/libc.so.6
#3  0x00007fcfe1ca4279 in _IO_doallocbuf () at /usr/lib/libc.so.6
#4  0x00007fcfe1ca2055 in _IO_file_underflow () at /usr/lib/libc.so.6
#5  0x00007fcfe1ca431f in _IO_default_uflow () at /usr/lib/libc.so.6
#6  0x00007fcfe1c9703b in _IO_getline_info () at /usr/lib/libc.so.6
#7  0x00007fcfe1c95de0 in fgets () at /usr/lib/libc.so.6
#8  0x0000559dea421dba in execAndGet[abi:cxx11](char const*) ()
#9  0x0000559dea3d1a25 in CrashReporter::createAndSaveCrash(int) ()
#10 0x0000559dea33ce94 in handleUnrecoverableSignal(int) ()
#11 0x00007fcfe1c5c710 in <signal handler called> () at /usr/lib/libc.so.6
#12 0x00007fcfe1cac83c in  () at /usr/lib/libc.so.6
#13 0x00007fcfe1c5c668 in raise () at /usr/lib/libc.so.6
#14 0x00007fcfe1c444b8 in abort () at /usr/lib/libc.so.6
#15 0x00007fcfe1c45390 in  () at /usr/lib/libc.so.6
#16 0x00007fcfe1cb67b7 in  () at /usr/lib/libc.so.6
#17 0x00007fcfe1cb883c in  () at /usr/lib/libc.so.6
#18 0x00007fcfe1cb8b29 in  () at /usr/lib/libc.so.6
#19 0x00007fcfe1cbb353 in free () at /usr/lib/libc.so.6
#20 0x00007fcfe26bae4f in  () at /usr/lib/libwlroots.so.12032
#21 0x00007fcfe25fe9ba in  () at /usr/lib/libwayland-server.so.0
#22 0x00007fcfe25ff0db in wl_client_destroy ()
--Type <RET> for more, q to quit, c to continue without paging--
    at /usr/lib/libwayland-server.so.0
#23 0x00007fcfe25ff60e in  () at /usr/lib/libwayland-server.so.0
#24 0x00007fcfe25feae2 in wl_event_loop_dispatch ()
    at /usr/lib/libwayland-server.so.0
#25 0x00007fcfe25ff2d7 in wl_display_run () at /usr/lib/libwayland-server.so.0
#26 0x0000559dea354cc8 in CCompositor::startCompositor() ()
#27 0x0000559dea3278e7 in main ()
```

**Comment by ronasimi** [comment]
not using 10 bit anymore for testing

**Comment by ronasimi** [comment]
Still have the same issue on 0.32.3, see below for gdb output

```
(gdb) bt -full
#0  0x00007f003a7ba69b in __lll_lock_wait_private () at /usr/lib/libc.so.6
#1  0x00007f003a7cdee0 in malloc () at /usr/lib/libc.so.6
#2  0x00007f003a7a849a in _IO_file_doallocate () at /usr/lib/libc.so.6
#3  0x00007f003a7b7279 in _IO_doallocbuf () at /usr/lib/libc.so.6
#4  0x00007f003a7b5055 in _IO_file_underflow () at /usr/lib/libc.so.6
#5  0x00007f003a7b731f in _IO_default_uflow () at /usr/lib/libc.so.6
#6  0x00007f003a7aa03b in _IO_getline_info () at /usr/lib/libc.so.6
#7  0x00007f003a7a8de0 in fgets () at /usr/lib/libc.so.6
#8  0x00005626e705603a in execAndGet[abi:cxx11](char const*) ()
#9  0x00005626e7005ca5 in CrashReporter::createAndSaveCrash(int) ()
#10 0x00005626e6f71114 in handleUnrecoverableSignal(int) ()
#11 0x00007f003a76f710 in <signal handler called> () at /usr/lib/libc.so.6
#12 0x00007f003a7bf83c in  () at /usr/lib/libc.so.6
#13 0x00007f003a76f668 in raise () at /usr/lib/libc.so.6
#14 0x00007f003a7574b8 in abort () at /usr/lib/libc.so.6
#15 0x00007f003a758390 in  () at /usr/lib/libc.so.6
#16 0x00007f003a7c97b7 in  () at /usr/lib/libc.so.6
#17 0x00007f003a7cb83c in  () at /usr/lib/libc.so.6
#18 0x00007f003a7cbb29 in  () at /usr/lib/libc.so.6
#19 0x00007f003a7ce353 in free () at /usr/lib/libc.so.6
#20 0x00007f003b17de4f in  () at /usr/lib/libwlroots.so.12032
#21 0x00007f003b0c19ba in  () at /usr/lib/libwayland-server.so.0
#22 0x00007f003b0c20db in wl_client_destroy ()
--Type <RET> for more, q to quit, c to continue without paging--c
    at /usr/lib/libwayland-server.so.0
#23 0x00007f003b0c260e in  () at /usr/lib/libwayland-server.so.0
#24 0x00007f003b0c1ae2 in wl_event_loop_dispatch ()
    at /usr/lib/libwayland-server.so.0
#25 0x00007f003b0c22d7 in wl_display_run () at /usr/lib/libwayland-server.so.0
#26 0x00005626e6f88f48 in CCompositor::startCompositor() ()
#27 0x00005626e6f5bb67 in main ()
```

**Comment by vaxerski** [comment]
yeah my bad this one is different

**Comment by vaxerski** [comment]
I couldn't repro this. :(

Could you do this: https://wiki.hyprland.org/Crashes-and-Bugs/#building-the-wayland-stack-with-asan

I know it's annoying, but this looks like a memory issue stemming from... somewhere. I tried myself, and couldn't get a crash.

Such an asan trace would help immensely.

**Comment by ronasimi** [comment]
Yeah, I might be able to do that but it'll be later tonight EST. This is my daily driver machine.

**Comment by vaxerski** [comment]
no hurries. Thanks.

**Comment by ronasimi** [comment]
It's something with my PKGBUILD, I installed -git and it's working fine, as long as I don't use 10 bit color.

I'll troubleshoot my PKGBUILD, thanks tho

**Comment by ronasimi** [comment]
for posterity, and any other arch users who want the latest release, here is a working PKGBUILD for 0.32.3 - just don't use 10 bit color lol

```
# Maintainer: Caleb Maclennan <caleb@alerque.com>
# Contributor: ThatOneCalculator <kainoa@t1c.dev>

pkgname=hyprland
pkgver=0.32.3
pkgrel=1
pkgdesc='a highly customizable dynamic tiling Wayland compositor'
arch=(x86_64 aarch64)
url="https://github.com/hyprwm/${pkgname^}"
license=(BSD)
depends=(cairo
         gcc-libs
         glibc
         glslang
         libdisplay-info
         libdrm
         libglvnd
         libinput
         libliftoff
         libx11
         libxcb
         libxcomposite
         libxfixes
         libxkbcommon
         libxrender
         opengl-driver
         pango
         pixman
         pixman
         polkit
         seatd
         systemd-libs
         vulkan-icd-loader
         vulkan-validation-layers
         wayland
         wayland-protocols
         xcb-proto
         xcb-util
         xcb-util-errors
         xcb-util-keysyms
         xcb-util-renderutil
         xcb-util-wm
         xorg-xinput
         xorg-xwayland)
depends+=(libdisplay-info.so)
makedepends=(cmake
             gdb
             meson
             ninja
             vulkan-headers
             xorgproto)
_archive="${pkgname^}-$pkgver"
source=("$_archive.tar.gz::$url/releases/download/v$pkgver/source-v$pkgver.tar.gz")
sha256sums=('285e8ebbd003978a2124e984db7677d044c21ca3cb72948eb71742cd8396df35')

prepare() {
	ln -sf hyprland-source "$_archive"
	cd "$_archive"
#	make fixwlr
	sed -i -e '/^release:/{n;s/-D/-DCMAKE_SKIP_RPATH=ON -D/}' Makefile
}

build() {
	cd "$_archive"
	pushd subprojects/wlroots
	meson build/ --prefix="$srcdir/tmpwlr" --buildtype=release
	ninja -C build/
	mkdir -p "$srcdir/tmpwlr"
	ninja -C build/ install
	popd
	pushd subprojects/udis86
	cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -H./ -B./build -G Ninja
	cmake --build ./build --config Release --target all
	popd
	make protocols
	make release
	pushd hyprctl
	make all
}

package() {
	cd "$_archive"
	find src -name '*.hpp' -exec install -Dm0644 {} "$pkgdir/usr/include/hyprland/{}" \;
	pushd subprojects/wlroots/include
	find . -name '*.h' -exec install -Dm0644 {} "$pkgdir/usr/include/hyprland/wlroots/{}" \;
	popd
	pushd subprojects/wlroots/build/include
	find . -name '*.h' -exec install -Dm0644 {} "$pkgdir/usr/include/hyprland/wlroots/{}" \;
	popd
	mkdir -p "$pkgdir/usr/include/hyprland/protocols"
	cp protocols/*-protocol.h "$pkgdir/usr/include/hyprland/protocols"
	pushd build
	cmake -DCMAKE_INSTALL_PREFIX=/usr ..
	popd
	install -Dm0644 -t "$pkgdir/usr/share/pkgconfig" build/hyprland.pc
	install -Dm0755 -t "$pkgdir/usr/bin" build/Hyprland
	install -Dm0755 -t "$pkgdir/usr/bin" hyprctl/hyprctl
	install -Dm0644 -t "$pkgdir/usr/share/$pkgname" assets/*.png
	install -Dm0644 -t "$pkgdir/usr/share/wayland-sessions" "example/$pkgname.desktop"
	install -Dm0644 -t "$pkgdir/usr/share/$pkgname" "example/$pkgname.conf"
	install -Dm0644 -t "$pkgdir/usr/share/licenses/$pkgname/" LICENSE
	install -Dm0755 -t "$pkgdir/usr/lib" "$srcdir/tmpwlr/lib/libwlroots.so.12032"
}

```

**Comment by vaxerski** [comment]
what does 10bit break? 

You have 2 issues here:
 - waybar transparency
 - crashes
 
which ones do crop up when 10bit is enabled and which ones dont?

**Comment by ronasimi** [comment]
I'm not getting soft locks and waybar transparency is working since I fixed my PKGBUILD.  The only issue I"m still having in artifacts on waybar when 10 bit is enabled, which is the same issue I've been having since 0.32.0

**Comment by vaxerski** [comment]
but that is reported @ #3822

So I will close this as an issue with your pkgbuild :)
