### ISSUE TITLE
Xwayland causes Hyprland to crash 

### ISSUE THREAD

**Issue by h0tc0d3** [hyprwm/Hyprland#3998]
### Hyprland Version

main

### Bug or Regression?

Bug

### Description

xwaylnd app causing hyprland to crash.

Commit: https://github.com/hyprwm/Hyprland/commit/d2c3b23ace745d3f79926c71d4cb3c481a394841

### How to reproduce

Build. Run xwayland app.

### Crash reports, logs, images, videos

```
(gdb) bt full
#0  0x00007f1f2a4ae834 in __pthread_kill_implementation () at /lib64/libc.so.6
#1  0x00007f1f2a45c8ee in raise () at /lib64/libc.so.6
#2  0x00007f1f2a4448ff in abort () at /lib64/libc.so.6
#3  0x00005619940dbd93 in handleUnrecoverableSignal(int) ()
#4  0x00007f1f2a45c9a0 in <signal handler called> () at /lib64/libc.so.6
#5  0x00007f1f2a4ae834 in __pthread_kill_implementation () at /lib64/libc.so.6
#6  0x00007f1f2a45c8ee in raise () at /lib64/libc.so.6
#7  0x00005619942238a9 in CFramebuffer::alloc(int, int, unsigned int) ()
#8  0x000056199423347a in CHyprOpenGLImpl::makeLayerSnapshot(SLayerSurface*) ()
#9  0x0000561994176dc2 in Events::listener_unmapLayerSurface(void*, void*) ()
#10 0x00005619941a7b91 in handleWrapped(wl_listener*, void*) ()
#11 0x00007f1f2af8cdcc in wl_signal_emit_mutable () at /lib64/libwayland-server.so.0
#12 0x000056199429950a in wlr_surface_unmap ()
#13 0x000056199429ac54 in  ()
#14 0x00007f1f2af8e791 in destroy_resource () at /lib64/libwayland-server.so.0
#15 0x00007f1f2af8ef2b in wl_client_destroy () at /lib64/libwayland-server.so.0
#16 0x00007f1f2af8f4b8 in wl_client_connection_data () at /lib64/libwayland-server.so.0
#17 0x00007f1f2af8e8e2 in wl_event_loop_dispatch () at /lib64/libwayland-server.so.0
#18 0x00007f1f2af8f125 in wl_display_run () at /lib64/libwayland-server.so.0
#19 0x00005619940e4ae6 in CCompositor::startCompositor() ()
#20 0x00005619941c1bb5 in main ()
```

**Comment by vaxerski** [comment]
it's not even an xwayland app, it's a layersurface being unmapped.
