### ISSUE TITLE
Assertion fail when windows get too small

### ISSUE THREAD

**Issue by russelltg** [hyprwm/Hyprland#4591]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
git 7447be822080fac5b8515a177773ec74b4d6c925
```

</details>

### Bug or Regression?

Bug

### Description

While I was running a asan build figured I'd try to break stuff a little....

Hyprland crashed

### How to reproduce

Make a bunch of really tiny windows (by repeatedly opening, say, a terminal)

### Crash reports, logs, images, videos

```
(gdb) bt
#0  handleUnrecoverableSignal (sig=6) at /home/russell/Hyprland/src/Compositor.cpp:24
#1  0x00007fd56e14c710 in <signal handler called> () at /usr/lib/libc.so.6
#2  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#3  0x00007fd56e19c8a3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#4  0x00007fd56e14c668 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#5  0x00007fd56e1344b8 in __GI_abort () at abort.c:79
#6  0x00007fd56e1343dc in __assert_fail_base
    (fmt=0x7fd56e2adae8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x7fd56ee94480 "width >= 0 && height >= 0", file=file@entry=0x7fd56ee93fa0 "types/xdg_shell/wlr_xdg_toplevel.c", line=line@entry=558, function=function@entry=0x7fd56ee947c0 <__PRETTY_FUNCTION__.4> "wlr_xdg_toplevel_set_size") at assert.c:92
#7  0x00007fd56e144d26 in __assert_fail
    (assertion=0x7fd56ee94480 "width >= 0 && height >= 0", file=0x7fd56ee93fa0 "types/xdg_shell/wlr_xdg_toplevel.c", line=558, function=0x7fd56ee947c0 <__PRETTY_FUNCTION__.4> "wlr_xdg_toplevel_set_size") at assert.c:101
#8  0x00007fd56ed82639 in wlr_xdg_toplevel_set_size (toplevel=0x51400021ae40, width=46, height=-1) at ../types/xdg_shell/wlr_xdg_toplevel.c:558
#9  0x00005bce9610387b in CHyprXWaylandManager::setWindowSize (this=0x502000024f90, pWindow=0x522000051100, size=..., force=false) at /home/russell/Hyprland/src/managers/XWaylandManager.cpp:181
#10 0x00005bce96010bfb in CHyprDwindleLayout::applyNodeDataToWindow (this=0x513000000908, pNode=0x50d0001a4d80, force=true) at /home/russell/Hyprland/src/layout/DwindleLayout.cpp:232
#11 0x00005bce9600bc04 in SDwindleNodeData::recalcSizePosRecursive (this=0x50d0001a4d80, force=true, horizontalOverride=false, verticalOverride=false) at /home/russell/Hyprland/src/layout/DwindleLayout.cpp:37
#12 0x00005bce9600bb5f in SDwindleNodeData::recalcSizePosRecursive (this=0x50d0001b4620, force=true, horizontalOverride=false, verticalOverride=false) at /home/russell/Hyprland/src/layout/DwindleLayout.cpp:34
#13 0x00005bce9600bbb3 in SDwindleNodeData::recalcSizePosRecursive (this=0x50d0001a4ff0, force=true, horizontalOverride=false, verticalOverride=false) at /home/russell/Hyprland/src/layout/DwindleLayout.cpp:35
#14 0x00005bce9600bb5f in SDwindleNodeData::recalcSizePosRecursive (this=0x50d0001a01f0, force=true, horizontalOverride=false, verticalOverride=false) at /home/russell/Hyprland/src/layout/DwindleLayout.cpp:34
#15 0x00005bce9600bbb3 in SDwindleNodeData::recalcSizePosRecursive (this=0x50d000198260, force=true, horizontalOverride=false, verticalOverride=false) at /home/russell/Hyprland/src/layout/DwindleLayout.cpp:35
#16 0x00005bce9600bbb3 in SDwindleNodeData::recalcSizePosRecursive (this=0x50d00018a970, force=true, horizontalOverride=false, verticalOverride=false) at /home/russell/Hyprland/src/layout/DwindleLayout.cpp:35
#17 0x00005bce9600bb5f in SDwindleNodeData::recalcSizePosRecursive (this=0x50d000185f80, force=true, horizontalOverride=false, verticalOverride=false) at /home/russell/Hyprland/src/layout/DwindleLayout.cpp:34
#18 0x00005bce9600bbb3 in SDwindleNodeData::recalcSizePosRecursive (this=0x50d0000dfea0, force=true, horizontalOverride=false, verticalOverride=false) at /home/russell/Hyprland/src/layout/DwindleLayout.cpp:35
#19 0x00005bce9601bc95 in CHyprDwindleLayout::resizeActiveWindow (this=0x513000000908, pixResize=..., corner=CORNER_BOTTOMRIGHT, pWindow=0x522000048100) at /home/russell/Hyprland/src/layout/DwindleLayout.cpp:720
#20 0x00005bce960374ba in IHyprLayout::onMouseMove (this=0x513000000908, mousePos=...) at /home/russell/Hyprland/src/layout/IHyprLayout.cpp:399
#21 0x00005bce96118151 in CInputManager::mouseMoveUnified (this=0x51c000012080, time=2442146, refocus=false) at /home/russell/Hyprland/src/managers/input/InputManager.cpp:221
#22 0x00005bce961149e8 in CInputManager::onMouseMoved (this=0x51c000012080, e=0x7fd56a7bddb0) at /home/russell/Hyprland/src/managers/input/InputManager.cpp:34
#23 0x00005bce95efeadd in Events::listener_mouseMove (listener=0x5bce966ffce0 <Events::listen_mouseMove>, data=0x7fd56a7bddb0) at /home/russell/Hyprland/src/events/Devices.cpp:40
#24 0x00007fd56f6f401e in wl_signal_emit_mutable (signal=<optimized out>, data=0x7fd56a7bddb0) at ../wayland-1.22.0/src/wayland-server.c:2241
#25 0x00007fd56ed961c7 in handle_pointer_motion (listener=0x5160000132b8, data=0x7fd56a7bddb0) at ../types/wlr_cursor.c:676
#26 0x00007fd56f6f401e in wl_signal_emit_mutable (signal=<optimized out>, data=0x7fd56a7bddb0) at ../wayland-1.22.0/src/wayland-server.c:2241
#27 0x00007fd56ed033c8 in handle_pointer_motion (event=0x50b000337fc0, pointer=0x51a000020c08) at ../backend/libinput/pointer.c:39
#28 0x00007fd56ed026b0 in handle_libinput_event (backend=0x50d000010c60, event=0x50b000337fc0) at ../backend/libinput/events.c:167
#29 0x00007fd56ed00fcb in handle_libinput_readable (fd=40, mask=1, _backend=0x50d000010c60) at ../backend/libinput/backend.c:59
#30 0x00007fd56f6f5ae2 in wl_event_loop_dispatch (loop=0x50d000000450, timeout=timeout@entry=-1) at ../wayland-1.22.0/src/event-loop.c:1027
#31 0x00007fd56f6f62d7 in wl_display_run (display=0x511000001440) at ../wayland-1.22.0/src/wayland-server.c:1493
#32 0x00005bce95c018f5 in CCompositor::startCompositor (this=0x518000000480) at /home/russell/Hyprland/src/Compositor.cpp:611
#33 0x00005bce9606b9dc in main (argc=3, argv=0x7ffe4bc63f98) at /home/russell/Hyprland/src/main.cpp:111
```

seems the window get a negative height!

**Comment by vaxerski** [comment]
aw man
