### ISSUE TITLE
Coredump caused by `stoi` when parsing config file

### ISSUE THREAD

**Issue by horror-proton** [hyprwm/Hyprland#5121]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 3e930a568a76a810dde6bcabcf737a81850e7153 dirty (format: fix format).
Date: Sat Mar 9 11:09:25 2024
Tag: v0.36.0-79-g3e930a56

flags: (if any)


System Information:
System name: Linux
Node name: archlinux
Release: 6.7.9-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Fri, 08 Mar 2024 01:58:50 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Alder Lake-P GT1 [UHD Graphics] [8086:46a3] (rev 0c) (prog-if 00 [VGA controller])
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA107M [GeForce RTX 3050 Mobile] [10de:25a2] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

Line with wrong format in config file causes Hyprland to crash 

### How to reproduce

add and save something like `monitor=HDMI-A-1,auto,auto,1,mirror` to config file

### Crash reports, logs, images, videos

something like `std::stoi` and `std::stol` should not be used directly 

```
>>> bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007b0f2e086393 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007b0f2e0356c8 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007b0f2e01d4b8 in __GI_abort () at abort.c:79
#4  0x00005b6d1ebefd52 in handleUnrecoverableSignal (sig=6) at /usr/src/debug/hyprland-git/Hyprland/src/Compositor.cpp:35
#5  0x00007b0f2e035770 in <signal handler called> () at /usr/lib/libc.so.6
#6  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#7  0x00007b0f2e086393 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#8  0x00007b0f2e0356c8 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#9  0x00007b0f2e01d4b8 in __GI_abort () at abort.c:79
#10 0x00007b0f2e29ca6f in __gnu_cxx::__verbose_terminate_handler () at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#11 0x00007b0f2e2b011c in __cxxabiv1::__terminate (handler=<optimized out>) at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:48
#12 0x00007b0f2e2b0189 in std::terminate () at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:58
#13 0x00007b0f2e2b03ed in __cxxabiv1::__cxa_throw (obj=<optimized out>, tinfo=0x7b0f2e46c0b8 <typeinfo for std::invalid_argument>, dest=0x7b0f2e2c8540 <std::invalid_argument::~invalid_argument()>) at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/eh_throw.cc:98
#14 0x00007b0f2e2a0163 in std::__throw_invalid_argument (__s=__s@entry=0x5b6d1ed735b4 "stoi") at /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++11/functexcept.cc:78
#15 0x00005b6d1ed575df in __gnu_cxx::__stoa<long, int, char, int>(long (*)(char const*, char**, int), char const*, char const*, unsigned long*, int) [clone .constprop.0] (__str=0x7ffc381a6fb0 "auto", __idx=0x0, __name=0x5b6d1ed735b4 "stoi", __convf=<optimized out>) at /usr/include/c++/13.2.1/ext/string_conversions.h:85
#16 0x00005b6d1ec5528c in std::__cxx11::stoi (__base=10, __idx=0x0, __str="auto", __str=<optimized out>, __idx=<optimized out>, __base=<optimized out>) at /usr/include/c++/13.2.1/bits/basic_string.h:222
#17 CConfigManager::handleMonitor (this=0x5b6d1f4fe340, command=<optimized out>, args=<optimized out>) at /usr/src/debug/hyprland-git/Hyprland/src/config/ConfigManager.cpp:1564
#18 0x00005b6d1ec370f0 in handleMonitor (c=<optimized out>, v=<optimized out>) at /usr/src/debug/hyprland-git/Hyprland/src/config/ConfigManager.cpp:134
#19 0x00007b0f2e5bbaf1 in Hyprlang::CConfig::parseLine(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool) () at /usr/lib/libhyprlang.so.1
#20 0x00007b0f2e5bcdff in Hyprlang::CConfig::parseFile(char const*) () at /usr/lib/libhyprlang.so.1
#21 0x00007b0f2e5bead7 in Hyprlang::CConfig::parse() () at /usr/lib/libhyprlang.so.1
#22 0x00005b6d1ec3ddd8 in CConfigManager::reload (this=0x5b6d1f4fe340) at /usr/include/c++/13.2.1/bits/unique_ptr.h:199
#23 0x00005b6d1ec47e2f in CConfigManager::tick (this=0x5b6d1f4fe340) at /usr/src/debug/hyprland-git/Hyprland/src/config/ConfigManager.cpp:880
#24 0x00005b6d1ecec83a in handleTimer (data=0x5b6d1ff341e0) at /usr/src/debug/hyprland-git/Hyprland/src/managers/ThreadManager.cpp:14
#25 0x00007b0f2e950d27 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#26 0x00007b0f2e9512d7 in wl_display_run () at /usr/lib/libwayland-server.so.0
#27 0x00005b6d1ebf18c9 in CCompositor::startCompositor (this=0x5b6d1f4f8c40) at /usr/src/debug/hyprland-git/Hyprland/src/Compositor.cpp:624
#28 0x00005b6d1ebd79a7 in main (argc=1, argv=0x7ffc381a82e8) at /usr/include/c++/13.2.1/bits/unique_ptr.h:199
>>> frame  17
#17 CConfigManager::handleMonitor (this=0x5b6d1f4fe340, command=..., args=...) at /usr/src/debug/hyprland-git/Hyprland/src/config/ConfigManager.cpp:1564
1564	       newrule.resolution.x = stoi(ARGS[1].substr(0, ARGS[1].find_first_of('x')));
>>> print ARGS
$2 = {
  m_vArgs = std::vector of length 5, capacity 8 = {[0] = "HDMI-A-1", [1] = "auto", [2] = "auto", [3] = "1", [4] = "mirror"}
}
```

**Comment by vaxerski** [comment]
I know and it has been fixed, update
