### ISSUE TITLE
Crash on drag

### ISSUE THREAD

**Issue by g3r** [hyprwm/Hyprland#5125]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit c4f52d19792696b8b297877b9152bd86d0f4624b dirty (master: fix invalid config usage).
Date: Fri Mar 15 16:31:33 2024
Tag: v0.36.0-119-gc4f52d19

flags: (if any)


System Information:
System name: Linux
Node name: KRONOS
Release: 6.7.7-1-MANJARO
Version: #1 SMP PREEMPT_DYNAMIC Fri Mar  1 18:26:06 UTC 2024


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GM206 [GeForce GTX 960] [10de:1401] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Manjaro Linux"
PRETTY_NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://forum.manjaro.org/"
BUG_REPORT_URL="https://docs.manjaro.org/reporting-bugs/"
PRIVACY_POLICY_URL="https://manjaro.org/privacy-policy/"
LOGO=manjarolinux


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

Hyprland crashes when dragging something

### How to reproduce

Open dolphin file manager
start dragging a file
Hyprland crashes

### Crash reports, logs, images, videos

```
(gdb) thread apply all bt

Thread 2 (Thread 0x715e6be006c0 (LWP 47374)):
#0  0x0000715e6fbb7ebe in ??? () at /usr/lib/libc.so.6
#1  0x0000715e6fbbad35 in pthread_cond_clockwait () at /usr/lib/libc.so.6
#2  0x00005b56f0747379 in ??? ()
#3  0x0000715e6fee1943 in std::execute_native_thread_routine (__p=0x5b56f1b2c2b0) at /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++11/thread.cc:104
#4  0x0000715e6fbbb55a in ??? () at /usr/lib/libc.so.6
#5  0x0000715e6fc38a3c in ??? () at /usr/lib/libc.so.6

Thread 1 (Thread 0x715e6e0e9ac0 (LWP 47358)):
#0  0x0000715e6fbbd32c in ??? () at /usr/lib/libc.so.6
#1  0x0000715e6fb6c6c8 in raise () at /usr/lib/libc.so.6
#2  0x0000715e6fb544b8 in abort () at /usr/lib/libc.so.6
#3  0x00005b56f069385e in handleUnrecoverableSignal(int) ()
#4  0x0000715e6fb6c770 in <signal handler called> () at /usr/lib/libc.so.6
#5  0x00005b56f07c0b07 in ??? ()
#6  0x0000715e706d99ae in ??? () at /usr/lib/libwlroots.so.13032
#7  0x00005b56f07c8898 in CHyprRenderer::renderDragIcon(CMonitor*, timespec*) ()
#8  0x00005b56f07c91c8 in CHyprRenderer::renderAllClientsForWorkspace(CMonitor*, CWorkspace*, timespec*, Vector2D const&, float const&) ()
#9  0x00005b56f07c9869 in CHyprRenderer::renderWorkspace(CMonitor*, CWorkspace*, timespec*, CBox const&) ()
#10 0x00005b56f07cab14 in CHyprRenderer::renderMonitor(CMonitor*) ()
#11 0x00005b56f07471fb in handleWrapped(wl_listener*, void*) ()
#12 0x0000715e7065d01e in wl_signal_emit_mutable () at /usr/lib/libwayland-server.so.0
#13 0x0000715e706af329 in ??? () at /usr/lib/libwlroots.so.13032
#14 0x0000715e7064a907 in drmHandleEvent () at /usr/lib/libdrm.so.2
#15 0x0000715e706a8d01 in ??? () at /usr/lib/libwlroots.so.13032
#16 0x0000715e7065eae2 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#17 0x0000715e7065f2d7 in wl_display_run () at /usr/lib/libwayland-server.so.0
#18 0x00005b56f067abdc in main ()
```

**Comment by xusiai** [comment]
Happening to me as well (although I'm using Thunar) on NixOS after updating to c4f52d19792696b8b297877b9152bd86d0f4624b and it happens _every_ time. No log file is produced.
