### ISSUE TITLE
coredump on exit

### ISSUE THREAD

**Issue by gulafaran** [hyprwm/Hyprland#5471]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 3875679755014997776e091ff8903acfb311dd2f  (props: bump ver to 0.38.0).
Date: Mon Apr 1 18:30:37 2024
Tag: v0.38.0

flags: (if any)


System Information:
System name: Linux
Node name: tom-legion
Release: 6.8.4-gentoo-tom
Version: #1 SMP PREEMPT_DYNAMIC Fri Apr  5 14:00:55 CEST 2024


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Raptor Lake-S UHD Graphics [8086:a788] (rev 04) (prog-if 00 [VGA controller])
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD104M [GeForce RTX 4080 Max-Q / Mobile] [10de:27e0] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
VERSION_ID="2.15"


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

everytime i exit hyprland $mainMod, M, exit. im getting a coredump

```
Core was generated by `Hyprland'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00005555556fc614 in std::operator- (__x=..., __y=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/stl_deque.h:373
373		 * (__x._M_node - __y._M_node - bool(__x._M_node))
[Current thread is 1 (Thread 0x7ffff645eac0 (LWP 641950))]
(gdb) bt
#0  0x00005555556fc614 in std::operator- (__x=<error reading variable: Cannot access memory at address 0x360>, __y=<error reading variable: Cannot access memory at address 0x340>) at /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/stl_deque.h:373
#1  0x00005555556fbf7d in std::deque<SLayerSurface*, std::allocator<SLayerSurface*> >::size (this=0x330) at /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/stl_deque.h:1269
#2  0x00005555556fb74e in std::erase<SLayerSurface*, std::allocator<SLayerSurface*>, SLayerSurface*> (__cont=<error reading variable: Cannot access memory at address 0x378>, __value=@0x7fffffffc740: 0x555557e292e0) at /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/deque:122
#3  0x00005555556f9908 in Events::listener_unmapLayerSurface (owner=0x555557e292e0, data=0x0) at ../hyprland-source/src/events/Layers.cpp:188
#4  0x00005555556d4697 in std::__invoke_impl<void, void (*&)(void*, void*), void*, void*> (__f=@0x555557e296d8: 0x5555556f9694 <Events::listener_unmapLayerSurface(void*, void*)>) at /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/invoke.h:61
#5  0x00005555556d4108 in std::__invoke_r<void, void (*&)(void*, void*), void*, void*> (__fn=@0x555557e296d8: 0x5555556f9694 <Events::listener_unmapLayerSurface(void*, void*)>) at /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/invoke.h:111
#6  0x00005555556d3973 in std::_Function_handler<void (void*, void*), void (*)(void*, void*)>::_M_invoke(std::_Any_data const&, void*&&, void*&&) (__functor=..., __args#0=@0x7fffffffc970: 0x555557e292e0, __args#1=@0x7fffffffc968: 0x0)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/std_function.h:290
#7  0x000055555573da85 in std::function<void (void*, void*)>::operator()(void*, void*) const (this=0x555557e296d8, __args#0=0x555557e292e0, __args#1=0x0) at /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/std_function.h:591
#8  0x000055555573d3ff in CHyprWLListener::emit (this=0x555557e296b0, data=0x0) at ../hyprland-source/src/helpers/WLListener.cpp:61
#9  0x000055555573d1a6 in handleWrapped (listener=0x555557e296b0, data=0x0) at ../hyprland-source/src/helpers/WLListener.cpp:14
#10 0x00007ffff7f97ae8 in wl_signal_emit_mutable () at /usr/lib64/libwayland-server.so.0
#11 0x00005555558a07f9 in wlr_surface_unmap (surface=surface@entry=0x555557e286b0) at ../hyprland-source/subprojects/wlroots/types/wlr_compositor.c:854
#12 0x00005555558a21c8 in wlr_surface_unmap (surface=0x555557e286b0) at ../hyprland-source/subprojects/wlroots/types/wlr_compositor.c:752
#13 surface_destroy_role_object (surface=0x555557e286b0) at ../hyprland-source/subprojects/wlroots/types/wlr_compositor.c:932
#14 surface_destroy_role_object (surface=0x555557e286b0) at ../hyprland-source/subprojects/wlroots/types/wlr_compositor.c:928
#15 surface_handle_resource_destroy (resource=<optimized out>) at ../hyprland-source/subprojects/wlroots/types/wlr_compositor.c:727
#16 0x00007ffff7f933db in ??? () at /usr/lib64/libwayland-server.so.0
#17 0x00007ffff7f9950b in wl_client_destroy () at /usr/lib64/libwayland-server.so.0
#18 0x00007ffff7f996a9 in wl_display_destroy_clients () at /usr/lib64/libwayland-server.so.0
#19 0x00005555555e4d0a in CCompositor::cleanup (this=0x555555b53ca0) at ../hyprland-source/src/Compositor.cpp:425
#20 0x0000555555705c62 in Events::listener_monitorFrame (owner=0x5555568f3780, data=0x555556905660) at ../hyprland-source/src/events/Monitors.cpp:123
#21 0x00005555556d4697 in std::__invoke_impl<void, void (*&)(void*, void*), void*, void*> (__f=@0x5555568f3bb0: 0x555555705bfd <Events::listener_monitorFrame(void*, void*)>) at /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/invoke.h:61
#22 0x00005555556d4108 in std::__invoke_r<void, void (*&)(void*, void*), void*, void*> (__fn=@0x5555568f3bb0: 0x555555705bfd <Events::listener_monitorFrame(void*, void*)>) at /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/invoke.h:111
#23 0x00005555556d3973 in std::_Function_handler<void (void*, void*), void (*)(void*, void*)>::_M_invoke(std::_Any_data const&, void*&&, void*&&) (__functor=..., __args#0=@0x7fffffffcdf0: 0x5555568f3780, __args#1=@0x7fffffffcde8: 0x555556905660)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/std_function.h:290
#24 0x000055555573da85 in std::function<void (void*, void*)>::operator()(void*, void*) const (this=0x5555568f3bb0, __args#0=0x5555568f3780, __args#1=0x555556905660) at /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/std_function.h:591
#25 0x000055555573d3ff in CHyprWLListener::emit (this=0x5555568f3b88, data=0x555556905660) at ../hyprland-source/src/helpers/WLListener.cpp:61
#26 0x000055555573d1a6 in handleWrapped (listener=0x5555568f3b88, data=0x555556905660) at ../hyprland-source/src/helpers/WLListener.cpp:14
#27 0x00007ffff7f97ae8 in wl_signal_emit_mutable () at /usr/lib64/libwayland-server.so.0
#28 0x0000555555877185 in wlr_output_send_frame (output=0x555556905660) at ../hyprland-source/subprojects/wlroots/types/output/output.c:734
#29 wlr_output_send_frame (output=0x555556905660) at ../hyprland-source/subprojects/wlroots/types/output/output.c:731
#30 handle_page_flip (fd=<optimized out>, seq=276906, tv_sec=69943, tv_usec=411107, crtc_id=<optimized out>, data=<optimized out>) at ../hyprland-source/subprojects/wlroots/backend/drm/drm.c:1907
#31 0x00007ffff7f767a7 in drmHandleEvent () at /usr/lib64/libdrm.so.2
#32 0x0000555555874a59 in handle_drm_event (fd=<optimized out>, mask=<optimized out>, data=0x555555b98b40) at ../hyprland-source/subprojects/wlroots/backend/drm/drm.c:1919
#33 0x00007ffff7f9b8e2 in wl_event_loop_dispatch () at /usr/lib64/libwayland-server.so.0
#34 0x00007ffff7f9bdbe in wl_display_run () at /usr/lib64/libwayland-server.so.0
#35 0x00005555555e6957 in CCompositor::startCompositor (this=0x555555b53ca0) at ../hyprland-source/src/Compositor.cpp:631
#36 0x0000555555765c66 in main (argc=1, argv=0x7fffffffdc88) at ../hyprland-source/src/main.cpp:111

```

### How to reproduce

run hyprland, exit it with $mainMod, M, exit.

doesnt generate a crash report in ~/.cache/hyprland but i get it in my journal.

**Comment by thejch** [comment]
https://github.com/hyprwm/Hyprland/issues/4849
