### ISSUE TITLE
crash after screen unlock and turning on dpms

### ISSUE THREAD

**Issue by andresilva** [hyprwm/Hyprland#5535]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 303b9956b2ae15508b09dffae602550ca17e6539  ().
Date: 2024-04-10
Tag: , commits: @COMMITS@

flags: (if any)

System Information:
System name: Linux
Release: 6.8.4

GPU information: 
0a:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 31 [Radeon RX 7900 XT/7900 XTX/7900M] [1002:744c] (rev c8) (prog-if 00 [VGA controller])

os-release: 

NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"

plugins:


```

</details>

### Bug or Regression?

Bug

### Description

After the screen is unlocked (through hyprlock) and dpms is turned back on, randomly firefox (and emacs) scaling looks completely broken. Afterwards it leads to an immediate crash, in other cases the crash is delayed or it doesn't happen at all.

Log below shows:

`[ERR] BUG THIS: No CWLSurface for surface in damageSurface!!!`

### How to reproduce

I can eventually replicate the issue by running `loginctl lock-session; sleep 5; hyprctl dispatch dpms off; sleep 15; hyprctl dispatch dpms on; sleep 5; kill -SIGUSR1 $(pidof hyprlock)` a bunch of times.

### Crash reports, logs, images, videos

[hyprlandCrashReport506900.txt](https://github.com/hyprwm/Hyprland/files/14933492/hyprlandCrashReport506900.txt)

**Comment by andresilva** [comment]
Another crash report that is different.

[hyprlandCrashReport587062.txt](https://github.com/hyprwm/Hyprland/files/14936143/hyprlandCrashReport587062.txt)

**Comment by vaxerski** [comment]
can you try systemd's `coredumpctl debug Hyprland` with `bt -full`? the stacktraces kinda poop

**Comment by andresilva** [comment]
The backtrace is useless, just prints "no symbol table info available" for all threads. I'll run a debug build and try to reproduce.

**Comment by andresilva** [comment]
Unlocked the screen, emacs scaling was fucked, closed it, opened rofi and crash.

[hyprlandCrashReport52152.txt](https://github.com/hyprwm/Hyprland/files/14946939/hyprlandCrashReport52152.txt)

```
#0  0x00007f96270a2efc in __pthread_kill_implementation () from /nix/store/ddwyrxif62r8n6xclvskjyy6szdhvj60-glibc-2.39-5/lib/libc.so.6
No symbol table info available.
#1  0x00007f9627052e86 in raise () from /nix/store/ddwyrxif62r8n6xclvskjyy6szdhvj60-glibc-2.39-5/lib/libc.so.6
No symbol table info available.
#2  0x00007f962703b935 in abort () from /nix/store/ddwyrxif62r8n6xclvskjyy6szdhvj60-glibc-2.39-5/lib/libc.so.6
No symbol table info available.
#3  0x00000000006dc57e in handleUnrecoverableSignal(int) ()
No symbol table info available.
#4  <signal handler called>
No symbol table info available.
#5  0x00000000020250d8 in ?? ()
No symbol table info available.
#6  0x00007f9627dd1a0c in wl_signal_emit_mutable () from /nix/store/blw10rx1cayp2n2pkmyihpipifzgj2xq-wayland-1.22.0/lib/libwayland-server.so.0
No symbol table info available.
#7  0x00007f9627d14393 in output_bind () from /nix/store/sgavsg936bdg00cs3lg011ydxinjiv04-wlroots-hyprland-2024-03-09_50eae51/lib/libwlroots.so.13
No symbol table info available.
#8  0x00007f96274d1052 in ffi_call_unix64 () from /nix/store/f8ipgi6l1n1c0wr1r5aj40phnd6fkmv8-libffi-3.4.6/lib/libffi.so.8
No symbol table info available.
#9  0x00007f96274ceee5 in ffi_call_int () from /nix/store/f8ipgi6l1n1c0wr1r5aj40phnd6fkmv8-libffi-3.4.6/lib/libffi.so.8
No symbol table info available.
#10 0x00007f96274cfad8 in ffi_call () from /nix/store/f8ipgi6l1n1c0wr1r5aj40phnd6fkmv8-libffi-3.4.6/lib/libffi.so.8
No symbol table info available.
#11 0x00007f9627dd5841 in wl_closure_invoke () from /nix/store/blw10rx1cayp2n2pkmyihpipifzgj2xq-wayland-1.22.0/lib/libwayland-server.so.0
No symbol table info available.
#12 0x00007f9627dd0c4b in wl_client_connection_data () from /nix/store/blw10rx1cayp2n2pkmyihpipifzgj2xq-wayland-1.22.0/lib/libwayland-server.so.0
No symbol table info available.
#13 0x00007f9627dd38f2 in wl_event_loop_dispatch () from /nix/store/blw10rx1cayp2n2pkmyihpipifzgj2xq-wayland-1.22.0/lib/libwayland-server.so.0
No symbol table info available.
#14 0x00007f9627dd1455 in wl_display_run () from /nix/store/blw10rx1cayp2n2pkmyihpipifzgj2xq-wayland-1.22.0/lib/libwayland-server.so.0
No symbol table info available.
#15 0x000000000090aa7a in CEventLoopManager::enterLoop(wl_display*, wl_event_loop*) ()
No symbol table info available.
#16 0x00000000006e1b8f in CCompositor::startCompositor() ()
No symbol table info available.
#17 0x00000000008bd640 in main ()
No symbol table info available.
```

**Comment by andresilva** [comment]
After a bisect session this is the commit introducing the problem: c3882bb83240b602277f2d22f21d71690531f62e

**Comment by andresilva** [comment]
No idea what's happening here. I don't have any hyprcursor theme, just using xcursor. I tried building Hyprland with latest hyprcursor, setting an hyprcursor theme, not setting any xcursor theme. In all cases was able to replicate.

**Comment by vaxerski** [comment]
Maybe ASan will show something interesting? https://wiki.hyprland.org/Crashes-and-Bugs/#building-the-wayland-stack-with-asan

**Comment by andresilva** [comment]
Asan log seems pretty useless 😥

```
=================================================================
==207007==ERROR: AddressSanitizer: SEGV on unknown address 0x617000051798 (pc 0x617000051798 bp 0x7ffffffed160 sp 0x7ffffffed058 T0)
==207007==The signal is caused by a READ memory access.
==207007==Hint: PC is at a non-executable region. Maybe a wild jump?
    #0 0x617000051798  (<unknown module>)
    #1 0x7ffff7544c80 in output_bind ../types/output/output.c:126
    #2 0xe770d2 in registry_bind ../src/wayland-server.c:1023
    #3 0x7ffff6db8051 in ffi_call_unix64 (/nix/store/f8ipgi6l1n1c0wr1r5aj40phnd6fkmv8-libffi-3.4.6/lib/libffi.so.8+0xa051)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (<unknown module>) 
==207007==ABORTING
```

**Comment by andresilva** [comment]
<img src="https://github.com/hyprwm/Hyprland/assets/123550/501f3e7b-1ae9-47a2-b37e-0f3d95cd8f2d" width="490.625">

This is what it looks like after unlocking, the browser window just gets blurred (it happens in emacs as well). It seems that the issue isn't related to hyprcursor though, this just happened on 0.36.0 although it didn't lead to a crash and it's way less prevalent (been running it for some days now without triggering). Also in the case of firefox the blurriness fixed itself after I interacted with the window. Any idea about which part of the code could be related to this? I'm using fractional scaling in case that's relevant.

**Comment by andresilva** [comment]
Nevermind, it did crash eventually:

```
        #0 | /nix/store/fx7plpzxdnbffm97b84mw6qc6m1d2irf-hyprland-0.36.0+date=2024-04-14_ff39ac1/bin/.Hyprland-wrapped_(_Z12getBacktracev+0x48) [0x5788f8]
                getBacktrace()
                ??:?
        #1 | /nix/store/fx7plpzxdnbffm97b84mw6qc6m1d2irf-hyprland-0.36.0+date=2024-04-14_ff39ac1/bin/.Hyprland-wrapped_(_ZN13CrashReporter18createAndSaveCrashEi+0x6b5) [0x52b7f5]
                CrashReporter::createAndSaveCrash(int)
                ??:?
        #2 | /nix/store/fx7plpzxdnbffm97b84mw6qc6m1d2irf-hyprland-0.36.0+date=2024-04-14_ff39ac1/bin/.Hyprland-wrapped_(_Z25handleUnrecoverableSignali+0x44) [0x4a2fb4]
                handleUnrecoverableSignal(int)
                ??:?
        #3 | /nix/store/ddwyrxif62r8n6xclvskjyy6szdhvj60-glibc-2.39-5/lib/libc.so.6(+0x3ff30) [0x7fd61c252f30]
                ??
                ??:0
        #4 | /nix/store/blw10rx1cayp2n2pkmyihpipifzgj2xq-wayland-1.22.0/lib/libwayland-server.so.0(wl_list_insert+0x14) [0x7fd61cfce494]
                ??
                ??:0
        #5 | /nix/store/blw10rx1cayp2n2pkmyihpipifzgj2xq-wayland-1.22.0/lib/libwayland-server.so.0(wl_signal_emit_mutable+0x39) [0x7fd61cfc99c9]
                ??
                ??:0
        #6 | /nix/store/h147jd0fh2qyg2k24cxf6z5av7jx9y9y-wlroots-hyprland-2024-02-21_0cb091f/lib/libwlroots.so.13(wlr_output_schedule_frame+0x9) [0x7fd61cf0cc59]
                ??
                ??:0
        #7 | /nix/store/fx7plpzxdnbffm97b84mw6qc6m1d2irf-hyprland-0.36.0+date=2024-04-14_ff39ac1/bin/.Hyprland-wrapped_(_ZN13CHyprRenderer9damageBoxEP4CBox+0xa8) [0x653478]
                CHyprRenderer::damageBox(CBox*)
                ??:?
        #8 | /nix/store/fx7plpzxdnbffm97b84mw6qc6m1d2irf-hyprland-0.36.0+date=2024-04-14_ff39ac1/bin/.Hyprland-wrapped_(_ZN6Events27listener_commitLayerSurfaceEPvS0_+0xaa) [0x54fe9a]
                Events::listener_commitLayerSurface(void*, void*)
                ??:?
        #9 | /nix/store/fx7plpzxdnbffm97b84mw6qc6m1d2irf-hyprland-0.36.0+date=2024-04-14_ff39ac1/bin/.Hyprland-wrapped_(_ZN15CHyprWLListener4emitEPv+0x3b) [0x591fdb]
                CHyprWLListener::emit(void*)
                ??:?
        #10 | /nix/store/fx7plpzxdnbffm97b84mw6qc6m1d2irf-hyprland-0.36.0+date=2024-04-14_ff39ac1/bin/.Hyprland-wrapped_(_Z13handleWrappedP11wl_listenerPv+0x3f) [0x59384f]
                handleWrapped(wl_listener*, void*)
                ??:?
        #11 | /nix/store/blw10rx1cayp2n2pkmyihpipifzgj2xq-wayland-1.22.0/lib/libwayland-server.so.0(wl_signal_emit_mutable+0x7c) [0x7fd61cfc9a0c]
                ??
                ??:0
        #12 | /nix/store/h147jd0fh2qyg2k24cxf6z5av7jx9y9y-wlroots-hyprland-2024-02-21_0cb091f/lib/libwlroots.so.13(+0x8533d) [0x7fd61cf2233d]
                ??
                ??:0
        #13 | /nix/store/f8ipgi6l1n1c0wr1r5aj40phnd6fkmv8-libffi-3.4.6/lib/libffi.so.8(+0xa052) [0x7fd61c6ff052]
                ??
                ??:0
```

I also tried running with damage tracking disabled for a while and could still reproduce.

**Comment by andresilva** [comment]
Haven't replicated so far on latest, will close and reopen if necessary.
