### ISSUE TITLE
Intermittent seg fault in libgcc_s.so.1 when using Hyprland

### ISSUE THREAD

**Issue by mrvruj** [hyprwm/Hyprland#5579]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh

Hyprland, built from branch v0.38.1-b at commit 360ede79d124ffdeebbe8401f1ac4bc0dbec2c91  (props: bump ver to 0.38.1).
Date: Sat Apr 6 14:24:13 2024
Tag: v0.38.1

flags: (if any)


System Information:
System name: Linux
Node name: boron
Release: 6.8.5-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Thu, 11 Apr 2024 01:47:33 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Alder Lake-P GT2 [Iris Xe Graphics] [8086:46a6] (rev 0c) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

Hyprland crashes inconsistently, I haven't found an obvious reproducible cause. The following segfault error is triggered in `libgcc_s.so.1`, leading to a system log out due to the crash. This issue has occurred about 10 times over the past couple of days, since I updated to 0.38.1-1.

### How to reproduce

The exact steps to reproduce the error are not currently known as the crashes appear to be intermittent. However, crashes have been noted under the following conditions:

1. During or shortly after heavy usage of graphical applications (e.g., GIMP, Firefox).
2. When changing window configurations rapidly.
3. Occasionally upon session start-up.

Attempts to consistently replicate the crash under controlled conditions have so far been unsuccessful.

### Crash reports, logs, images, videos

Journal here:
[hyprland_journalctl.txt](https://github.com/hyprwm/Hyprland/files/14969326/hyprland_journalctl.txt)

Did not find any relevant crash logs in ~/.cache/hyprland

**Comment by vaxerski** [comment]
does `coredumpctl` show a hyprland crash?

**Comment by Zander671** [comment]
I have been experiencing the same issue. While there are no hyprland crash logs, `coredumpctl` does have  a core dump. It says that hyprland got signal 11 in `wl_event_loop_dispatch` and then proceded to call `abort()` from a signal handler.
Here is the stack trace:
```
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007ec897cab393 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007ec897c5a6c8 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ec897c424b8 in __GI_abort () at abort.c:79
#4  0x00005911edd460e2 in handleUnrecoverableSignal (sig=11) at /usr/src/debug/hyprland/Hyprland-0.39.1/src/Compositor.cpp:38
#5  0x00007ec897c5a770 in <signal handler called> () at /usr/lib/libc.so.6
#6  0x00007ec89869bae0 in wl_event_loop_dispatch (loop=0x5911ef787130, timeout=timeout@entry=-1) at ../wayland-1.22.0/src/event-loop.c:1027
#7  0x00007ec89869c2d7 in wl_display_run (display=0x5911ef787040) at ../wayland-1.22.0/src/wayland-server.c:1493
#8  0x00005911edd47fe3 in CEventLoopManager::enterLoop (wlEventLoop=<optimized out>, display=<optimized out>, this=<optimized out>)
    at /usr/src/debug/hyprland/Hyprland-0.39.1/src/managers/eventLoop/EventLoopManager.cpp:27
#9  CCompositor::startCompositor (this=<optimized out>) at /usr/src/debug/hyprland/Hyprland-0.39.1/src/Compositor.cpp:633
#10 0x00005911edd2a892 in main (argc=<optimized out>, argv=<optimized out>) at /usr/include/c++/13.2.1/bits/unique_ptr.h:199
```

All other threads are waiting on `pthread_cond_wait`

**Comment by vaxerski** [comment]
odd, can you get an ASan trace? https://wiki.hyprland.org/Crashes-and-Bugs/#building-the-wayland-stack-with-asan

**Comment by vaxerski** [comment]
Hello there!

This issue has been closed, as we are moving from issues to discussions. More about this can be found [here](https://wiki.hyprland.org/Contributing-and-Debugging/Issue-Guidelines/) and in #9854.

Firstly, please make sure this issue is still relevant in latest Hyprland. If so, we ask you to open a [discussion](https://github.com/hyprwm/Hyprland/discussions) (please read the discussion guidelines first, in the pinned post)

Thank you for your understanding!
