### ISSUE TITLE
Crashing when rotating display

### ISSUE THREAD

**Issue by System64fumo** [hyprwm/Hyprland#6217]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit df80fbf70650dfb0d96381a1d86d30811cf516f4  (tablet: fix mapping when mapped region is specified (6206)).
Date: Thu May 23 14:52:32 2024
Tag: , commits: 1

flags: (if any)


System Information:
System name: Linux
Node name: icicle
Release: 6.9.0-rc4-baka+
Version: #1 SMP PREEMPT Thu Apr 18 09:30:50 IDT 2024


GPU information: 
qcom,adreno-630.2

os-release: NAME="Artix Linux"
PRETTY_NAME="Artix Linux"
ID=artix
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.artixlinux.org/"
DOCUMENTATION_URL="https://wiki.artixlinux.org/"
SUPPORT_URL="https://forum.artixlinux.org/"
BUG_REPORT_URL="https://bugs.artixlinux.org/"
PRIVACY_POLICY_URL="https://terms.artixlinux.org/docs/privacy-policy/"
LOGO=artixlinux-logo


plugins:
  hyprgrass by horriblename ver 0.6
```

</details>

### Bug or Regression?

Bug

### Description

Attempting to rotate my display (DSI-1) with the command:
`hyprctl keyword monitor DSI-1, 0x0, prefered,auto, transform, 1`
Causes hyprland to crash

### How to reproduce

1: Launch hyprland with your default display settings
2: Run `hyprctl keyword monitor DSI-1, 0x0, prefered,auto, transform, 1` (Change DSI-1 to match your display)
3: Crash

### Crash reports, logs, images, videos

Crash log:
[hyprland.log](https://github.com/hyprwm/Hyprland/files/15421489/hyprland.log)

**Comment by System64fumo** [comment]
Doesn't seem to output a crash report in ~/.cache/hyprland ?
And i don't know how to debug stacktrace

**Comment by hdm9527** [comment]
> Doesn't seem to output a crash report in ~/.cache/hyprland ? And i don't know how to debug stacktrace

https://wiki.hyprland.org/Crashes-and-Bugs/#obtaining-a-debug-stacktrace

**Comment by gulafaran** [comment]
tried it here.

backtrace
```
0  std::unreachable () at /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/utility:223
#1  CCompositor::arrangeMonitors (this=0x555555f9aec0) at ../hyprland-9999/src/Compositor.cpp:2665
#2  0x0000555555df70f8 in CHyprRenderer::applyMonitorRule
    (this=0x5555569462a0, pMonitor=0x5555571c5cc0, pMonitorRule=0x7fffffffbfa0, force=false)
    at ../hyprland-9999/src/render/Renderer.cpp:2223
#3  0x0000555555a44463 in CConfigManager::performMonitorReload (this=0x555555fa8220) at ../hyprland-9999/src/config/ConfigManager.cpp:1275
#4  0x0000555555dee016 in CHyprRenderer::renderMonitor (this=0x5555569462a0, pMonitor=0x5555571c5cc0)
    at ../hyprland-9999/src/render/Renderer.cpp:1174
#5  0x0000555555afd304 in Events::listener_monitorFrame (owner=0x5555571c5cc0, data=0x5555571d8350)
    at ../hyprland-9999/src/events/Monitors.cpp:170
#6  0x0000555555ab876b in std::__invoke_impl<void, void (*&)(void*, void*), void*, void*>
    (__f=@0x5555571c61f8: 0x555555afcc69 <Events::listener_monitorFrame(void*, void*)>)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/bits/invoke.h:61
#7  0x0000555555ab8142 in std::__invoke_r<void, void (*&)(void*, void*), void*, void*>
    (__fn=@0x5555571c61f8: 0x555555afcc69 <Events::listener_monitorFrame(void*, void*)>)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/bits/invoke.h:111
#8  0x0000555555ab78fc in std::_Function_handler<void (void*, void*), void (*)(void*, void*)>::_M_invoke(std::_Any_data const&, void*&&, void*&&) (__functor=..., __args#0=@0x7fffffffcb70: 0x5555571c5cc0, __args#1=@0x7fffffffcb68: 0x5555571d8350)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/bits/std_function.h:290
#9  0x0000555555b312c7 in std::function<void (void*, void*)>::operator()(void*, void*) const
    (this=0x5555571c61f8, __args#0=0x5555571c5cc0, __args#1=0x5555571d8350)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/bits/std_function.h:591
#10 0x0000555555b30b19 in CHyprWLListener::emit (this=0x5555571c61d0, data=0x5555571d8350) at ../hyprland-9999/src/helpers/WLListener.cpp:61
#11 0x0000555555b30882 in handleWrapped (listener=0x5555571c61d0, data=0x5555571d8350) at ../hyprland-9999/src/helpers/WLListener.cpp:14
#12 0x00007ffff7f88c93 in wl_signal_emit_mutable () at /usr/lib64/libwayland-server.so.0
#13 0x0000555555e4923d in wlr_output_send_frame (output=0x5555571d8350)
    at ../hyprland-9999/subprojects/wlroots-hyprland/types/output/output.c:753
#14 wlr_output_send_frame (output=0x5555571d8350) at ../hyprland-9999/subprojects/wlroots-hyprland/types/output/output.c:750
#15 handle_page_flip (fd=<optimized out>, seq=79036, tv_sec=729, tv_usec=<optimized out>, crtc_id=<optimized out>, data=<optimized out>)
    at ../hyprland-9999/subprojects/wlroots-hyprland/backend/drm/drm.c:2050
#16 0x00007ffff7f68da0 in drmHandleEvent () at /usr/lib64/libdrm.so.2
#17 0x0000555555e451a9 in handle_drm_event (fd=<optimized out>, mask=<optimized out>, data=0x555555fe36c0)
    at ../hyprland-9999/subprojects/wlroots-hyprland/backend/drm/drm.c:2062
#18 0x00007ffff7f8cd12 in wl_event_loop_dispatch () at /usr/lib64/libwayland-server.so.0
#19 0x00007ffff7f8d1fe in wl_display_run () at /usr/lib64/libwayland-server.so.0
#20 0x0000555555be6022 in CEventLoopManager::enterLoop (this=0x555555fa4bf0, display=0x555555fa7040, wlEventLoop=0x555555fa7130)
    at ../hyprland-9999/src/managers/eventLoop/EventLoopManager.cpp:27
#21 0x00005555559b23fc in CCompositor::startCompositor (this=0x555555f9aec0) at ../hyprland-9999/src/Compositor.cpp:575
#22 0x0000555555b60a4c in main (argc=1, argv=0x7fffffffdbd8) at ../hyprland-9999/src/main.cpp:116
```

**Comment by gulafaran** [comment]
> try now

unless @System64fumo has any objections, it works for me here with [6d67b84](https://github.com/hyprwm/Hyprland/commit/6d67b84469d5c12c5bbc4880f327ca8eb7a2ed2d)

**Comment by System64fumo** [comment]
Can confirm, works great now :+1: 
Good work
