### ISSUE TITLE
BLACK SCREEN ON LEGACY RENDER

### ISSUE THREAD

**Issue by palontologist** [hyprwm/Hyprland#6227]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details> 0.40
➜  Hyprland git:(main) Hyprland                   
Welcome to Hyprland!
[LOG] Instance Signature: 4e42107d25dc47ee94da282db233f85f1e4c6bd0_1716561960_581775091
[LOG] Runtime directory: /run/user/1000/hypr/4e42107d25dc47ee94da282db233f85f1e4c6bd0_1716561960_581775091
[LOG] Hyprland PID: 18326
[LOG] ===== SYSTEM INFO: =====
[LOG] System name: Linux
[LOG] Node name: archlinux
[LOG] Release: 6.9.1-arch1-2
[LOG] Version: #1 SMP PREEMPT_DYNAMIC Wed, 22 May 2024 13:47:07 +0000

[LOG] GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation Core Processor Integrated Graphics Controller [8086:0046] (rev 02) (prog-if 00 [VGA controller])

[LOG] os-release:
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

[LOG] ========================

[INFO] If you are crashing, or encounter any bugs, please consult https://wiki.hyprland.org/Crashes-and-Bugs/

[LOG] 
Current splash: Save your mercy for someone who needs it more

[LOG] Creating the EventLoopManager!
[LOG] Creating the HookSystem!
[LOG] Creating the ProtocolManager!
[LOG] [WLSeat] Registered global
[LOG] [WLDataDevice] Registered global
[LOG] [TearingControl] Registered global
[LOG] [FractionalScale] Registered global
[LOG] [XDGOutput] Registered global
[LOG] [CursorShape] Registered global
[LOG] [IdleInhibit] Registered global
[LOG] [RelativePointer] Registered global
[LOG] [XDGDecoration] Registered global
[LOG] [AlphaModifier] Registered global
[LOG] [GammaControl] Registered global
[LOG] [ForeignToplevel] Registered global
[LOG] [PointerGestures] Registered global
[LOG] [ForeignToplevelWlr] Registered global
[LOG] [ShortcutsInhibit] Registered global
[LOG] [TextInputV3] Registered global
[LOG] [PointerConstraints] Registered global
[LOG] [OutputPower] Registered global
[LOG] [XDGActivation] Registered global
[LOG] [IdleNotify] Registered global
[LOG] [SessionLock] Registered global
[LOG] [IMEv2] Registered global
[LOG] [VirtualKeyboard] Registered global
[LOG] [VirtualPointer] Registered global
[LOG] [OutputManagement] Registered global
[LOG] [ServerDecorationKDE] Registered global
[LOG] [FocusGrab] Registered global
[LOG] [TabletV2] Registered global
[LOG] [LayerShell] Registered global
[LOG] [Presentation] Registered global
[LOG] [XDGShell] Registered global
[LOG] [DataDeviceWlr] Registered global
[LOG] [PrimarySelection] Registered global
[LOG] ToplevelExportManager started successfully!
[LOG] TextInputV1Manager started successfully!
[LOG] GlobalShortcutsManager started successfully!
[LOG] ScreencopyProtocolManager started successfully!
[LOG] Creating the SeatManager!
[LOG] Creating the KeybindManager!
[LOG] Creating the AnimationManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 63.57µs. Estimated average calc time: 0.00µs.
[LOG] Creating the ConfigManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 32.21µs. Estimated average calc time: 0.00µs.
[LOG] Using config: /home/givenchy/.config/hypr/hyprland.conf
[INFO] !!!!HEY YOU, YES YOU!!!!: further logs to stdout / logfile are disabled by default. BEFORE SENDING THIS LOG, ENABLE THEM. Use debug:disable_logs = false to do so: https://wiki.hyprland.org/Configuring/Variables/#debug
[LOG] Creating the CHyprError!
[LOG] Creating the LayoutManager!
[LOG] Creating the TokenManager!
[LOG] [hookSystem] New hook event registered: preConfigReload
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 40.34µs. Estimated average calc time: 0.00µs.
[LOG] Using config: /home/givenchy/.config/hypr/hyprland.conf
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 32.37µs. Estimated average calc time: 0.00µs.
/bin/sh: line 1: hyprpaper: command not found
[2024-05-24 14:46:00.921] [info] Using configuration file /home/givenchy/.config/waybar/config
[2024-05-24 14:46:00.925] [info] Discovered appearance 'light'
[2024-05-24 14:46:00.925] [info] Using CSS file /home/givenchy/.config/waybar/style.css
basic_string::_M_create
[2024-05-24 14:46:00.940] [info] Hyprland IPC starting
[2024-05-24 14:46:00.944] [info] Loading persistent workspaces from Hyprland workspace rules
[2024-05-24 14:46:00.957] [warning] Can't open /dev/input/event0 (are you in the input group?): EACCES Permission denied
[2024-05-24 14:46:00.957] [warning] Can't open /dev/input/event1 (are you in the input group?): EACCES Permission denied
[2024-05-24 14:46:00.957] [warning] Can't open /dev/input/event2 (are you in the input group?): EACCES Permission denied
[2024-05-24 14:46:00.957] [warning] Can't open /dev/input/event3 (are you in the input group?): EACCES Permission denied
[2024-05-24 14:46:00.957] [warning] Can't open /dev/input/event4 (are you in the input group?): EACCES Permission denied
[2024-05-24 14:46:00.957] [warning] Can't open /dev/input/event5 (are you in the input group?): EACCES Permission denied
[2024-05-24 14:46:00.962] [warning] Can't create libevdev device: EINVAL Invalid argument
[2024-05-24 14:46:00.962] [warning] Can't open /dev/input/event6 (are you in the input group?): EACCES Permission denied
[2024-05-24 14:46:00.962] [warning] Can't open /dev/input/event7 (are you in the input group?): EACCES Permission denied
[2024-05-24 14:46:00.962] [warning] Can't open /dev/input/mice (are you in the input group?): EACCES Permission denied
[2024-05-24 14:46:00.962] [warning] Can't open /dev/input/mouse0 (are you in the input group?): EACCES Permission denied
[2024-05-24 14:46:00.962] [warning] Can't open /dev/input/event8 (are you in the input group?): EACCES Permission denied
[2024-05-24 14:46:00.962] [warning] Can't open /dev/input/event9 (are you in the input group?): EACCES Permission denied
[2024-05-24 14:46:00.962] [warning] Can't open /dev/input/event10 (are you in the input group?): EACCES Permission denied
[2024-05-24 14:46:00.962] [warning] Can't open /dev/input/event11 (are you in the input group?): EACCES Permission denied
[2024-05-24 14:46:00.962] [warning] Can't open /dev/input/event12 (are you in the input group?): EACCES Permission denied
[2024-05-24 14:46:00.962] [warning] Can't open /dev/input/event13 (are you in the input group?): EACCES Permission denied
[2024-05-24 14:46:00.962] [warning] Can't open /dev/input/event14 (are you in the input group?): EACCES Permission denied
[2024-05-24 14:46:00.962] [warning] module keyboard-state: Disabling module "keyboard-state", Failed to find keyboard device: EACCES Permission denied
[2024-05-24 14:46:00.972] [warning] module sway/language: Disabling module "sway/language", Socket path is empty
[2024-05-24 14:46:00.972] [warning] No battery named BAT2
[2024-05-24 14:46:01.135] [info] Bar configured (width: 1280, height: 30) for output: WL-1
[2024-05-24 14:46:01.166] [error] Item 'blueman': Could not find an icon named 'blueman-tray' and no pixmap given.

### Bug or Regression?

Bug

### Description

After first install tested with terminal and it worked but after reboot went to black screen 

### How to reproduce

fresh install of arch and legacyrender my specs are hp 8440p core i5 resolution 1366x768

### Crash reports, logs, images, videos

➜  Hyprland git:(main) Hyprland                   
Welcome to Hyprland!
[LOG] Instance Signature: 4e42107d25dc47ee94da282db233f85f1e4c6bd0_1716561960_581775091
[LOG] Runtime directory: /run/user/1000/hypr/4e42107d25dc47ee94da282db233f85f1e4c6bd0_1716561960_581775091
[LOG] Hyprland PID: 18326
[LOG] ===== SYSTEM INFO: =====
[LOG] System name: Linux
[LOG] Node name: archlinux
[LOG] Release: 6.9.1-arch1-2
[LOG] Version: #1 SMP PREEMPT_DYNAMIC Wed, 22 May 2024 13:47:07 +0000

[LOG] GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation Core Processor Integrated Graphics Controller [8086:0046] (rev 02) (prog-if 00 [VGA controller])

[LOG] os-release:
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

[LOG] ========================

[INFO] If you are crashing, or encounter any bugs, please consult https://wiki.hyprland.org/Crashes-and-Bugs/

[LOG] 
Current splash: Save your mercy for someone who needs it more

[LOG] Creating the EventLoopManager!
[LOG] Creating the HookSystem!
[LOG] Creating the ProtocolManager!
[LOG] [WLSeat] Registered global
[LOG] [WLDataDevice] Registered global
[LOG] [TearingControl] Registered global
[LOG] [FractionalScale] Registered global
[LOG] [XDGOutput] Registered global
[LOG] [CursorShape] Registered global
[LOG] [IdleInhibit] Registered global
[LOG] [RelativePointer] Registered global
[LOG] [XDGDecoration] Registered global
[LOG] [AlphaModifier] Registered global
[LOG] [GammaControl] Registered global
[LOG] [ForeignToplevel] Registered global
[LOG] [PointerGestures] Registered global
[LOG] [ForeignToplevelWlr] Registered global
[LOG] [ShortcutsInhibit] Registered global
[LOG] [TextInputV3] Registered global
[LOG] [PointerConstraints] Registered global
[LOG] [OutputPower] Registered global
[LOG] [XDGActivation] Registered global
[LOG] [IdleNotify] Registered global
[LOG] [SessionLock] Registered global
[LOG] [IMEv2] Registered global
[LOG] [VirtualKeyboard] Registered global
[LOG] [VirtualPointer] Registered global
[LOG] [OutputManagement] Registered global
[LOG] [ServerDecorationKDE] Registered global
[LOG] [FocusGrab] Registered global
[LOG] [TabletV2] Registered global
[LOG] [LayerShell] Registered global
[LOG] [Presentation] Registered global
[LOG] [XDGShell] Registered global
[LOG] [DataDeviceWlr] Registered global
[LOG] [PrimarySelection] Registered global
[LOG] ToplevelExportManager started successfully!
[LOG] TextInputV1Manager started successfully!
[LOG] GlobalShortcutsManager started successfully!
[LOG] ScreencopyProtocolManager started successfully!
[LOG] Creating the SeatManager!
[LOG] Creating the KeybindManager!
[LOG] Creating the AnimationManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 63.57µs. Estimated average calc time: 0.00µs.
[LOG] Creating the ConfigManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 32.21µs. Estimated average calc time: 0.00µs.
[LOG] Using config: /home/givenchy/.config/hypr/hyprland.conf
[INFO] !!!!HEY YOU, YES YOU!!!!: further logs to stdout / logfile are disabled by default. BEFORE SENDING THIS LOG, ENABLE THEM. Use debug:disable_logs = false to do so: https://wiki.hyprland.org/Configuring/Variables/#debug
[LOG] Creating the CHyprError!
[LOG] Creating the LayoutManager!
[LOG] Creating the TokenManager!
[LOG] [hookSystem] New hook event registered: preConfigReload
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 40.34µs. Estimated average calc time: 0.00µs.
[LOG] Using config: /home/givenchy/.config/hypr/hyprland.conf
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 32.37µs. Estimated average calc time: 0.00µs.
/bin/sh: line 1: hyprpaper: command not found
[2024-05-24 14:46:00.921] [info] Using configuration file /home/givenchy/.config/waybar/config
[2024-05-24 14:46:00.925] [info] Discovered appearance 'light'
[2024-05-24 14:46:00.925] [info] Using CSS file /home/givenchy/.config/waybar/style.css
basic_string::_M_create
[2024-05-24 14:46:00.940] [info] Hyprland IPC starting
[2024-05-24 14:46:00.944] [info] Loading persistent workspaces from Hyprland workspace rules
[2024-05-24 14:46:00.957] [warning] Can't open /dev/input/event0 (are you in the input group?): EACCES Permission denied
[2024-05-24 14:46:00.957] [warning] Can't open /dev/input/event1 (are you in the input group?): EACCES Permission denied
[2024-05-24 14:46:00.957] [warning] Can't open /dev/input/event2 (are you in the input group?): EACCES Permission denied
[2024-05-24 14:46:00.957] [warning] Can't open /dev/input/event3 (are you in the input group?): EACCES Permission denied
[2024-05-24 14:46:00.957] [warning] Can't open /dev/input/event4 (are you in the input group?): EACCES Permission denied
[2024-05-24 14:46:00.957] [warning] Can't open /dev/input/event5 (are you in the input group?): EACCES Permission denied
[2024-05-24 14:46:00.962] [warning] Can't create libevdev device: EINVAL Invalid argument
[2024-05-24 14:46:00.962] [warning] Can't open /dev/input/event6 (are you in the input group?): EACCES Permission denied
[2024-05-24 14:46:00.962] [warning] Can't open /dev/input/event7 (are you in the input group?): EACCES Permission denied
[2024-05-24 14:46:00.962] [warning] Can't open /dev/input/mice (are you in the input group?): EACCES Permission denied
[2024-05-24 14:46:00.962] [warning] Can't open /dev/input/mouse0 (are you in the input group?): EACCES Permission denied
[2024-05-24 14:46:00.962] [warning] Can't open /dev/input/event8 (are you in the input group?): EACCES Permission denied
[2024-05-24 14:46:00.962] [warning] Can't open /dev/input/event9 (are you in the input group?): EACCES Permission denied
[2024-05-24 14:46:00.962] [warning] Can't open /dev/input/event10 (are you in the input group?): EACCES Permission denied
[2024-05-24 14:46:00.962] [warning] Can't open /dev/input/event11 (are you in the input group?): EACCES Permission denied
[2024-05-24 14:46:00.962] [warning] Can't open /dev/input/event12 (are you in the input group?): EACCES Permission denied
[2024-05-24 14:46:00.962] [warning] Can't open /dev/input/event13 (are you in the input group?): EACCES Permission denied
[2024-05-24 14:46:00.962] [warning] Can't open /dev/input/event14 (are you in the input group?): EACCES Permission denied
[2024-05-24 14:46:00.962] [warning] module keyboard-state: Disabling module "keyboard-state", Failed to find keyboard device: EACCES Permission denied
[2024-05-24 14:46:00.972] [warning] module sway/language: Disabling module "sway/language", Socket path is empty
[2024-05-24 14:46:00.972] [warning] No battery named BAT2
[2024-05-24 14:46:01.135] [info] Bar configured (width: 1280, height: 30) for output: WL-1
[2024-05-24 14:46:01.166] [error] Item 'blueman': Could not find an icon named 'blueman-tray' and no pixmap given.

**Comment by palontologist** [comment]
also getting the backend create error

**Comment by vaxerski** [comment]
> for output: WL-1

please launch hyprland from a tty

**Comment by palontologist** [comment]
@vaxerski still having an error even after using tty    main()
  File "/home/givenchy/.local/share/bin/notifications.py", line 47, in main
    history = get_dunst_history()
              ^^^^^^^^^^^^^^^^^^^
  File "/home/givenchy/.local/share/bin/notifications.py", line 10, in get_dunst_history
    history = json.loads(result.stdout.decode('utf-8'))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Dunst is not running.
Traceback (most recent call last):
  File "/home/givenchy/.local/share/bin/notifications.py", line 54, in <module>
    main()
  File "/home/givenchy/.local/share/bin/notifications.py", line 47, in main
    history = get_dunst_history()
              ^^^^^^^^^^^^^^^^^^^
  File "/home/givenchy/.local/share/bin/notifications.py", line 10, in get_dunst_history
    history = json.loads(result.stdout.decode('utf-8'))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Dunst is not running.
Traceback (most recent call last):
  File "/home/givenchy/.local/share/bin/notifications.py", line 54, in <module>
    main()
  File "/home/givenchy/.local/share/bin/notifications.py", line 47, in main
    history = get_dunst_history()

**Comment by palontologist** [comment]
Its flikering like its not stable the screen

**Comment by palontologist** [comment]
Had done an install and the first time it worked when I did legacy but now it does not work

**Comment by palontologist** [comment]
@vaxerski  having an issue with dunst and fullscreen detection

**Comment by palontologist** [comment]
unst is not running.
Traceback (most recent call last):
  File "/home/givenchy/.local/share/bin/notifications.py", line 54, in <module>
    main()
  File "/home/givenchy/.local/share/bin/notifications.py", line 47, in main
    history = get_dunst_history()
              ^^^^^^^^^^^^^^^^^^^
  File "/home/givenchy/.local/share/bin/notifications.py", line 10, in get_dunst_history
    history = json.loads(result.stdout.decode('utf-8'))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Dunst is not running.
Traceback (most recent call last):
  File "/home/givenchy/.local/share/bin/notifications.py", line 54, in <module>
    main()
  File "/home/givenchy/.local/share/bin/notifications.py", line 47, in main
    history = get_dunst_history()
              ^^^^^^^^^^^^^^^^^^^
  File "/home/givenchy/.local/share/bin/notifications.py", line 10, in get_dunst_history
    history = json.loads(result.stdout.decode('utf-8'))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Dunst is not running.
Traceback (most recent call last):
  File "/home/givenchy/.local/share/bin/notifications.py", line 54, in <module>
    main()
  File "/home/givenchy/.local/share/bin/notifications.py", line 47, in main
    history = get_dunst_history()
              ^^^^^^^^^^^^^^^^^^^

**Comment by palontologist** [comment]
SOmething weird just happened when I tried to log out of plasma wayland I saw hyprland in the background and when I switch still is blackscreen also when I try with X11 this is the error [LOG] Using config: /home/givenchy/.config/hypr/hyprland.conf
[INFO] !!!!HEY YOU, YES YOU!!!!: further logs to stdout / logfile are disabled by default. BEFORE SENDING THIS LOG, ENABLE THEM. Use debug:disable_logs = false to do >
[LOG] Creating the CHyprError!
[LOG] Creating the LayoutManager!
[LOG] Creating the TokenManager!
[LOG] [hookSystem] New hook event registered: preConfigReload
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 31.77µs. Estimated average calc time: 0.00µs.
[LOG] Using config: /home/givenchy/.config/hypr/hyprland.conf
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 28.96µs. Estimated average calc time: 0.00µs.
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 31.53µs. Estimated average calc time: 0.00µs.
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 31.40µs. Estimated average calc time: 0.00µs.
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 31.36µs. Estimated average calc time: 0.00µs.
[LOG] Disabling stdout logs! Check the log for further logs.
[LOG] Creating the PointerManager!
[backend/backend.c:224] Cannot create X11 backend: disabled at compile-time
[CRITICAL] m_sWLRBackend was NULL! This usually means wlroots could not find a GPU or enountered some issues.
[CRITICAL] Critical error thrown: wlr_backend_autocreate() failed!


^G Help         ^O Write Out    ^F Where Is     ^K Cut          ^T Execute

**Comment by vaxerski** [comment]
X11 sessions are not supported. The logs you are posting are not from hyprland. looking at basic_string::_M_create, this is possibly a bug that's been fixed in git?

**Comment by palontologist** [comment]
still does not work when I use tty

**Comment by romanstingler** [comment]
can you try with the latest again 
please build `yay -S hyprland-legacyrenderer-git  aquamarine-git` new and add `env = AQ_NO_MODIFIERS,1` to your `hyperland.conf`

**Comment by vaxerski** [comment]
Hello there!

This issue has been closed, as we are moving from issues to discussions. More about this can be found [here](https://wiki.hyprland.org/Contributing-and-Debugging/Issue-Guidelines/) and in #9854.

Firstly, please make sure this issue is still relevant in latest Hyprland. If so, we ask you to open a [discussion](https://github.com/hyprwm/Hyprland/discussions) (please read the discussion guidelines first, in the pinned post)

Thank you for your understanding!

**Comment by palontologist** [comment]
Cool @vaxerski
