### ISSUE TITLE
Assertion fail after suspend-resume

### ISSUE THREAD

**Issue by vlaci** [hyprwm/Hyprland#629]
Installed Hyprland on NixOS using the provided flake using revision 94ca386a8c298265fa5fb19ee2ec2be3db335502.

```
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007f05f12b2c33 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007f05f1265b46 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007f05f12504b5 in __GI_abort () at abort.c:79
#4  0x00007f05f12503d9 in __assert_fail_base (fmt=0x7f05f13e5308 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x7f05f1b50b34 "allocator != NULL", file=0x7f05f1b51420 "types/output/render.c", line=52, function=<optimized out>) at assert.c:92
#5  0x00007f05f125e7b6 in __GI___assert_fail (assertion=0x7f05f1b50b34 "allocator != NULL", file=0x7f05f1b51420 "types/output/render.c", line=52, function=0x7f05f1b51920 <__PRETTY_FUNCTION__.6> "output_create_swapchain") at assert.c:101
#6  0x00007f05f1b0860f in output_create_swapchain () from /nix/store/jc10mp7rk2w0vdypls8cc6s3cvlr5dqg-wlroots-hyprland-hidpi-2022-08-30_fd0b027/lib/libwlroots.so.11
#7  0x00007f05f1b08636 in output_attach_back_buffer () from /nix/store/jc10mp7rk2w0vdypls8cc6s3cvlr5dqg-wlroots-hyprland-hidpi-2022-08-30_fd0b027/lib/libwlroots.so.11
#8  0x00007f05f1b08709 in wlr_output_attach_render () from /nix/store/jc10mp7rk2w0vdypls8cc6s3cvlr5dqg-wlroots-hyprland-hidpi-2022-08-30_fd0b027/lib/libwlroots.so.11
#9  0x00000000004f5f13 in CHyprOpenGLImpl::makeLayerSnapshot(SLayerSurface*) ()
#10 0x00000000004eb48b in Events::listener_unmapLayerSurface(void*, void*) ()
#11 0x00000000004b2c5b in CHyprWLListener::emit(void*) ()
#12 0x00007f05f1b9490c in wl_signal_emit_mutable () from /nix/store/rq2d1gp2hhh4l584112vrkrbijpw7xhm-wayland-1.21.0/lib/libwayland-server.so.0
#13 0x00007f05f1b244c4 in layer_surface_unmap () from /nix/store/jc10mp7rk2w0vdypls8cc6s3cvlr5dqg-wlroots-hyprland-hidpi-2022-08-30_fd0b027/lib/libwlroots.so.11
#14 0x00007f05f1b245a5 in layer_surface_destroy () from /nix/store/jc10mp7rk2w0vdypls8cc6s3cvlr5dqg-wlroots-hyprland-hidpi-2022-08-30_fd0b027/lib/libwlroots.so.11
#15 0x00007f05f1b92ee7 in destroy_resource () from /nix/store/rq2d1gp2hhh4l584112vrkrbijpw7xhm-wayland-1.21.0/lib/libwayland-server.so.0
#16 0x00007f05f1b935f0 in wl_resource_destroy () from /nix/store/rq2d1gp2hhh4l584112vrkrbijpw7xhm-wayland-1.21.0/lib/libwayland-server.so.0
#17 0x00007f05f122280a in ffi_call_unix64 () from /nix/store/4d4zzb9a4fazq0qv7vvls561l9cxi0zc-libffi-3.4.2/lib/libffi.so.8
#18 0x00007f05f1221943 in ffi_call_int () from /nix/store/4d4zzb9a4fazq0qv7vvls561l9cxi0zc-libffi-3.4.2/lib/libffi.so.8
#19 0x00007f05f1b98961 in wl_closure_invoke () from /nix/store/rq2d1gp2hhh4l584112vrkrbijpw7xhm-wayland-1.21.0/lib/libwayland-server.so.0
#20 0x00007f05f1b93bda in wl_client_connection_data () from /nix/store/rq2d1gp2hhh4l584112vrkrbijpw7xhm-wayland-1.21.0/lib/libwayland-server.so.0
#21 0x00007f05f1b9688a in wl_event_loop_dispatch () from /nix/store/rq2d1gp2hhh4l584112vrkrbijpw7xhm-wayland-1.21.0/lib/libwayland-server.so.0
#22 0x00007f05f1b94365 in wl_display_run () from /nix/store/rq2d1gp2hhh4l584112vrkrbijpw7xhm-wayland-1.21.0/lib/libwayland-server.so.0
#23 0x0000000000439654 in main ()
```
[core.Hyprland.1000.a48c473b58e9452d944d2c8d1b0c792e.72995.1662408963000000.zip](https://github.com/hyprwm/Hyprland/files/9491902/core.Hyprland.1000.a48c473b58e9452d944d2c8d1b0c792e.72995.1662408963000000.zip)

Looks like there was a symilar issue in wlroots concerning Wayfire: https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3326

**Comment by vaxerski** [comment]
log please

**Comment by vlaci** [comment]
[log.zip](https://github.com/hyprwm/Hyprland/files/9491913/log.zip)

**Comment by vaxerski** [comment]
mashallah. 

Well the logs warned you:
```
[WARN] Unplugged last monitor, entering an unsafe state. Good luck my friend.
```

You have yet another one of those shitty-ass laptops that physically disconnect the display on lid close. Cringe.

Check with 16f1d1b99b9ac4ae89fc04d00fcd16cd4e3cd302

**Comment by vlaci** [comment]
This is a desktop machine, but your comment got me thinking: this is due to my KVM disconnecting. When monitor is plugged in directly, there is no issue.

**Comment by vlaci** [comment]
I mean a KVM switch, more specifically [this one](https://store.level1techs.com/products/14-display-port-kvm-dual-4computer).

But what is more important, that after the patch, resume works!

Thank you for the quick turnaround and this awesome window manager!

**Comment by vaxerski** [comment]
ok dunno what the hell happened but yeah sure you're welcome
