### ISSUE TITLE
Cannot start `kitty@0.34.1` after updating to `0.42.0`

### ISSUE THREAD

**Issue by ndom91** [hyprwm/Hyprland#7235]
### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 83a334f97df4389ca30cb63e50317a66a82562b9  ().
Date: 2024-08-08
Tag: , commits: 83a334f97df4389ca30cb63e50317a66a82562b9

flags: (if any)


System Information:
System name: Linux
Node name: ndo-gb
Release: 6.10.3
Version: #1-NixOS SMP PREEMPT_DYNAMIC Sat Aug  3 07:01:09 UTC 2024


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Meteor Lake-P [Intel Graphics] [8086:7d45] (rev 08) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240805.883180e"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_END="2024-12-31"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:

======Config-Start======


Config File: /home/ndo/.config/hypr/hyprland.conf: Read Succeeded
exec-once = /nix/store/8piinp0n24cl145qndjdfzja8x9s5x0k-dbus-1.14.10/bin/dbus-update-activation-environment --systemd --all && systemctl --user stop hyprland-session.target && systemctl --user start hyprland-session.target
$mainMod=SUPER
animations {
  bezier=myBezier, 0.05, 0.9, 0.1, 1.05
  bezier=linear, 0.0, 0.0, 1.0, 1.0
  bezier=wind, 0.05, 0.9, 0.1, 1.05
  bezier=winIn, 0.1, 1.1, 0.1, 1.1
  bezier=winOut, 0.3, -0.3, 0, 1
  bezier=slow, 0, 0.85, 0.3, 1
  bezier=overshot, 0.7, 0.6, 0.1, 1.1
  bezier=bounce, 1.1, 1.6, 0.1, 0.85
  bezier=sligshot, 1, -1, 0.15, 1.25
  bezier=nice, 0, 6.9, 0.5, -4.20
  bezier=linear, 0, 0, 1, 1
  bezier=md3_standard, 0.2, 0, 0, 1
  bezier=md3_decel, 0.05, 0.7, 0.1, 1
  bezier=md3_accel, 0.3, 0, 0.8, 0.15
  bezier=overshot, 0.05, 0.9, 0.1, 1.1
  bezier=crazyshot, 0.1, 1.5, 0.76, 0.92 
  bezier=hyprnostretch, 0.05, 0.9, 0.1, 1.0
  bezier=menu_decel, 0.1, 1, 0, 1
  bezier=menu_accel, 0.38, 0.04, 1, 0.07
  bezier=easeInOutCirc, 0.85, 0, 0.15, 1
  bezier=easeOutCirc, 0, 0.55, 0.45, 1
  bezier=easeOutExpo, 0.16, 1, 0.3, 1
  bezier=softAcDecel, 0.26, 0.26, 0.15, 1
  animation=windowsIn, 1, 5, slow, popin
  animation=windowsOut, 1, 5, winOut, popin
  animation=windowsMove, 1, 5, wind, slide
  animation=border, 1, 10, linear
  animation=fade, 1, 5, overshot
  animation=workspaces, 1, 5, wind
  animation=windows, 1, 5, bounce, popin
  animation=windows, 1, 3, md3_decel, popin 60%
  animation=windowsIn, 1, 3, md3_decel, popin 60%
  animation=windowsOut, 1, 3, md3_accel, popin 60%
  animation=border, 1, 10, default
  animation=fade, 1, 3, md3_decel
  animation=layers, 1, 2, md3_decel, slide
  animation=layersIn, 1, 3, menu_decel, slide
  animation=layersOut, 1, 1.6, menu_accel
  animation=fadeLayersIn, 1, 2, menu_decel
  animation=fadeLayersOut, 1, 4.5, menu_accel
  animation=workspaces, 1, 7, menu_decel, slide
  enabled=yes
}

debug {
  disable_logs=true
}

decoration {
  blur {
    enabled=true
    ignore_opacity=true
    new_optimizations=true
    passes=2
    popups=true
    size=8
    xray=true
  }
  active_opacity=0.94
  dim_inactive=true
  dim_strength=0.075
  drop_shadow=false
  fullscreen_opacity=1.0
  inactive_opacity=0.85
  rounding=4
}

general {
  border_size=6
  col.active_border=rgb(11111b) rgb(181825) 45deg
  col.inactive_border=rgba(f5e0dc20)
  gaps_in=10
  gaps_out=20
  layout=master
  no_focus_fallback=true
  resize_on_border=true
}

gestures {
  workspace_swipe=true
  workspace_swipe_create_new=false
  workspace_swipe_distance=200
  workspace_swipe_fingers=3
}

group {
  groupbar {
    col.active=rgb(181825)
    col.inactive=rgba(f5e0dc20)
    font_family=Fira Sans Light
    font_size=9
    height=24
    render_titles=true
  }
  col.border_active=rgb(181825)
  col.border_inactive=rgba(f5e0dc20)
}

input {
  touchpad {
    clickfinger_behavior=true
  }
  accel_profile=adaptive
  follow_mouse=2
  kb_layout=us
  kb_options=caps:escape
}

misc {
  allow_session_lock_restore=true
  animate_manual_resizes=true
  disable_hyprland_logo=true
  focus_on_activate=true
  key_press_enables_dpms=true
  mouse_move_enables_dpms=true
}

xwayland {
  force_zero_scaling=true
}
bind=$mainMod, G, togglegroup,
bind=$mainMod, U, changegroupactive,b
bind=$mainMod, I, changegroupactive,f
bind=$mainMod, Q, killactive
bind=CTRL SHIFT, L, exec, hyprlock
bind=$mainMod, Return, exec, kitty
bind=$mainMod SHIFT, R, exec, hyprctl reload
bind=$mainMod SHIFT, F, exec, nemo
bind=$mainMod SHIFT, Q, exec, wlogout -b 5 -c 0 -r 0 -m 0 --protocol layer-shell
bind=$mainMod SHIFT, Space, togglefloating,
bind=$mainMod, Space, cyclenext # hack to focus floating windows
bind=$mainMod, F, fullscreen, 1 # fullscreen type 1
bind=$mainMod, P, pseudo, # dwindle layout
bind=$mainMod, O, togglesplit, # dwindle layout
bind=$mainMod, D, exec, "$HOME/.config/rofi/bin/launcher"
bind=$mainMod, E, exec, "$HOME/.config/rofi/bin/emoji"
bind=$mainMod, C, exec, "$HOME/.config/rofi/bin/cliphist"
bind=$mainMod, S, exec, "$HOME/.config/rofi/bin/screenshot"
bind=$mainMod SHIFT, S, exec, pkill --signal SIGINT wf-recorder && notify-send "Stopped Recording" || wf-recorder -g "$(slurp)" -f ~/Videos/wfrecording_$(date +"%Y-%m-%d_%H:%M:%S.mp4") & notify-send "Started Recording" # start/stop video recording
bind=CTRL, Space, exec, swaync-client -t -sw
bind=CTRL SHIFT, Space, exec, swaync-client -C -sw
bind=$mainMod, H, movefocus, l
bind=$mainMod, L, movefocus, r
bind=$mainMod, K, movefocus, u
bind=$mainMod, J, movefocus, d
bind=$mainMod SHIFT, H, movewindoworgroup, l
bind=$mainMod SHIFT, L, movewindoworgroup, r
bind=$mainMod SHIFT, K, movewindoworgroup, u
bind=$mainMod SHIFT, J, movewindoworgroup, d
bind=,XF86MonBrightnessUp, exec, brightnessctl set 5%+
bind=,XF86MonBrightnessDown, exec, brightnessctl set 5%-
bind=,XF86AudioPlay, exec, playerctl play-pause
bind=,XF86AudioNext, exec, playerctl next
bind=,XF86AudioPrev, exec, playerctl previous
bind=,XF86AudioStop, exec, playerctl stop
bind=,XF86AudioRaiseVolume, exec, swayosd-client --output-volume raise
bind=,XF86AudioLowerVolume, exec, swayosd-client --output-volume lower
bind=,XF86AudioMute, exec, swayosd-client --output-volume mute-toggle
bind=,XF86AudioMicMute, exec, swayosd-client --input-volume mute-toggle
bind=$mainMod, 1, workspace, 1
bind=$mainMod SHIFT, 1, movetoworkspacesilent, 1
bind=$mainMod, 2, workspace, 2
bind=$mainMod SHIFT, 2, movetoworkspacesilent, 2
bind=$mainMod, 3, workspace, 3
bind=$mainMod SHIFT, 3, movetoworkspacesilent, 3
bind=$mainMod, 4, workspace, 4
bind=$mainMod SHIFT, 4, movetoworkspacesilent, 4
bind=$mainMod, 5, workspace, 5
bind=$mainMod SHIFT, 5, movetoworkspacesilent, 5
bind=$mainMod, 6, workspace, 6
bind=$mainMod SHIFT, 6, movetoworkspacesilent, 6
bind=$mainMod, 7, workspace, 7
bind=$mainMod SHIFT, 7, movetoworkspacesilent, 7
bind=$mainMod, 8, workspace, 8
bind=$mainMod SHIFT, 8, movetoworkspacesilent, 8
bind=$mainMod, 9, workspace, 9
bind=$mainMod SHIFT, 9, movetoworkspacesilent, 9
bind=$mainMod, 0, workspace, 10
bind=$mainMod SHIFT, 0, movetoworkspacesilent, 10
bind=,XF86Launch2, exec, /home/ndo/.config/rofi/bin/screenshot
bindl=,switch:on:Lid Switch,exec,hyprctl keyword monitor 'eDP-1,disable'
bindl=,switch:off:Lid Switch,exec,hyprctl keyword monitor 'eDP-1,preferred,auto,1'
bindm=$mainMod, mouse:272, movewindow
bindm=$mainMod, mouse:273, resizewindow
bindn=CTRL SHIFT, Period, exec, /nix/store/jvw9an94li6i3skkf5w24xy6i6ipbmwg-1password-8.10.33/bin/1password --quick-access
env=HYPRCURSOR_THEME,rose-pine-hyprcursor
exec=/nix/store/9asca4nn6z0pb4wq6361zsv17jyqvpk1-swayosd-0-unstable-2024-04-15/bin/swayosd-server
exec-once=/nix/store/jvw9an94li6i3skkf5w24xy6i6ipbmwg-1password-8.10.33/bin/1password --silent
exec-once=/nix/store/4f2k3yq1k904cc7r19xl2pgfmxgbcjii-blueman-2.4.1/bin/blueman-applet
exec-once=/nix/store/czcl8ansch3ia53r9604vggcri153v3s-swaybg-1.2.1/bin/swaybg -m fill -i ~/.config/hypr/wallpaper.png
monitor=eDP-1,preferred,auto,1
monitor=DP-1,preferred,auto,1
windowrule=float, file_progress
windowrule=float, confirm
windowrule=float, dialog
windowrule=float, download
windowrule=float, notification
windowrule=float, error
windowrule=float, splash
windowrule=float, confirmreset
windowrulev2=animation fade, floating:1
windowrulev2=float, class:org.gnome.FileRoller
windowrulev2=float, title:wlogout
windowrulev2=fullscreen, title:wlogout
windowrulev2=workspace special silent, title:^(Firefox — Sharing Indicator)$
windowrulev2=workspace special silent, title:^.*(Sharing Indicator)$
windowrulev2=workspace special silent, title:^(.*is sharing (your screen|a window).)$
windowrulev2=float, class:org.gnome.Loupe
windowrulev2=float, class:^((g|G)it-(b|B)utler.*)$
windowrulev2=monitor DP-1, class:^((g|G)it-(b|B)utler.*)$
windowrulev2=stayfocused,title:^(Quick Access - 1Password)
windowrulev2=monitor DP-1,title:^(Quick Access - 1Password)
windowrulev2=monitor DP-1,class:^(1Password)$
windowrulev2=center, class:^(1Password)$
windowrulev2=float, class:^(1Password)$
windowrulev2=idleinhibit focus, class:^(vivaldi)$, title:^(.*YouTube.*)$
windowrulev2=idleinhibit fullscreen, class:^(vivaldi)$
windowrulev2=float, class:Beeper
windowrulev2=float, class:org.gnome.TextEditor
windowrulev2=float, class:nemo
windowrulev2=center, class:nemo
windowrulev2=float, class:pavucontrol
windowrulev2=center, class:pavucontrol
windowrulev2=float, class:^(.*blueberry.*)$
windowrulev2=center, class:^(.*blueberry.*)$
windowrulev2=float, class:^(.*blueman-.*)$
windowrulev2=center, class:^(.*blueman-.*)$
windowrulev2=float, class:nm-connection-editor
windowrulev2=center, class:nm-connection-editor
windowrulev2=float, class:^(opensnitch_ui)$
windowrulev2=float, title:^(DevTools.*)$
windowrulev2=float, title:^(DevTools.*)$
windowrulev2=float, title:^(Developer Tools.*)$
windowrulev2=float, title:^(Developer Tools.*)$
windowrulev2=float, title:^(Winetricks.*)$
windowrulev2=float, class:lutris
windowrulev2=float, class:beekeeper-studio
windowrulev2=dimaround, class:^(xdg-desktop-portal-gtk)$
windowrulev2=float, class:^(xdg-desktop-portal-gtk)$
windowrulev2=dimaround, class:^(polkit-gnome-authentication-agent-1)$
windowrulev2=float, class:^(polkit-gnome-authentication-agent-1)$
windowrulev2=dimaround, class:^(gcr-prompter)$
windowrulev2=float, class:^(gcr-prompter)$
windowrulev2=opacity 0.0 override 0.0 override,class:^(xwaylandvideobridge)$
windowrulev2=noanim,class:^(xwaylandvideobridge)$
windowrulev2=nofocus,class:^(xwaylandvideobridge)$
windowrulev2=noinitialfocus,class:^(xwaylandvideobridge)$
workspace=1,monitor:eDP-1,default:true
workspace=2,monitor:eDP-1
workspace=3,monitor:DP-1,default:true
# Resize
bind = $mainMod, R, submap, resize
submap = resize
binde = , H, resizeactive, 40 0
binde = , L, resizeactive, -40 0
binde = , K, resizeactive, 0 -40
binde = , J, resizeactive, 0 40
bind = , escape, submap, reset
submap = reset


======Config-End========


```

</details>

### Description

After updating to `0.42.0` (commit `83a334f97df4389ca30cb63e50317a66a82562b9` via nix), I am unable to start `kitty`.

Kitty output when started via the terminal:

```sh
[0.054] [glfw error 65542]: EGL: Failed to get EGL display: Success
[0.057] Traceback (most recent call last):
  File "/nix/store/2x0qa05yfmr8a0xgnz5bxk0m4syfk6mv-kitty-0.34.1/bin/../lib/kitty/kitty/main.py", line 562, in main
    _main()
  File "/nix/store/2x0qa05yfmr8a0xgnz5bxk0m4syfk6mv-kitty-0.34.1/bin/../lib/kitty/kitty/main.py", line 554, in _main
    run_app(opts, cli_opts, bad_lines)
  File "/nix/store/2x0qa05yfmr8a0xgnz5bxk0m4syfk6mv-kitty-0.34.1/bin/../lib/kitty/kitty/main.py", line 297, in __call__
    _run_app(opts, args, bad_lines)
  File "/nix/store/2x0qa05yfmr8a0xgnz5bxk0m4syfk6mv-kitty-0.34.1/bin/../lib/kitty/kitty/main.py", line 268, in _run_app
    window_id = create_os_window(
                ^^^^^^^^^^^^^^^^^
ValueError: Failed to create GLFWwindow
```

Seems potentially related to [the issue](https://github.com/kovidgoyal/kitty/issues/7516) vaxerski opened in Kitty but seemed to have been fixed [here](https://github.com/hyprwm/Hyprland/commit/9994b73ad0af5c9ba5fc4058234cea77d0a1ddb1) :thinking: 

### How to reproduce

Attempt to launch `kitty` via the terminal, observe the output above.

**Comment by vaxerski** [comment]
I had that once when kitty was compiled wrong. Anyways, this isn't a hyprland issue

**Comment by ndom91** [comment]
You're right, forcing nix to use the `unstable.kitty` (instead of the one from `nixpkgs@24.05`, for example) fixed it :partying_face: 

If anyone else comes across this and is using the home-manager kitty setup, you can pass it `package = unstable.kitty` to force it to use the unstable nixpkgs version, i.e. 

```nix
{ input, unstablePkgs, pkgs, ... }:
{
  programs.kitty = {
    enable = true;
    package = unstablePkgs.kitty;
    # Pick "name" from https://github.com/kovidgoyal/kitty-themes/blob/master/themes.json
    theme = "Rosé Pine";
  };
}
```
