### ISSUE TITLE
Segmentation fault at start up all the time on 0.42.0

### ISSUE THREAD

**Issue by iddm** [hyprwm/Hyprland#7291]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
hyprctl systeminfo -c
Hyprland, built from branch  at commit 918d8340afd652b011b937d29d5eea0be08467f5  (flake.lock: update).
Date: Tue Jun 25 14:06:02 2024
Tag: v0.41.2, commits: 4886

flags: (if any)


System Information:
System name: Linux
Node name: purplejam
Release: 6.10.3-arch1-2
Version: #1 SMP PREEMPT_DYNAMIC Tue, 06 Aug 2024 07:21:19 +0000


GPU information:
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD102 [GeForce RTX 4090] [10de:2684] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
  split-monitor-workspaces by Duckonaut ver 1.1.0

======Config-Start======


Config File: /home/fx/.config/hypr/hyprland.conf: Read Succeeded
env = QT_QPA_PLATFORM,wayland
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = WLR_NO_HARDWARE_CURSORS,1
# Disable GSYNC
env = __GL_GSYNC_ALLOWED,0
env = __GL_MaxFramesAllowed,0
# Enable tearing: disables the usage ot a newer kernel DRM API that doesn't support tearing yet.
env = WLR_DRM_NO_ATOMIC,1

plugin {
    split-monitor-workspaces {
        count = 5
    }
}

debug {
    enable_stdout_logs = true
    disable_logs = false
}

#
# Please note not all available settings / options are set here.
# For a full list, see the wiki

# See https://wiki.hyprland.org/Configuring/Monitors/
#monitor=,preferred,auto,auto
monitor=DP-3, 2560x1440@240, 0x0, 1, vrr, 0, bitdepth, 10
monitor=DP-2, preferred, auto, 1, vrr, 0, bitdepth, 10
monitor=HDMI-A-1, disable

# See https://wiki.hyprland.org/Configuring/Keywords/ for more

# Execute your favorite apps at launch
exec-once = waybar
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = dbus-update-activation-environment --all
exec-once = wl-paste --type text --watch cliphist store #Stores only text data
exec-once = wl-paste --type image --watch cliphist store #Stores only image data
exec-once=hyprctl plugin load /home/user/workspace/split-monitor-workspaces/build/libsplit-monitor-workspaces.so

# Source a file (multi-file configs)
# source = ~/.config/hypr/myColors.conf

# Some default env vars.
env = XCURSOR_SIZE,24

# For all categories, see https://wiki.hyprland.org/Configuring/Variables/
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options = grp:alt_shift_toggle
    kb_rules =

    follow_mouse = 1

    touchpad {
        natural_scroll = no
    }

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
    #accel_profile = "flat"
    force_no_accel = true
}

cursor {
    inactive_timeout = 2
}

general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    gaps_in = 5
    gaps_out = 20
    border_size = 2
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)

    layout = dwindle

    # Enable tearing
    allow_tearing = true
}

decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    rounding = 10

    blur {
        enabled = true
        size = 3
        passes = 1
    }

    drop_shadow = yes
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)
}

misc {
    disable_hyprland_logo = true
    background_color = 0x000000
}

animations {
    enabled = yes

    # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

dwindle {
    # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = yes # you probably want this
}

master {
    # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    #new_is_master = true
    new_status = master
}

gestures {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    workspace_swipe = off
}

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#executing for more
device {
    name = compx-pulsar-xlite-wireless
    sensitivity = 0
    accel_profile = flat
    #force_no_accel = true
}

# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

windowrulev2 = immediate, title:^(Freesync test)$
# Let steam NOT lose focus
windowrulev2 = stayfocused, title:^()$,class:^(steam)$
windowrulev2 = minsize 1 1, title:^()$,class:^(steam)$

# See https://wiki.hyprland.org/Configuring/Keywords/ for more
$mainMod = SUPER

# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = $mainMod, C, killactive,
bind = $mainMod SHIFT, M, exit,
bind = $mainMod, V, togglefloating,
bind = $mainMod, F, fullscreen,
bind = $mainMod, R, exec, wofi --show drun
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, J, togglesplit, # dwindle

# Move focus with mainMod + arrow keys
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, split-workspace, 1
bind = $mainMod, 2, split-workspace, 2
bind = $mainMod, 3, split-workspace, 3
bind = $mainMod, 4, split-workspace, 4
bind = $mainMod, 5, split-workspace, 5
bind = $mainMod, 6, split-workspace, 6
bind = $mainMod, 7, split-workspace, 7
bind = $mainMod, 8, split-workspace, 8
bind = $mainMod, 9, split-workspace, 9
bind = $mainMod, 0, split-workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, split-movetoworkspace, 1
bind = $mainMod SHIFT, 2, split-movetoworkspace, 2
bind = $mainMod SHIFT, 3, split-movetoworkspace, 3
bind = $mainMod SHIFT, 4, split-movetoworkspace, 4
bind = $mainMod SHIFT, 5, split-movetoworkspace, 5
bind = $mainMod SHIFT, 6, split-movetoworkspace, 6
bind = $mainMod SHIFT, 7, split-movetoworkspace, 7
bind = $mainMod SHIFT, 8, split-movetoworkspace, 8
bind = $mainMod SHIFT, 9, split-movetoworkspace, 9
bind = $mainMod SHIFT, 0, split-movetoworkspace, 10

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, split-workspace, e+1
bind = $mainMod, mouse_up, split-workspace, e-1

# FX binds
# Basic ALT-TAB functionality.
bind = $mainMod, tab, cyclenext
bind = $mainMod SHIFT, tab, cyclenext, prev
bind = $mainMod, return, exec, /home/user/downloads/browser/Warp-x86_64.AppImage
bind = $mainMod, L, exec, urlshortener-cli --get-from-clipboard --set-to-clipboard
bind = $mainMod, O, split-changemonitor, +1
bind = $mainMod, D, dpms, off DP-3
bind = $mainMod, S, dpms, off DP-2
bind = $mainMod SHIFT, D, dpms, on DP-3
bind = $mainMod SHIFT, S, dpms, on DP-2
bind = $mainMod SHIFT, D, exec, xrandr --output DP-2 --primary
bind = $mainMod SHIFT, S, exec, xrandr --output DP-2 --primary
bind = $mainMod SHIFT CTRL, return, exec, shutdown -h now
bind = $mainMod, Z, focusmonitor, +1
bind = CTRL ALT, Z, exec, cliphist list | wofi --dmenu | cliphist decode | wl-copy
# Screenshot the entire display area (all the monitors).
bind = CTRL SHIFT, 3, exec, grim /tmp/screenshot.png
# Screenshot a part of the screen (user selection).
bind = CTRL SHIFT, 4, exec, slurp | grim -g - /tmp/screenshot.png
# Screenshot for the current active window.
bind = CTRL SHIFT, 5, exec, hyprctl -j activewindow | jq -r '"\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"' | grim -g - /tmp/screenshot.png
# Toggle waybar
bindr = ALT, Alt_R, exec, killall -SIGUSR1 waybar


# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

======Config-End========
```

</details>

### Description

Whenever I start Hyprland built from version `0.42.0`, it crashes almost immediately.

### How to reproduce

1. Git clone `Hyprland` and all the relevant projects for it to run.
2. Checkout tag `v0.42.0`.
3. `make all`
4. Either `./build/Hyprland` or install the binaries where needed on the host and start it as a main session, there is no difference.

### Crash reports, logs, images, videos

The stack trace:
```
Thread 1 "Hyprland" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x0000555555dfc803 in Hyprutils::Memory::CSharedPointer<Aquamarine::CBackend>::get (this=0x555556c3fa38) at /usr/local/include/hyprutils/memory/SharedPtr.hpp:242
#2  0x0000555555de9f78 in Hyprutils::Memory::CSharedPointer<Aquamarine::CBackend>::operator-> (this=0x555556c3fa38) at /usr/local/include/hyprutils/memory/SharedPtr.hpp:229
#3  0x0000555555db5036 in CCompositor::initAllSignals (this=0x555556c3fa20) at /home/fx/workspace/Hyprland/src/Compositor.cpp:320
#4  0x0000555555db3c80 in CCompositor::initServer (this=0x555556c3fa20, socketName="", socketFd=-1) at /home/fx/workspace/Hyprland/src/Compositor.cpp:258
#5  0x00005555560125fe in main (argc=1, argv=0x7fffffffdf48) at /home/fx/workspace/Hyprland/src/main.cpp:150
```
There is an unconditional dereference which leads to the unmapped region access.

```
(gdb) p *this
$1 = {m_sWLDisplay = 0x555556c368d0, m_sWLEventLoop = 0x555556c369c0, m_iDRMFD = -1, m_bInitialized = false, m_pAqBackend = {impl_ = 0x555556cc1c10}, m_szHyprTempDataRoot = "/run/user/1000/hypr", m_szWLDisplaySocket = "", m_szInstanceSignature = "9a09eac79b85c846e3a865a9078a3f8ff65a9259_1723397513_332879213",
  m_szInstancePath = "/run/user/1000/hypr/9a09eac79b85c846e3a865a9078a3f8ff65a9259_1723397513_332879213", m_szCurrentSplash = "\"This will never get into Hyprland\" - Flafy", m_vMonitors = std::vector of length 0, capacity 0, m_vRealMonitors = std::vector of length 0, capacity 0,
  m_vWindows = std::vector of length 0, capacity 0, m_vLayers = std::vector of length 0, capacity 0, m_vWorkspaces = std::vector of length 0, capacity 0, m_vWindowsFadingOut = std::vector of length 0, capacity 0, m_vSurfacesFadingOut = std::vector of length 0, capacity 0,
  m_mMonitorIDMap = std::unordered_map with 0 elements, m_pLastFocus = {impl_ = 0x0}, m_pLastWindow = {impl_ = 0x0}, m_pLastMonitor = {impl_ = 0x0}, m_vWindowFocusHistory = std::vector of length 0, capacity 0, m_bReadyToProcess = false, m_bSessionActive = true, m_bDPMSStateON = true, m_bUnsafeState = false,
  m_bNextIsUnsafe = false, m_pUnsafeOutput = 0x0, m_bIsShuttingDown = false, explicitConfigPath = "", m_iHyprlandPID = 24351, m_critSigSource = 0x555556c36ac0, m_sOriginalNofile = {rlim_cur = 1024, rlim_max = 1048576}}
  ```

**hyprlandCrashReport16766.txt**
```
--------------------------------------------
   Hyprland Crash Report
--------------------------------------------
I don't feel so good...

Hyprland received signal 11(SEGV)
Version: 9a09eac79b85c846e3a865a9078a3f8ff65a9259
Tag: v0.42.0
Date: Wed Aug 7 21:17:10 2024
Flags:

System info:
	System name: Linux
	Node name: purplejam
	Release: 6.10.3-arch1-2
	Version: #1 SMP PREEMPT_DYNAMIC Tue, 06 Aug 2024 07:21:19 +0000

GPU:
	01:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD102 [GeForce RTX 4090] [10de:2684] (rev a1) (prog-if 00 [VGA controller])


os-release:
	NAME="Arch Linux"
	PRETTY_NAME="Arch Linux"
	ID=arch
	BUILD_ID=rolling
	ANSI_COLOR="38;2;23;147;209"
	HOME_URL="https://archlinux.org/"
	DOCUMENTATION_URL="https://wiki.archlinux.org/"
	SUPPORT_URL="https://bbs.archlinux.org/"
	BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
	PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
	LOGO=archlinux-logo
Backtrace:
	# | ./build/Hyprland(_Z12getBacktracev+0x46) [0x59800ef06c36]
		getBacktrace()
		??:?
	#1 | ./build/Hyprland(_ZN13CrashReporter18createAndSaveCrashEi+0x98d) [0x59800ee63d5d]
		CrashReporter::createAndSaveCrash(int)
		??:?
	#2 | ./build/Hyprland(_Z25handleUnrecoverableSignali+0x5c) [0x59800edd231c]
		handleUnrecoverableSignal(int)
		??:?
	#3 | /usr/lib/libc.so.6(+0x3d1d0) [0x762d23c4c1d0]
		??
		??:0


Log tail:
[LOG] Runtime directory: /run/user/1000/hypr/9a09eac79b85c846e3a865a9078a3f8ff65a9259_1723396410_469725528
[LOG] Hyprland PID: 16766
[LOG] ===== SYSTEM INFO: =====
[LOG] System name: Linux
[LOG] Node name: purplejam
[LOG] Release: 6.10.3-arch1-2
[LOG] Version: #1 SMP PREEMPT_DYNAMIC Tue, 06 Aug 2024 07:21:19 +0000


[LOG] GPU information:
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD102 [GeForce RTX 4090] [10de:2684] (rev a1) (prog-if 00 [VGA controller])


[WARN] Warning: you're using an NVIDIA GPU. Make sure you follow the instructions on the wiki if anything is amiss.

[LOG] os-release:
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

[LOG] ========================



[INFO] If you are crashing, or encounter any bugs, please consult https://wiki.hyprland.org/Crashes-and-Bugs/


[LOG]
Current splash: Take on me, take me on...


[LOG] Old rlimit: soft -> 1024, hard -> 1048576
[LOG] New rlimit: soft -> 1048576, hard -> 1048576
[LOG] Creating the EventLoopManager!
[LOG] Creating the HookSystem!
[LOG] Creating the KeybindManager!
[LOG] Creating the AnimationManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 15.41µs. Estimated average calc time: 0.00µs.
[LOG] Creating the ConfigManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 5.01µs. Estimated average calc time: 0.00µs.
[LOG] Using config: /home/user/.config/hypr/hyprland.conf
[INFO] !!!!HEY YOU, YES YOU!!!!: further logs to stdout / logfile are disabled by default. BEFORE SENDING THIS LOG, ENABLE THEM. Use debug:disable_logs = false to do so: https://wiki.hyprland.org/Configuring/Variables/#debug
[LOG] Creating the CHyprError!
[LOG] Creating the LayoutManager!
[LOG] Creating the TokenManager!
[LOG] [hookSystem] New hook event registered: preConfigReload
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 4.93µs. Estimated average calc time: 0.00µs.
[LOG] Using config: /home/fx/.config/hypr/hyprland.conf
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 4.95µs. Estimated average calc time: 0.00µs.
[ERR] Invalid dispatcher!
[ERR] Invalid dispatcher!
[ERR] Invalid dispatcher!
[ERR] Invalid dispatcher!
[ERR] Invalid dispatcher!
[ERR] Invalid dispatcher!
[ERR] Invalid dispatcher!
[ERR] Invalid dispatcher!
[ERR] Invalid dispatcher!
[ERR] Invalid dispatcher!
[ERR] Invalid dispatcher!
[ERR] Invalid dispatcher!
[ERR] Invalid dispatcher!
[ERR] Invalid dispatcher!
[ERR] Invalid dispatcher!
[ERR] Invalid dispatcher!
[ERR] Invalid dispatcher!
[ERR] Invalid dispatcher!
[ERR] Invalid dispatcher!
[ERR] Invalid dispatcher!
[ERR] Invalid dispatcher!
[ERR] Invalid dispatcher!
[ERR] Invalid dispatcher!
[LOG] Creating the PointerManager!
[LOG] Creating the EventManager!
[LOG] [AQ] Creating an Aquamarine backend!
[LOG] [AQ] [libseat] [libseat/backend/seatd.c:64] Could not connect to socket /run/seatd.sock: No such file or directory
[LOG] [AQ] [libseat] [libseat/libseat.c:76] Backend 'seatd' failed to open seat, skipping
[ERR] [AQ] [libseat] [libseat/backend/logind.c:349] Could not take control of session: Device or resource busy
[LOG] [AQ] [libseat] [libseat/libseat.c:76] Backend 'logind' failed to open seat, skipping
[ERR] [AQ] [libseat] [libseat/libseat.c:79] No backend was able to open a seat
[ERR] [AQ] libseat: failed to open a seat
[ERR] [AQ] Failed to open a session
[ERR] [AQ] DRM Backend failed
```
Please note that the line:
```
[INFO] !!!!HEY YOU, YES YOU!!!!: further logs to stdout / logfile are disabled by default. BEFORE SENDING THIS LOG, ENABLE THEM. Use debug:disable_logs = false to do so: https://wiki.hyprland.org/Configuring/Variables/#debug
```
is appearing all the time regardless of the setting. As you may see in the first text, the config is set:
```
debug {
    enable_stdout_logs = true
    disable_logs = false
}
```
if it helps,
```
gcc --version
gcc (GCC) 14.2.1 20240805
```

**Comment by MightyPlaza** [comment]
try installing seatd

**Comment by vaxerski** [comment]
as above

**Comment by iddm** [comment]
> try installing seatd

How?

```
❯ pacman -S seatd
warning: seatd-0.8.0-2 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) seatd-0.8.0-2

Total Installed Size:  0.11 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] n
```

**Comment by vaxerski** [comment]
seatd has always been required. Dunno why it worked before.

**Comment by iddm** [comment]
> seatd has always been required. Dunno why it worked before.

Thanks for the reply! Weird :-) Have a great day!
