### ISSUE TITLE
Crashing on registerStaticListener in monitor layout

### ISSUE THREAD

**Issue by jilen** [hyprwm/Hyprland#7426]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh

flags: (if any)


System Information:
System name: Linux
Node name: jilen.moe
Release: 6.10.5-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Thu, 15 Aug 2024 00:25:30 +0000


GPU information:
2b:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU116 [GeForce GTX 1660 SUPER] [10de:21c4] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX Open Kernel Module for x86_64  555.58.02  Release Build  (archlinux-builder@)


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Description

Still crash with latest aquamarine and hyprland-git
Commit c5feee1e357f3c3c59ebe406630601c627807963 works fine.

### How to reproduce

Start hyprland

### Crash reports, logs, images, videos

<details>
<summary>CrashLog</summary>

```
   Hyprland Crash Report
--------------------------------------------
"stable"

Hyprland received signal 11(SEGV)
Version: c86db7bbb0cf14d4955ee3a4d13c0ed9f8a0e0ae
Tag: v0.42.0-46-gc86db7bb
Date: Tue Aug 20 00:44:22 2024
Flags:

System info:
	System name: Linux
	Node name: jilen.moe
	Release: 6.10.5-arch1-1
	Version: #1 SMP PREEMPT_DYNAMIC Thu, 15 Aug 2024 00:25:30 +0000

GPU:
	2b:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU116 [GeForce GTX 1660 SUPER] [10de:21c4] (rev a1) (prog-if 00 [VGA controller])


os-release:
	NAME="Arch Linux"
	PRETTY_NAME="Arch Linux"
	ID=arch
	BUILD_ID=rolling
	ANSI_COLOR="38;2;23;147;209"
	HOME_URL="https://archlinux.org/"
	DOCUMENTATION_URL="https://wiki.archlinux.org/"
	SUPPORT_URL="https://bbs.archlinux.org/"
	BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
	PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
	LOGO=archlinux-logo
Backtrace:
	# | Hyprland(_Z12getBacktracev+0x46) [0x588165988556]
		getBacktrace()
		??:?
	#1 | Hyprland(_ZN13CrashReporter18createAndSaveCrashEi+0xabe) [0x58816591017e]
		CrashReporter::createAndSaveCrash(int)
		??:?
	#2 | Hyprland(_Z25handleUnrecoverableSignali+0x5c) [0x5881658a4f8c]
		handleUnrecoverableSignal(int)
		??:?
	#3 | /usr/lib/libc.so.6(+0x3d1d0) [0x742995c4c1d0]
		??
		??:0
	#4 | /usr/lib/libhyprutils.so.1(_ZN9Hyprutils6Signal7CSignal22registerStaticListenerESt8functionIFvPvSt3anyEES3_+0x9d) [0x74299679af7d]
		??
		??:0
	#5 | Hyprland(+0x37036f) [0x588165a1336f]
		CPointerManager::onMonitorLayoutChange()
		??:?
	#6 | Hyprland(_ZN18CHookSystemManager4emitEPSt6vectorI14SCallbackFNPtrSaIS1_EER13SCallbackInfoSt3any+0x48c) [0x5881659bfeac]
		CHookSystemManager::emit(std::vector<SCallbackFNPtr, std::allocator<SCallbackFNPtr> >*, SCallbackInfo&, std::any)
		??:?
	#7 | Hyprland(_ZN8CMonitor9onConnectEb+0x111a) [0x5881659879ea]
		CMonitor::onConnect(bool)
		??:?
	#8 | Hyprland(_ZN11CCompositor12onNewMonitorEN9Hyprutils6Memory14CSharedPointerIN10Aquamarine7IOutputEEE+0x2ad) [0x5881658c762d]
		CCompositor::onNewMonitor(Hyprutils::Memory::CSharedPointer<Aquamarine::IOutput>)
		??:?
	#9 | Hyprland(_ZN11CCompositor10initServerENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEi+0xc65) [0x5881658a6ba5]
		CCompositor::initServer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int)
		??:?
	#1 | Hyprland(main+0xbaa) [0x58816583d4ea]
		main
		??:?
	#11 | /usr/lib/libc.so.6(+0x25e08) [0x742995c34e08]
		??
		??:0
	#12 | /usr/lib/libc.so.6(__libc_start_main+0x8c) [0x742995c34ecc]
		??
		??:0
	#13 | Hyprland(_start+0x25) [0x58816586bfd5]
		_start
		??:?


Log tail:
[LOG] [AQ] Swapchain: Reconfigured a swapchain to [Vector2D: x: 3840, y: 2160] XR24 of length 2
[LOG] CMonitorState::ensureBufferPresent: no buffer, attaching one from the swapchain for modeset being possible
[LOG] output HDMI-A-1 succeeded basic test on format DRM_FORMAT_XRGB8888
[LOG] [AQ] drm: Modesetting HDMI-A-1 with 3840x2160@60.00Hz
[LOG] Monitor HDMI-A-1 -> destroyed all render data
[LOG] arrangeMonitors: 1 to arrange
[LOG] arrangeMonitors: HDMI-A-1 auto [-1, -1]
[LOG] arrangeMonitors: HDMI-A-1 xwayland [0, 0]
[LOG] Monitor HDMI-A-1 data dump: res 3840x2160@60.00Hz, scale 1.67, transform 0, pos 0x0, 10b 0
[LOG] XCursor scanning theme default
[LOG] XCursor parsing index.theme /usr/share/icons/default/index.theme
[LOG] XCursor theme default inherits Adwaita
[LOG] XCursor scanning theme Adwaita
[LOG] XCursor using theme path /usr/share/icons/Adwaita/cursors
[LOG] XCursor parsing index.theme /usr/share/icons/Adwaita/index.theme
[LOG] XCursor theme Adwaita inherits AdwaitaLegacy
[LOG] XCursor theme Adwaita inherits hicolor
[LOG] XCursor scanning theme hicolor
[LOG] XCursor parsing index.theme /usr/share/icons/hicolor/index.theme
[LOG] XCursor scanning theme AdwaitaLegacy
[LOG] XCursor parsing index.theme /usr/share/icons/AdwaitaLegacy/index.theme
[LOG] XCursor theme AdwaitaLegacy inherits hicolor
[LOG] XCursor scanning theme Adwaita
[LOG] XCursor using theme path /usr/share/icons/Adwaita/cursors
[LOG] XCursor parsing index.theme /usr/share/icons/Adwaita/index.theme
[LOG] XCursor theme Adwaita inherits AdwaitaLegacy
[LOG] XCursor theme Adwaita inherits hicolor
[LOG] XCursor already has a shape default loaded, skipping
[LOG] XCursor already has a shape context-menu loaded, skipping
[LOG] XCursor already has a shape help loaded, skipping
[LOG] XCursor already has a shape pointer loaded, skipping
[LOG] XCursor already has a shape progress loaded, skipping
[LOG] XCursor already has a shape wait loaded, skipping
[LOG] XCursor failed to find a legacy shape with name plus, skipping
[LOG] XCursor already has a shape crosshair loaded, skipping
[LOG] XCursor already has a shape text loaded, skipping
[LOG] XCursor already has a shape vertical-text loaded, skipping
[LOG] XCursor failed to find a legacy shape with name dnd-link, skipping
[LOG] XCursor failed to find a legacy shape with name dnd-copy, skipping
[LOG] XCursor already has a shape move loaded, skipping
[LOG] XCursor failed to find a legacy shape with name dnd-none, skipping
[LOG] XCursor failed to find a legacy shape with name crossed_circle, skipping
[LOG] XCursor already has a shape grab loaded, skipping
[LOG] XCursor already has a shape grabbing loaded, skipping
[LOG] XCursor already has a shape e-resize loaded, skipping
[LOG] XCursor already has a shape n-resize loaded, skipping
[LOG] XCursor already has a shape ne-resize loaded, skipping
[LOG] XCursor already has a shape nw-resize loaded, skipping
[LOG] XCursor already has a shape s-resize loaded, skipping
[LOG] XCursor already has a shape se-resize loaded, skipping
[LOG] XCursor already has a shape sw-resize loaded, skipping
[LOG] XCursor already has a shape w-resize loaded, skipping
[LOG] XCursor already has a shape ew-resize loaded, skipping
[LOG] XCursor already has a shape ns-resize loaded, skipping
[LOG] XCursor already has a shape nesw-resize loaded, skipping
[LOG] XCursor already has a shape nwse-resize loaded, skipping
[LOG] XCursor already has a shape col-resize loaded, skipping
[LOG] XCursor already has a shape row-resize loaded, skipping
[LOG] XCursor already has a shape all-scroll loaded, skipping
[LOG] XCursor already has a shape zoom-in loaded, skipping
[LOG] XCursor already has a shape zoom-out loaded, skipping
[LOG] Added new monitor with name HDMI-A-1 at [0, 0] with size [3840, 2160], pointer 588183239580
[LOG] New monitor: WORKSPACEID 1, exists: 0
[LOG] [hookSystem] New hook event registered: createWorkspace
```
</details>

**Comment by vaxerski** [comment]
compile hyprutils in debug and get a debug stacktrace: https://wiki.hyprland.org/Crashes-and-Bugs/#obtaining-a-debug-stacktrace

**Comment by jilen** [comment]
```
0  0x000076cb855883f4 in ??? () at /usr/lib/libc.so.6
#1  0x000076cb8552f120 in raise () at /usr/lib/libc.so.6
#2  0x000076cb855164c3 in abort () at /usr/lib/libc.so.6
#3  0x000064fe2aa9df91 in handleUnrecoverableSignal(int) ()
#4  0x000076cb8552f1d0 in <signal handler called> () at /usr/lib/libc.so.6
#5  0x000076cb85fb68dd in Hyprutils::Signal::CSignal::registerStaticListener(std::function<void (void*, std::any)>, void*) () at /usr/lib/libhyprutils.so.1
#6  0x000064fe2ac0c36f in ??? ()
#7  0x000064fe2abb8eac in CHookSystemManager::emit(std::vector<SCallbackFNPtr, std::allocator<SCallbackFNPtr> >*, SCallbackInfo&, std::any) ()
#8  0x000064fe2ab809ea in CMonitor::onConnect(bool) ()
#9  0x000064fe2aac062d in CCompositor::onNewMonitor(Hyprutils::Memory::CSharedPointer<Aquamarine::IOutput>) ()
#10 0x000064fe2aa9fba5 in CCompositor::initServer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int) ()
#11 0x000064fe2aa364ea in main ()
```

**Comment by vaxerski** [comment]
hyprutils is not in debug

**Comment by jilen** [comment]
Hm, this is the aur build script for hyprutils, is that debug build ?
```
build() {
	cd "${srcdir}/${_pkgname}"
	cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_INSTALL_PREFIX:PATH=/usr -S . -B ./build
	cmake --build ./build --config Debug --target all
}

```
![微信图片_20240822095525](https://github.com/user-attachments/assets/a3a180c9-ae52-4ea3-a3af-2788f667dd26)

**Comment by vaxerski** [comment]
apparently not. AUR tends to do some stuff. Install it manually

**Comment by jilen** [comment]
```
#0  0x00007bd3cd5b63f4 in ??? () at /usr/lib/libc.so.6
#1  0x00007bd3cd55d120 in raise () at /usr/lib/libc.so.6
#2  0x00007bd3cd5444c3 in abort () at /usr/lib/libc.so.6
#3  0x00005baaae8a2551 in handleUnrecoverableSignal(int) ()
#4  0x00007bd3cd55d1d0 in <signal handler called> () at /usr/lib/libc.so.6
#5  0x00007bd3ce02d8e4 in std::vector<std::unique_ptr<Hyprutils::Signal::CStaticSignalListener, std::default_delete<Hyprutils::Signal::CStaticSignalListener> >, std::allocator<std::unique_ptr<Hyprutils::Signal::CStaticSignalListener, std::default_delete<Hyprutils::Signal::CStaticSignalListener> > > >::emplace_back<std::unique_ptr<Hyprutils::Signal::CStaticSignalListener, std::default_delete<Hyprutils::Signal::CStaticSignalListener> > > (this=0x438) at /usr/include/c++/14.2.1/bits/vector.tcc:114
#6  0x00007bd3ce02c4ce in Hyprutils::Signal::CSignal::registerStaticListener (this=0x420, handler=..., owner=0x0) at /home/jilen/.cache/yay/hyprutils-git/src/hyprutils/src/signal/Signal.cpp:56
#7  0x00005baaaea10f6f in ??? ()
#8  0x00005baaae9bdaac in CHookSystemManager::emit(std::vector<SCallbackFNPtr, std::allocator<SCallbackFNPtr> >*, SCallbackInfo&, std::any) ()
#9  0x00005baaae9855ea in CMonitor::onConnect(bool) ()
#10 0x00005baaae8c4bed in CCompositor::onNewMonitor(Hyprutils::Memory::CSharedPointer<Aquamarine::IOutput>) ()
#11 0x00005baaae8a4165 in CCompositor::initServer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int) ()
#12 0x00005baaae83aaaa in main ()
quit
```

**Comment by vaxerski** [comment]
thanks, that's good enough

**Comment by vaxerski** [comment]
wait, no, it's not, idk where it's called from, can you also build hyprland from source in debug?

basically it seems like there's a missing nullcheck somewhere (this = 0x420)

**Comment by jilen** [comment]
Hm, build from source won't crash anymore (both release & debug)...

**Comment by jilen** [comment]
Seems already fixed in recent commits
