### ISSUE TITLE
hyprland crash when external monitor connected on dgpu

### ISSUE THREAD

**Issue by gulafaran** [hyprwm/Hyprland#8224]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland 0.44.0 built from branch main at commit f603a22af0c8890b9742d761d44f0b595740f5b1  (internal: Remove some unused lambda captures (8218)).
Date: Thu Oct 24 14:12:41 2024
Tag: v0.44.0-71-gf603a22a, commits: 5370
built against aquamarine 0.4.3


flags set:
debug


System Information:
System name: Linux
Node name: heimdall
Release: 6.11.5-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Tue, 22 Oct 2024 18:31:38 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Raptor Lake-S UHD Graphics [8086:a788] (rev 04) (prog-if 00 [VGA controller])
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD104M [GeForce RTX 4080 Max-Q / Mobile] [10de:27e0] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX Open Kernel Module for x86_64  560.35.03  Release Build  (archlinux-builder@)  


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

======Config======

monitor = eDP-1, 2560x1600@240, 0x0, 1
monitor = DP-1, 2560x1440@160, 2560x0, 1
#monitor = DP-2, 2560x1440@160, 2560x0, 1
```

</details>

### Description

been using other WM's for a bit so not sure when this has begun occuring. but instant crash if external monitor is attached. everything -git built

```
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007ffff71b6463 in __pthread_kill_internal (threadid=<optimized out>, signo=6) at pthread_kill.c:78
#2  0x00007ffff715d120 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff71444c3 in __GI_abort () at abort.c:79
#4  0x000055555571a191 in handleUnrecoverableSignal (sig=11) at ../src/Compositor.cpp:80
#5  0x00007ffff715d1d0 in <signal handler called> () at /usr/lib/libc.so.6
#6  0x00007ffff7f24867 in Hyprutils::Memory::CSharedPointer<Aquamarine::IBuffer>::destroyImpl (this=<optimized out>) at /usr/include/hyprutils/memory/SharedPtr.hpp:282
#7  Hyprutils::Memory::CSharedPointer<Aquamarine::IBuffer>::decrement (this=<optimized out>) at /usr/include/hyprutils/memory/SharedPtr.hpp:265
#8  Hyprutils::Memory::CSharedPointer<Aquamarine::IBuffer>::~CSharedPointer (this=<optimized out>, __in_chrg=<optimized out>) at /usr/include/hyprutils/memory/SharedPtr.hpp:177
#9  Aquamarine::COutputState::SInternalState::~SInternalState (this=<optimized out>, __in_chrg=<optimized out>) at /usr/src/debug/aquamarine-git/aquamarine/./include/aquamarine/backend/drm/../../output/Output.hpp:58
#10 Aquamarine::COutputState::~COutputState (this=<optimized out>, __in_chrg=<optimized out>) at /usr/src/debug/aquamarine-git/aquamarine/./include/aquamarine/backend/drm/../../output/Output.hpp:42
#11 std::default_delete<Aquamarine::COutputState>::operator() (this=0x100000018, __ptr=<optimized out>) at /usr/include/c++/14.2.1/bits/unique_ptr.h:93
#12 Hyprutils::Memory::CSharedPointer_::impl<Aquamarine::COutputState>::_destroy (this=0xffffffff) at /usr/include/hyprutils/memory/SharedPtr.hpp:69
#13 Hyprutils::Memory::CSharedPointer_::impl<Aquamarine::COutputState>::destroy (this=0xffffffff) at /usr/include/hyprutils/memory/SharedPtr.hpp:103
#14 Hyprutils::Memory::CSharedPointer<Aquamarine::SDRMPlane>::destroyImpl (this=0x7fffffffda10) at /usr/include/hyprutils/memory/SharedPtr.hpp:279
#15 Hyprutils::Memory::CSharedPointer<Aquamarine::SDRMPlane>::decrement (this=0x7fffffffda10) at /usr/include/hyprutils/memory/SharedPtr.hpp:265
#16 Hyprutils::Memory::CSharedPointer<Aquamarine::SDRMPlane>::~CSharedPointer (this=0x7fffffffda10, __in_chrg=<optimized out>) at /usr/include/hyprutils/memory/SharedPtr.hpp:177
#17 Aquamarine::CDRMAtomicImpl::reset (this=<optimized out>) at /usr/src/debug/aquamarine-git/aquamarine/src/backend/drm/impl/Atomic.cpp:352
#18 0x00007ffff7f2b817 in Hyprutils::Memory::CSharedPointer<Aquamarine::IBuffer>::decrement (this=0x555556e048f8) at /usr/include/hyprutils/memory/SharedPtr.hpp:261
#19 Hyprutils::Memory::CSharedPointer<Aquamarine::IBuffer>::~CSharedPointer (this=0x555556e048f8, __in_chrg=<optimized out>) at /usr/include/hyprutils/memory/SharedPtr.hpp:177
#20 Aquamarine::COutputState::SInternalState::~SInternalState (this=0x555556e04890, __in_chrg=<optimized out>) at /usr/src/debug/aquamarine-git/aquamarine/./include/aquamarine/output/Output.hpp:58
#21 Aquamarine::COutputState::~COutputState (this=0x555556e04890, __in_chrg=<optimized out>) at /usr/src/debug/aquamarine-git/aquamarine/./include/aquamarine/output/Output.hpp:42
#22 std::default_delete<Aquamarine::COutputState>::operator() (this=0x19, __ptr=0x555556e04890) at /usr/include/c++/14.2.1/bits/unique_ptr.h:93
#23 Hyprutils::Memory::CSharedPointer_::impl<Aquamarine::COutputState>::_destroy (this=0x0) at /usr/include/hyprutils/memory/SharedPtr.hpp:69
#24 Hyprutils::Memory::CSharedPointer_::impl<Aquamarine::COutputState>::destroy (this=0x0) at /usr/include/hyprutils/memory/SharedPtr.hpp:103
#25 Hyprutils::Memory::CSharedPointer<Aquamarine::SOutputMode>::destroyImpl (this=0x7fffffffdb78) at /usr/include/hyprutils/memory/SharedPtr.hpp:279
#26 Hyprutils::Memory::CSharedPointer<Aquamarine::SOutputMode>::decrement (this=0x7fffffffdb78) at /usr/include/hyprutils/memory/SharedPtr.hpp:265
#27 Hyprutils::Memory::CSharedPointer<Aquamarine::SOutputMode>::~CSharedPointer (this=0x7fffffffdb78, __in_chrg=<optimized out>) at /usr/include/hyprutils/memory/SharedPtr.hpp:177
#28 Aquamarine::COutputState::SInternalState::~SInternalState (this=0x7fffffffdb20, __in_chrg=<optimized out>) at /usr/src/debug/aquamarine-git/aquamarine/./include/aquamarine/output/Output.hpp:58
#29 Aquamarine::COutputState::~COutputState (this=0x7fffffffdb20, __in_chrg=<optimized out>) at /usr/src/debug/aquamarine-git/aquamarine/./include/aquamarine/output/Output.hpp:42
#30 std::default_delete<Aquamarine::COutputState>::operator() (this=0x19, __ptr=0x7fffffffdb20) at /usr/include/c++/14.2.1/bits/unique_ptr.h:93
#31 Hyprutils::Memory::CSharedPointer_::impl<Aquamarine::COutputState>::_destroy (this=0x0) at /usr/include/hyprutils/memory/SharedPtr.hpp:69
#32 Hyprutils::Memory::CSharedPointer_::impl<Aquamarine::COutputState>::destroy (this=0x0) at /usr/include/hyprutils/memory/SharedPtr.hpp:103
#33 Hyprutils::Memory::CSharedPointer_::impl<Aquamarine::COutputState>::~impl (this=0x0, __in_chrg=<optimized out>) at /usr/include/hyprutils/memory/SharedPtr.hpp:119
#34 Hyprutils::Memory::CSharedPointer_::impl<Aquamarine::COutputState>::~impl (this=0x0, __in_chrg=<optimized out>) at /usr/include/hyprutils/memory/SharedPtr.hpp:120
#35 Hyprutils::Memory::CWeakPointer<Aquamarine::SOutputMode>::decrementWeak (this=0x2d4eb55ffe9ce400) at /usr/include/hyprutils/memory/WeakPtr.hpp:172
#36 0x00007ffff7f1ca1e in Hyprutils::Memory::CSharedPointer<Hyprutils::Signal::CSignalListener>::destroyImpl (this=0x555555e03a38) at /usr/include/hyprutils/memory/SharedPtr.hpp:282
#37 Hyprutils::Memory::CSharedPointer<Hyprutils::Signal::CSignalListener>::decrement (this=0x555555e03a38) at /usr/include/hyprutils/memory/SharedPtr.hpp:265
#38 Hyprutils::Memory::CSharedPointer<Hyprutils::Signal::CSignalListener>::~CSharedPointer (this=0x555555e03a38, __in_chrg=<optimized out>) at /usr/include/hyprutils/memory/SharedPtr.hpp:177
#39 Aquamarine::CDRMRendererBufferAttachment::~CDRMRendererBufferAttachment (this=0x555555e03a10, __in_chrg=<optimized out>) at /usr/src/debug/aquamarine-git/aquamarine/src/backend/drm/Renderer.hpp:30
#40 Aquamarine::CDRMRendererBufferAttachment::~CDRMRendererBufferAttachment (this=0x555555e03a10, __in_chrg=<optimized out>) at /usr/src/debug/aquamarine-git/aquamarine/src/backend/drm/Renderer.hpp:30
#41 0x0000555555a03c96 in CHyprRenderer::applyMonitorRule (this=0x0, pMonitor=..., pMonitorRule=0x0, force=128) at ../src/render/Renderer.cpp:2339
#42 0x0000555555805477 in CMonitor::onConnect (this=0x555557178860, noRule=true) at ../src/helpers/Monitor.cpp:174
#43 0x000055555573a156 in CCompositor::onNewMonitor (this=0x0, output=...) at ../src/Compositor.cpp:3062
#44 0x0000555555721ad6 in CCompositor::initServer (this=0x555555da34b0, socketName=<error: Cannot access memory at address 0x7300676e69>, socketFd=-6528) at ../src/Compositor.cpp:339
#45 0x00005555556a696c in main (argc=0, argv=0x1) at ../src/main.cpp:165
```

### How to reproduce

just attach monitor in this case to DP-1 and it crashes on launch.

**Comment by gulafaran** [comment]
ok interestingly its because i had these set, used to set those on kwin to kinda force all apps run on intel and yet have external monitor going on nvidia. commenting it out and runs again

```
#force intel for nvidia D3 power management
#env = ENABLE_DEVICE_CHOOSER_LAYER,1
#env = VULKAN_DEVICE_INDEX,0
#env = DXVK_FILTER_DEVICE_NAME,Intel
#env = VKD3D_FILTER_DEVICE_NAME,Intel
#env = MESA_VK_DEVICE_SELECT,8086:a788
#env = __GLX_VENDOR_LIBRARY_NAME,mesa
#env = __EGL_VENDOR_LIBRARY_FILENAMES,/usr/share/glvnd/egl_vendor.d/50_mesa.json
#env = VK_ICD_FILENAMES,/usr/share/vulkan/icd.d/intel_icd.x86_64.json:/usr/share/vulkan/icd.d/intel_icd.i686.json
#env = __NV_PRIME_RENDER_OFFLOAD,0
#env = __VK_LAYER_NV_optimus,non_NVIDIA_only
#env = LIBVA_DRIVER_NAME,iHD
#env = VDPAU_DRIVER,va_gl
#env = WLR_RENDER_DRM_DEVICE,/dev/dri/renderD129
#env = WLR_DRM_DEVICES/dev/dri/card0
#env = GST_VAAPI_DRM_DEVICE,/dev/dri/renderD129
```

**Comment by vaxerski** [comment]
which one specifically is at fault?

**Comment by vaxerski** [comment]
yeee its likely not a hl issue
