### ISSUE TITLE
Crashes on launch since d8b8653

### ISSUE THREAD

**Issue by matt1432** [hyprwm/Hyprland#8325]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland 0.44.0 built from branch  at commit 3852418d2446555509738bf1486940042107afe7  ().
Date: 2024-11-01
Tag: , commits: 
built against aquamarine 0.4.3


flags set:
debug


System Information:
System name: Linux
Node name: binto
Release: 6.11.5-zen1
Version: #1-NixOS ZEN SMP PREEMPT_DYNAMIC Tue Jan  1 00:00:00 UTC 1980


GPU information: 
06:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA104 [GeForce RTX 3070 Lite Hash Rate] [10de:2488] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX x86_64 Kernel Module  560.35.03  Fri Aug 16 21:39:15 UTC 2024


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.11.20241029.807e915"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.11 (Vicuna)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.11 (Vicuna)"
VERSION_CODENAME=vicuna
VERSION_ID="24.11"


plugins:
  hyprexpo by Vaxry ver 1.0

======Config-Start======


Config File: /home/matt/.config/hypr/hyprland.conf: Read Succeeded
exec-once = /nix/store/ldpr2fzzk97pzml87z7lmvhqg7pp65lf-dbus-1.14.10/bin/dbus-update-activation-environment --systemd -all && systemctl --user stop hyprland-session.target && systemctl --user start hyprland-session.target
plugin=/nix/store/c0msia6gcw1i2b0mdbrll3f74fh8zq3q-hyprexpo-0.1/lib/libhyprexpo.so
$mainMod=SUPER
source=/home/matt/.nix/devices/binto/config/hypr/main.conf
animations {
  bezier=easeInOutQuart, 0.77, 0   , 0.175, 1
  bezier=easeInExpo    , 0.95, 0.05, 0.795, 0.035
  animation=fadeLayersIn , 0
  animation=fadeLayersOut, 1, 3000, easeInExpo
  animation=layers       , 1, 4   , easeInOutQuart, slide left
}

cursor {
  hide_on_touch=true
  no_hardware_cursors=true
}

device {
  name=logitech-g502-x
  accel_profile=flat
  sensitivity=0
}

device {
  name=logitech-g502-hero-gaming-mouse
  accel_profile=flat
  sensitivity=0
}

dwindle {
  smart_split=true
  special_scale_factor=0.800000
}

input {
  touchpad {
    disable_while_typing=false
    drag_lock=true
    natural_scroll=true
    tap-and-drag=true
  }
  follow_mouse=true
  kb_layout=ca
  kb_variant=multix
  numlock_by_default=true
  repeat_rate=25
}

misc {
  disable_hyprland_logo=true
  disable_splash_rendering=true
  vfr=true
}

plugin {
  hyprexpo {
    bg_col=rgb(111111)
    columns=3
    enable_gesture=true
    gap_size=5
    gesture_distance=300
    gesture_fingers=3
    gesture_positive=true
    workspace_method=center current
  }
}

xwayland {
  force_zero_scaling=true
}
bind=,XF86AudioPlay, exec, playerctl play-pause
bind=,XF86AudioStop, exec, playerctl stop
bind=,XF86AudioNext, exec, playerctl next
bind=,XF86AudioPrev, exec, playerctl previous
bind=ALT, tab, hyprexpo:expo, toggle
bind=$mainMod SHIFT, E    , exec, pgrep ags -a | grep '/bin/gjs' && ags -t win-powermenu || agsV2 -t win-powermenu
bind=$mainMod      , D    , exec, pgrep ags -a | grep '/bin/gjs' && ags -t win-applauncher || agsV2 -t win-applauncher
bind=$mainMod      , V    , exec, pgrep ags -a | grep '/bin/gjs' && ags -t win-clipboard || agsV2 -t win-clipboard
bind=              , Print, exec, pgrep ags -a | grep '/bin/gjs' && ags -t win-screenshot || agsV2 -t win-screenshot
bind=,F8, exec, ags -r 'GSR.saveReplay()'
bind=$mainMod, F,    fullscreen
bind=$mainMod, C,    killactive
bind=$mainMod SHIFT, SPACE,     togglefloating
bind=$mainMod, J,    layoutmsg, togglesplit
bind=$mainMod, left,  movefocus, l
bind=$mainMod, right, movefocus, r
bind=$mainMod, up,    movefocus, u
bind=$mainMod, down,  movefocus, d
bind=$mainMod, 1, workspace, 1
bind=$mainMod, 2, workspace, 2
bind=$mainMod, 3, workspace, 3
bind=$mainMod, 4, workspace, 4
bind=$mainMod, 5, workspace, 5
bind=$mainMod, 6, workspace, 6
bind=$mainMod, 7, workspace, 7
bind=$mainMod, 8, workspace, 8
bind=$mainMod, 9, workspace, 9
bind=$mainMod, 0, workspace, 10
bind=$mainMod SHIFT, 1, movetoworkspace, 1
bind=$mainMod SHIFT, 2, movetoworkspace, 2
bind=$mainMod SHIFT, 3, movetoworkspace, 3
bind=$mainMod SHIFT, 4, movetoworkspace, 4
bind=$mainMod SHIFT, 5, movetoworkspace, 5
bind=$mainMod SHIFT, 6, movetoworkspace, 6
bind=$mainMod SHIFT, 7, movetoworkspace, 7
bind=$mainMod SHIFT, 8, movetoworkspace, 8
bind=$mainMod SHIFT, 9, movetoworkspace, 9
bind=$mainMod SHIFT, 0, movetoworkspace, 10
bind=,XF86AudioMute,    exec, pactl set-sink-mute @DEFAULT_SINK@ toggle
bind=,XF86AudioMicMute, exec, pactl set-source-mute @DEFAULT_SOURCE@ toggle
bind=$mainMod, Print, exec, bash -c "grim -g \"$(slurp)\" - | satty -f -"
bind=$mainMod, L, exec, /nix/store/jqlmwddaylyd1pbkcqmr1j5cmaivm7vf-lock/bin/lock
bind=$mainMod, Q, exec, foot
bind=$mainMod SHIFT, C, exec, wl-color-picker
bind=$mainMod, P, togglespecialworkspace, protonmail
bind=$mainMod, S, togglespecialworkspace, spot
binde=, XF86MonBrightnessUp  , exec, pgrep ags -a | grep '/bin/gjs' && ags -r 'Brightness.screen += 0.05' || agsV2 -m 'Brightness.screen += 0.05'
binde=, XF86MonBrightnessDown, exec, pgrep ags -a | grep '/bin/gjs' && ags -r 'Brightness.screen -= 0.05' || agsV2 -m 'Brightness.screen -= 0.05'
binde=, XF86AudioRaiseVolume , exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+ & pgrep ags -a | grep '/bin/gjs' && ags -r 'popup_osd("speaker")' || agsV2 -m 'popup_osd("speaker")' &
binde=, XF86AudioLowerVolume , exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- & pgrep ags -a | grep '/bin/gjs' && ags -r 'popup_osd("speaker")' || agsV2 -m 'popup_osd("speaker")' &
bindm=$mainMod, mouse:272, movewindow
bindm=$mainMod, mouse:273, resizewindow
bindn=    , Escape   , exec, pgrep ags -a | grep '/bin/gjs' && ags -r 'closeAll()' || agsV2 -m 'closeAll()'
bindr=CAPS, Caps_Lock, exec, pgrep ags -a | grep '/bin/gjs' && ags -r 'Brightness.fetchCapsState()' || agsV2 -m 'Brightness.fetchCapsState()'
envd=XCURSOR_THEME, Dracula-cursors
envd=XCURSOR_SIZE, 24
envd=GTK_USE_PORTAL, 1
envd=NIXOS_OZONE_WL, 1
envd=ELECTRON_OZONE_PLATFORM_HINT, auto
envd=XDG_DATA_DIRS, /nix/store/x2c1xy5di8wlsd2nbsl35m0g7hf3xc0q-gsettings-desktop-schemas-46.0/share/gsettings-schemas/gsettings-desktop-schemas-46.0:/nix/store/z49s72m05k5daqmv7pajncx55v4p8fnm-gtk+3-3.24.43/share/gsettings-schemas/gtk+3-3.24.43:$XDG_DATA_DIRS
envd=LIBVA_DRIVER_NAME, nvidia
envd=XDG_SESSION_TYPE, wayland
envd=GBM_BACKEND, nvidia-drm
envd=__GLX_VENDOR_LIBRARY_NAME, nvidia
exec-once=hyprctl setcursor Dracula-hyprcursor 24
exec-once=hyprctl dispatch focusmonitor desc:GIGA-BYTE TECHNOLOGY CO. LTD. G27QC 0x00000B1D
exec-once=ags
exec-once=sleep 3; ags -r 'App.openWindow("win-applauncher")'
exec-once=gnome-keyring-daemon --start --components=secrets
exec-once=/nix/store/kz54544macmpaddfv871cq7ia8sl3icf-polkit-kde-agent-1-5.27.11/libexec/polkit-kde-authentication-agent-1
exec-once=/nix/store/ch6kr38vard7lilzzi2d0qdn6p14zxnl-kdeconnect-kde-23.08.5/libexec/kdeconnectd
exec-once=kdeconnect-indicator
exec-once=wl-paste --watch cliphist store
exec-once=sleep 3; nextcloud --background
exec-once=sleep 10; tmux new-session -s protonmail-bridge -d 'bash -c protonmail-bridge -c'
exec-once=[workspace special:protonmail silent] sleep 10; proton-mail
exec-once=[workspace special:spot silent] spotify
exec-once=sleep 3; /nix/store/yig2zjrqsy5l0rlzcwn5b4hhj7nindf8-restartTailscale/bin/restartTailscale
layerrule=noanim, ^(?!win-).*
layerrule=blur, ^(blur-bg.*)
layerrule=ignorealpha 0.19, ^(blur-bg.*)
monitor=desc:Acer Technologies Acer K212HQL T3EAA0014201,1920x1080@60,840x450, 1, transform, 3
monitor=desc:BOE 0x0964,1920x1200@60,0x2920, 1
monitor=desc:Samsung Electric Company C27JG5x HTOM100586,2560x1440@120,1920x120, 1
monitor=desc:GIGA-BYTE TECHNOLOGY CO. LTD. G27QC 0x00000B1D,2560x1440@120,1920x1560, 1
monitor=desc:Sharp Corporation LC-40LB480U 0x00000001,1680x1050, auto, 1,mirror, desc:GIGA-BYTE TECHNOLOGY CO. LTD. G27QC 0x00000B1D
windowrule=float,^(org.kde.polkit-kde-authentication-agent-1)$
windowrule=size 741 288,^(org.kde.polkit-kde-authentication-agent-1)$
windowrule=center,^(org.kde.polkit-kde-authentication-agent-1)$
windowrule=size 741 288,^(org.kde.ksshaskpass)$
windowrule=move cursor -370 -144,^(org.kde.ksshaskpass)$
windowrule=tile,^(libreoffice)$
windowrule=float,^(org.gnome.Calculator)$
windowrule=float,^(com.gabm.satty)$
windowrule=size 1000 700,^(com.gabm.satty)$
windowrule=float,^(com.nextcloud.desktopclient.nextcloud)$
windowrule=move cursor -15 -10,^(com.nextcloud.desktopclient.nextcloud)$
windowrule=size 400 581,^(com.nextcloud.desktopclient.nextcloud)$
windowrule=workspace special:protonmail silent,^(Proton Mail)$
windowrule=workspace special:spot silent,^(Spotify)$


Config File: /home/matt/.nix/devices/binto/config/hypr/main.conf: Read Succeeded
# Cosmetic
general {
    gaps_in = 10
    gaps_out = 20
    border_size = 0
}

======Config-End========
```

</details>

### Description

Whenever I launch Hyprland, it crashes after 1 or 2 seconds with ags launching.

If I don't have ags launch, it'll work until I drag a window for a few seconds.

This only happens on my NVIDIA machine as far as I can tell.

I bissected and this only happens since d8b865366af9d5ed30d2ee0a437b9a3ed43c10bd

### How to reproduce

Launch Hyprland with ags on my NVIDIA machine, or just drag a window.

### Crash reports, logs, images, videos

No crash reports were generated for some reason

**Comment by DockterTeagle** [comment]
getting I think a similar issue with crash report here, this occurs on latest git anytime I move a window between monitors, my system info is also in another of the provided files, while I dont get it to crash on a notification I do think this is similar enough to be of use here.
[sysinfo.txt](https://github.com/user-attachments/files/17605439/sysinfo.txt)

[log.txt](https://github.com/user-attachments/files/17605436/log.txt)

**Comment by DockterTeagle** [comment]
forgot to include crash report, which is provided here( I provided the most recent one but can provide more if needed)
[hyprlandCrashReport10043.txt](https://github.com/user-attachments/files/17605456/hyprlandCrashReport10043.txt)

**Comment by nonetrix** [comment]
Same here, layer shells are broken lol

**Comment by ebuttonsdude** [comment]
Getting similar behavior here on AMD, whenever I move a window with my mouse instead of with the keyboard, or launch discord it crashes. Here's my log files (-debug has the HYPRLAND_TRACE=1 AQ_TRACE=1 env
[hyprlandCrashReport4239-debug.txt](https://github.com/user-attachments/files/17606098/hyprlandCrashReport4239-debug.txt)
[hyprlandCrashReport11961-opened-discord.txt](https://github.com/user-attachments/files/17606099/hyprlandCrashReport11961-opened-discord.txt)
[hyprlandCrashReport10888-moving-floating-window-with-mouse.txt](https://github.com/user-attachments/files/17606100/hyprlandCrashReport10888-moving-floating-window-with-mouse.txt)
[hyprlandCrashReport968-moving-tiled-window-with-mouse.txt](https://github.com/user-attachments/files/17606101/hyprlandCrashReport968-moving-tiled-window-with-mouse.txt)
 variables).

**Comment by leiserfg** [comment]
After this factorio crashes hyprland at startup as well.
[CRASHhyprlandCrashReport724295.txt](https://github.com/user-attachments/files/17606230/CRASHhyprlandCrashReport724295.txt)

**Comment by Ciflire** [comment]
same here with vesktop if running on native wayland, running it on X will not crash hyprland
[gdb.txt](https://github.com/user-attachments/files/17606458/gdb.txt)
[hyprlandCrashReport27102.txt](https://github.com/user-attachments/files/17606459/hyprlandCrashReport27102.txt)

**Comment by Ciflire** [comment]
Second crash if i try to switch librewolf from a monitor to an other by dragging the window (shortcut works)
[gdb.txt](https://github.com/user-attachments/files/17606516/gdb.txt)
[hyprlandCrashReport8336.txt](https://github.com/user-attachments/files/17606518/hyprlandCrashReport8336.txt)

**Comment by NotAF0e** [comment]
I'm getting crashing to tty after pressing the properties button in Zen Browser and randomly when scrolling too. Will send logs in a bit

**Comment by NotAF0e** [comment]
I downgraded to `0.44.0.r94.ee91df62-1` and everything is fine

**Comment by RadicalTray** [comment]
Having these 2 lines make hyprland crash on launch for me
```
exec-once = waybar
layerrule = blur, waybar
```
but if I commented out `layerrule = blur, waybar` and uncomment it after launching, it doesn't seem to crash.

[hyprlandCrashReport18794.txt](https://github.com/user-attachments/files/17607060/hyprlandCrashReport18794.txt)
[systeminfo.txt](https://github.com/user-attachments/files/17607061/systeminfo.txt)

**Comment by vaxerski** [comment]
that was a message to all of you to go outside

**Comment by vaxerski** [comment]
should be fixed now tho I couldnt repro so check it for yourself then go outside

**Comment by izmyname** [comment]
no

**Comment by izmyname** [comment]
no brok. can haz futa pron, no outside

**Comment by vaxerski** [comment]
what?

**Comment by ebuttonsdude** [comment]
The commit fixed the issue for me - I also have waybar with a layer blur enabled
Thanks!

**Comment by Ciflire** [comment]
I still have crashes only from librewolf not from discord

**Comment by vaxerski** [comment]
debug stacktrace?

**Comment by ThaSiouL** [comment]
I still have crashes on things like opening proton games through steam, opening the steam settings window and opening Spotify(flatpak)

spotify crash:
[hyprlandCrashReport3134.txt](https://github.com/user-attachments/files/17607871/hyprlandCrashReport3134.txt)

**Comment by ThaSiouL** [comment]
here is the spotify crash report and gdb file with the debug version:

[hyprlandCrashReport3639.txt](https://github.com/user-attachments/files/17607968/hyprlandCrashReport3639.txt)
[gdb.txt](https://github.com/user-attachments/files/17607972/gdb.txt)

**Comment by ThaSiouL** [comment]
And here is another crash report when launching a proton game:

[hyprlandCrashReport6677.txt](https://github.com/user-attachments/files/17608003/hyprlandCrashReport6677.txt)
[gdb.txt](https://github.com/user-attachments/files/17608001/gdb.txt)

**Comment by vaxerski** [comment]
those arent debug

**Comment by Neurarian** [comment]
Same issue here. But on an AMD machine. Interestingly, on my Nvidia notebook everything works perfectly fine. Both are running almost the same NixOS/Home Manager config. https://github.com/hyprwm/Hyprland/commit/40081cb330fa838ad9c0a7b87c20b2300ea7fb38 improved/delayed the issue a little bit for some apps, but it still crashes after dragging tiles for a while. Dragging e.g. Firefox crashes Hyprland immediately. It also doesn't generate crash reports. 
[hyprland.log](https://github.com/user-attachments/files/17608682/hyprland.log) 
[coredump.txt](https://github.com/user-attachments/files/17608704/coredump.txt)

**Comment by vaxerski** [comment]
again, I need a debug stacktrace https://wiki.hyprland.org/Crashes-and-Bugs/#obtaining-a-debug-stacktrace

**Comment by abihf** [comment]
Hy @vaxerski here's my stack trace when crash

```gdb
#0  0x0000719fb02af65b in pthread_kill () at /usr/lib/libc.so.6
#1  0x0000719fb02500a8 in raise () at /usr/lib/libc.so.6
#2  0x0000719fb023247b in abort () at /usr/lib/libc.so.6
#3  0x000056b74198744e in handleUnrecoverableSignal (sig=11) at /home/abi/play/cpp/Hyprland/src/Compositor.cpp:80
#4  0x0000719fb0250150 in <signal handler called> () at /usr/lib/libc.so.6
#5  0x000056b7420513a4 in CHyprOpenGLImpl::blurMainFramebufferWithDamage (this=0x56b77bd17310, a=1, originalDamage=0x7fff0f167470) at /home/abi/play/cpp/Hyprland/src/render/OpenGL.cpp:1701
#6  0x000056b7420543fe in CHyprOpenGLImpl::renderTextureWithBlur (this=0x56b77bd17310, tex=..., pBox=0x7fff0f1675f0, a=1, pSurface=..., round=0, blockBlurOptimization=false, blurA=1) at /home/abi/play/cpp/Hyprland/src/render/OpenGL.cpp:2080
#7  0x000056b74207a5dd in renderSurface (surface=..., x=0, y=0, data=0x7fff0f167bf0) at /home/abi/play/cpp/Hyprland/src/render/Renderer.cpp:274
#8  0x000056b74207d369 in operator() (__closure=0x7fff0f1679c0, s=..., offset=..., data=0x7fff0f167bf0) at /home/abi/play/cpp/Hyprland/src/render/Renderer.cpp:675
#9  0x000056b74209a3c6 in std::__invoke_impl<void, CHyprRenderer::renderWindow(PHLWINDOW, PHLMONITOR, timespec*, bool, eRenderPassMode, bool, bool)::<lambda(Hyprutils::Memory::CSharedPointer<CWLSurfaceResource>, const Hyprutils::Math::Vector2D&, void*)>&, Hyprutils::Memory::CSharedPointer<CWLSurfaceResource>, const Hyprutils::Math::Vector2D&, void*>(std::__invoke_other, struct {...} &) (__f=...) at /usr/include/c++/14.2.1/bits/invoke.h:61
#10 0x000056b74209860b in std::__invoke_r<void, CHyprRenderer::renderWindow(PHLWINDOW, PHLMONITOR, timespec*, bool, eRenderPassMode, bool, bool)::<lambda(Hyprutils::Memory::CSharedPointer<CWLSurfaceResource>, const Hyprutils::Math::Vector2D&, void*)>&, Hyprutils::Memory::CSharedPointer<CWLSurfaceResource>, const Hyprutils::Math::Vector2D&, void*>(struct {...} &) (__fn=...) at /usr/include/c++/14.2.1/bits/invoke.h:111
#11 0x000056b742096d74 in std::_Function_handler<void(Hyprutils::Memory::CSharedPointer<CWLSurfaceResource>, const Hyprutils::Math::Vector2D&, void*), CHyprRenderer::renderWindow(PHLWINDOW, PHLMONITOR, timespec*, bool, eRenderPassMode, bool, bool)::<lambda(Hyprutils::Memory::CSharedPointer<CWLSurfaceResource>, const Hyprutils::Math::Vector2D&, void*)> >::_M_invoke(const std::_Any_data &, Hyprutils::Memory::CSharedPointer<CWLSurfaceResource> &&, const Hyprutils::Math::Vector2D &, void *&&)
    (__functor=..., __args#0=..., __args#1=..., __args#2=@0x7fff0f167800: 0x7fff0f167bf0) at /usr/include/c++/14.2.1/bits/std_function.h:290
#12 0x000056b741fd63fe in std::function<void(Hyprutils::Memory::CSharedPointer<CWLSurfaceResource>, Hyprutils::Math::Vector2D const&, void*)>::operator() (this=0x7fff0f1679c0, __args#0=..., __args#1=..., __args#2=0x7fff0f167bf0)
    at /usr/include/c++/14.2.1/bits/std_function.h:591
#13 0x000056b741fc7c12 in CWLSurfaceResource::bfHelper (this=0x56b77ee58930, nodes=std::vector of length 1, capacity 1 = {...}, fn=..., data=0x7fff0f167bf0) at /home/abi/play/cpp/Hyprland/src/protocols/core/Compositor.cpp:285
#14 0x000056b741fc7fbc in CWLSurfaceResource::breadthfirst (this=0x56b77ee58930, fn=..., data=0x7fff0f167bf0) at /home/abi/play/cpp/Hyprland/src/protocols/core/Compositor.cpp:305
#15 0x000056b74207ec32 in CHyprRenderer::renderWindow (this=0x56b77c05c950, pWindow=..., pMonitor=..., time=0x7fff0f167de0, decorate=false, mode=RENDER_PASS_MAIN, ignorePosition=false, ignoreAllGeometry=false)
    at /home/abi/play/cpp/Hyprland/src/render/Renderer.cpp:675
#16 0x000056b742086885 in CHyprRenderer::renderMonitor (this=0x56b77c05c950, pMonitor=...) at /home/abi/play/cpp/Hyprland/src/render/Renderer.cpp:1432
#17 0x000056b741bbf2a9 in CMonitor::onMonitorFrame (this=0x56b77c9573b0) at /home/abi/play/cpp/Hyprland/src/helpers/Monitor.cpp:1008
#18 0x000056b741bb5443 in operator() (__closure=0x56b77c943b30, d=std::any [no contained value]) at /home/abi/play/cpp/Hyprland/src/helpers/Monitor.cpp:49
#19 0x000056b741bc364a in std::__invoke_impl<void, CMonitor::onConnect(bool)::<lambda(std::any)>&, std::any>(std::__invoke_other, struct {...} &) (__f=...) at /usr/include/c++/14.2.1/bits/invoke.h:61
#20 0x000056b741bc1d33 in std::__invoke_r<void, CMonitor::onConnect(bool)::<lambda(std::any)>&, std::any>(struct {...} &) (__fn=...) at /usr/include/c++/14.2.1/bits/invoke.h:111
#21 0x000056b741bc0a9d in std::_Function_handler<void(std::any), CMonitor::onConnect(bool)::<lambda(std::any)> >::_M_invoke(const std::_Any_data &, std::any &&) (__functor=..., __args#0=...) at /usr/include/c++/14.2.1/bits/std_function.h:290
#22 0x0000719fb086d9cf in Hyprutils::Signal::CSignalListener::emit(std::any) () at /usr/lib/libhyprutils.so.1
#23 0x0000719fb086dd3e in Hyprutils::Signal::CSignal::emit(std::any) () at /usr/lib/libhyprutils.so.1
#24 0x0000719fb12f4c8b in ??? () at /usr/lib/libaquamarine.so.3
#25 0x0000719fb0d4a530 in drmHandleEvent () at /usr/lib/libdrm.so.2
#26 0x0000719fb12f39ab in Aquamarine::CDRMBackend::dispatchEvents() () at /usr/lib/libaquamarine.so.3
#27 0x000056b741bd7a72 in std::function<void()>::operator() (this=0x56b77e99dff8) at /usr/include/c++/14.2.1/bits/std_function.h:591
#28 0x000056b741ccb11a in aquamarineFDWrite (fd=32, mask=1, data=0x56b77e99dff0) at /home/abi/play/cpp/Hyprland/src/managers/eventLoop/EventLoopManager.cpp:41
#29 0x0000719fb11f2c12 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#30 0x0000719fb11f5517 in wl_display_run () at /usr/lib/libwayland-server.so.0
#31 0x000056b741ccb319 in CEventLoopManager::enterLoop (this=0x56b77adfa570) at /home/abi/play/cpp/Hyprland/src/managers/eventLoop/EventLoopManager.cpp:57
#32 0x000056b74198cc03 in CCompositor::startCompositor (this=0x56b77ae6ee00) at /home/abi/play/cpp/Hyprland/src/Compositor.cpp:718
#33 0x000056b741c0c5d6 in main (argc=1, argv=0x7fff0f168ff8) at /home/abi/play/cpp/Hyprland/src/main.cpp:173
```

**Comment by vaxerski** [comment]
tanks!

**Comment by sentakuhm** [comment]
i can confirm it fixed now.
