### ISSUE TITLE
Crashes when waybar is started with mirrored monitors

### ISSUE THREAD

**Issue by eriedaberrie** [hyprwm/Hyprland#947]
After a v0.17.0beta, I was unable to start up Hyprland with mirrored monitors without crashing immediately, which I eventually figured out was due to waybar.

The only thing changed in my hyprlandd.conf from the default is
```
monitor=,preferred,auto,1
monitor=HDMI-A-1,preferred,auto,1,mirror,eDP-1
```
**Expected Result:** Hyprland is running just like before, but with a waybar at the top.
**Actual result:** Hyprland crashes.

Here are my logs after running waybar from my terminal:

```
           PID: 31538 (Hyprland)
           UID: 1000 (errie)
           GID: 1000 (errie)
        Signal: 11 (SEGV)
     Timestamp: Tue 2022-11-01 21:29:22 PDT (34min ago)
  Command Line: ./Hyprland
    Executable: /home/errie/building/Hyprland/build/Hyprland
 Control Group: /user.slice/user-1000.slice/session-36.scope
          Unit: session-36.scope
         Slice: user-1000.slice
       Session: 36
     Owner UID: 1000 (errie)
       Boot ID: 9669890048ca43a8a9355cb396459b8b
    Machine ID: 0cfbae672e7f4b1095de3326d21d5574
      Hostname: AcerLaptop
       Storage: /var/lib/systemd/coredump/core.Hyprland.1000.9669890048ca43a8a9355cb396459b8b.31538.1667363362000000.zst (present)
     Disk Size: 2.9M
       Message: Process 31538 (Hyprland) of user 1000 dumped core.
                
                Module /home/errie/building/Hyprland/build/Hyprland with build-id fb88ad9b394aedf9a167166debf52d72134bda0d
                Module /home/errie/building/Hyprland/subprojects/wlroots/build/libwlroots.so.11032 with build-id a4234f4546e145f4b2877fc835b0e6f97657550e
                Module linux-vdso.so.1 with build-id 761622ba87db7ada771dabf8c045a339d26f604a
                Module libicudata.so.72 with build-id a133b365160fc45e002163e5435f3029f4254cfa
                Module libicuuc.so.72 with build-id c2e0249a038bd0fe76e681ecd2b73951c65a0866
                Module libxml2.so.2 with build-id 171e32069b76d4cfedbfdf97f2087807948a9b3d
                Module libncursesw.so.6 with build-id b9917757481e6fa6097e2a1f31f5bb5eaf138c4e
                Module libedit.so.0 with build-id 4b0babfcad161c2ad0af6e59e2493258db23a331
                Module libdrm_nouveau.so.2 with build-id 7e3a572a981d481c9e503d27f18d5cbe066e7db4
                Module libdrm_amdgpu.so.1 with build-id 84c55b198afb267724c1d704a4a6384458446e28
                Module libelf.so.1 with build-id 5ba0792747dce7480d031794ed90c620da72dbff
                Module libdrm_radeon.so.1 with build-id 121a4f7e02db7ecdf8badd7aa64c6860aff121aa
                Module libsensors.so.5 with build-id dc8b2c1c0d8525411aca188ea3cc3fb86d381d30
                Module libLLVM-14.so with build-id 16d23f3ab6fb7269b2f13a9932a2a7ec4b1d5104
                Module iris_dri.so with build-id 0b17a567605ce2c8f7104556d877a4db03733c74
                Module libxshmfence.so.1 with build-id 132b07a9077d5068fc07934d2a447b03c35a5f55
                Module libxcb-sync.so.1 with build-id 13025f6de23a271636ad321c77eda98801e62e8e
                Module libxcb-dri2.so.0 with build-id 7bde0abc84135ae6258a8d1d130864071c2cc327
                Module libX11-xcb.so.1 with build-id f92352eae0a30aea89d11beb22367fa985288925
                Module libglapi.so.0 with build-id cbed20ec1e1b9b063317c45975da77915f9da138
                Module libEGL_mesa.so.0 with build-id 4e62aa22cbdda2d067f236ba29e28e15800df6a9
                Module libgpg-error.so.0 with build-id 470d76ceb1e53cb017f78c08936e9bafaeb4058b
                Module libbrotlicommon.so.1 with build-id acfd597a977c8087bb6184383daae2e828a9ce42
                Module libblkid.so.1 with build-id fb2c5d3c17aac74758a3eb80a2bc1c16bcf183b1
                Module liblz4.so.1 with build-id 84ea95d811dad359e94e100ebe6a746294ffe8a7
                Module libzstd.so.1 with build-id ab54c2881f53ab314e134f3e08c76d504376dd5d
                Module liblzma.so.5 with build-id 8a7334fec02fef6a82ff641a68b3e3200a44a702
                Module libgcrypt.so.20 with build-id 8bf3cb884124273640de797a3e77d86c98434ea4
                Module libcap.so.2 with build-id 9b38b08de708f439a9d0a4f8b9914151bc8d4b50
                Module libgudev-1.0.so.0 with build-id 460465b63a086d945124662363191903c0002793
                Module libbrotlidec.so.1 with build-id 66c54e9301f7e102ecc1d88547e5f0e8a056fe22
                Module libbz2.so.1.0 with build-id 919597c477c9b2cb9cdbb7745ed6494ac0e6da60
                Module libdatrie.so.1 with build-id 6fe3b6ece2c8e7d11869fa051375128d8f808f58
                Module libmount.so.1 with build-id 9064fc3620c42e6f7aed38119f0a3ec39fca9a37
                Module libgmodule-2.0.so.0 with build-id 4145f63148e903c5cc49730868d4b108e4a2afba
                Module libsystemd.so.0 with build-id 9bed700282c6ab3bd115d3816bb234a632e770a5
                Module libexpat.so.1 with build-id a98bfab551dfa3df6889c33d5fd2ccfa6d505608
                Module libwacom.so.9 with build-id e0305944ffbc4bc72839093bcad8800af06968ed
                Module libevdev.so.2 with build-id 9ded5f5a6c45f3b30cf380d8a505e90b5f85f164
                Module libmtdev.so.1 with build-id 862cf8d5b0a0dd4d4d225e17f54be93ab9c3b34e
                Module libXrender.so.1 with build-id 9d6512ea1c9698e8c81f27e89fda57d36eb4b18e
                Module libXext.so.6 with build-id d7f3b1c9d5be6574b5faf83b74f8bba3d0dfa3c6
                Module libX11.so.6 with build-id 21e886e968772b7964d646f54c1faecc56734de9
                Module libpng16.so.16 with build-id 14d3b3cc9d61ec1b7c1f86bdf108218a99364945
                Module libz.so.1 with build-id 5340199d53cb95e609028ce1143675c742ff4218
                Module libgraphite2.so.3 with build-id ce58945ebb55b86d3a4e717b6eae29efc4720d8e
                Module libfreetype.so.6 with build-id f89dd5502e75aca28fb5c3ccd0dbd26fe822bfef
                Module libpcre2-8.so.0 with build-id 917fc43d2c9f8539a3e324555c6c73886e8000a8
                Module libthai.so.0 with build-id a7ac5010b4275c49308021200d23690533952702
                Module libfribidi.so.0 with build-id fe9f35ac2a0074108c8306c517793f7279bd9b37
                Module libgio-2.0.so.0 with build-id e40d688960cf27f1e3b08533563affb8baed62af
                Module libfontconfig.so.1 with build-id 9e856b5b37a3f4f7176ad8f92b2123508c95406e
                Module libpangoft2-1.0.so.0 with build-id d2aac9e9a7523c05b32ddc00621a1e371147485c
                Module libffi.so.8 with build-id 5c6b22b6624dd486a0783dfe74fee085b626b573
                Module libGLdispatch.so.0 with build-id 7879a881271650eff97c35aff7a8674859c5ae94
                Module ld-linux-x86-64.so.2 with build-id 22bd7a2c03d8cfc05ef7092bfae5932223189bc1
                Module libxcb-errors.so.0 with build-id ac2a50fca13918730b02db3b75d80f2183b77af1
                Module libxcb-res.so.0 with build-id cd3dbd6dd9e412a002d1be5ae0ec0d85650542ba
                Module libxcb-icccm.so.4 with build-id 5d6f83a2aa185e59274a061f07b8a50b766445f8
                Module libxcb-composite.so.0 with build-id e8b69e2806d928f66445390cc50ab33a0b98bef0
                Module libseat.so.1 with build-id 51f74c96a4dd3748925954d1cc5fc6c52f051866
                Module libxcb-xinput.so.0 with build-id 409ee697e2b16243bf1fc6429e672f2359033388
                Module libxcb-xfixes.so.0 with build-id e231a68d00ee4cfa12a2c31e755a9e2c1e7be450
                Module libxcb-shm.so.0 with build-id 828fec4d856e2710e732ea8d92c3f250c807b1c2
                Module libxcb-render-util.so.0 with build-id be7563af6c149b8412129d31bf3e262eb94b0efb
                Module libxcb-render.so.0 with build-id b1ca498d665807ab0ccdafbe8070853efd058173
                Module libxcb-present.so.0 with build-id 8ed389d9cd6ad7110fbb00c93b32e0efaa71a6b1
                Module libxcb-dri3.so.0 with build-id 088c750254cc139e7d62b8a3fc7795a138447ccf
                Module libvulkan.so.1 with build-id f17935be523c52093db3fed7d5845b8477c9040c
                Module libgbm.so.1 with build-id 8acba193da804107dd8ac0d0e5ed4f73f26c43e4
                Module libudev.so.1 with build-id 9182f4b98c40aa4dfd7fd1b4ff74fad23b715035
                Module libXdmcp.so.6 with build-id d864159ab0008415667db8d5f251696d75c90df2
                Module libXau.so.6 with build-id d9d5e8277140f1a86d3a07d9b52b1703c0a2f9a8
                Module libc.so.6 with build-id 1e94beb079e278ac4f2c8bce1f53091548ea1584
                Module libgcc_s.so.1 with build-id 85db482c4585a328d95ec41124337a967bb24d8f
                Module libm.so.6 with build-id 2c8ff1d29b255da5b7371efd5caf57444d622838
                Module libstdc++.so.6 with build-id 735a3d0cc7699fd69337361cba4aedb644b2a7ed
                Module libinput.so.10 with build-id 9de57b91e0d1d09e53606692e2c51c8b31d3dfe1
                Module libxkbcommon.so.0 with build-id 6cf66eead3fcc20fe5df10162bfbcdcdc8b2a183
                Module libEGL.so.1 with build-id 14389538015bb4a3a44e794e2466e31bf0834209
                Module libdrm.so.2 with build-id 5b59e55b50556f6d541e4d73fd6a2dcfb1983894
                Module libcairo.so.2 with build-id a222d042e56108d2786ece7bf291b56ba2069591
                Module libharfbuzz.so.0 with build-id 181bbb0db2bce74b6bd5ed66ee7dcbed96323d8b
                Module libglib-2.0.so.0 with build-id 49826f5cd4f784c8050176991d46fd93a5fcee9f
                Module libgobject-2.0.so.0 with build-id 4912a41f41a806314fb1a528139e368746d80dda
                Module libpango-1.0.so.0 with build-id 2cbe86c0a6de777fa7bc584d74ce48d39fc595d0
                Module libpangocairo-1.0.so.0 with build-id 2e46c234e5b532d7b0da24a79d0803cd67dd127f
                Module libwayland-cursor.so.0 with build-id 46a637dbcbb02d6712a201f177377b66598b9121
                Module libwayland-client.so.0 with build-id 515c72111400d7bdbfbdfcec78d597e4986a5943
                Module libwayland-server.so.0 with build-id 4c54fc8a7c0d4eb8adf2a69e44ebf12d16969c74
                Module libGLESv2.so.2 with build-id c2687a762cabcd41ea562e6536c383f31438a546
                Module libOpenGL.so.0 with build-id 3df533822644f44fa89abdb75b9f89220dfdee56
                Module libpixman-1.so.0 with build-id 3782c95a3b9e331f10403b264ffeedab91f99768
                Module libxcb.so.1 with build-id 13d677412a71468381b11092915d231f664d18d3
                Stack trace of thread 31538:
                #0  0x00000000004c9647 n/a (/home/errie/building/Hyprland/build/Hyprland + 0xc9647)
                #1  0x00000000004c6d0a n/a (/home/errie/building/Hyprland/build/Hyprland + 0xc6d0a)
                #2  0x00007f20faf20f6e wl_signal_emit_mutable (libwayland-server.so.0 + 0x9f6e)
                #3  0x00007f20fb08da9e n/a (/home/errie/building/Hyprland/subprojects/wlroots/build/libwlroots.so.11032 + 0x74a9e)
                ELF object binary architecture: AMD x86-64
```

[hyprlandd.log](https://github.com/hyprwm/Hyprland/files/9916442/hyprlandd.log)

**Comment by vaxerski** [comment]
please provide a debug coredump (see issue guidelines)

**Comment by eriedaberrie** [comment]
<details>
<summary>Debug coredump output</summary>

```
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `./Hyprland'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000004c9647 in std::vector<std::unique_ptr<SLayerSurface, std::default_delete<SLayerSurface> >, std::allocator<std::unique_ptr<SLayerSurface, std::default_delete<SLayerSurface> > > >::emplace_back<std::unique_ptr<SLayerSurface, std::default_delete<SLayerSurface> > > (this=0x120)
    at /usr/include/c++/12.2.0/bits/vector.tcc:114
114		if (this->_M_impl._M_finish != this->_M_impl._M_end_of_storage)
[Current thread is 1 (Thread 0x7f441012ce00 (LWP 2424))]
(gdb) bt -full
#0  0x00000000004c9647 in std::vector<std::unique_ptr<SLayerSurface, std::default_delete<SLayerSurface> >, std::allocator<std::unique_ptr<SLayerSurface, std::default_delete<SLayerSurface> > > >::emplace_back<std::unique_ptr<SLayerSurface, std::default_delete<SLayerSurface> > >(std::unique_ptr<SLayerSurface, std::default_delete<SLayerSurface> >&&) (this=0x120) at /usr/include/c++/12.2.0/bits/vector.tcc:114
#1  0x00000000004c6d0a in Events::listener_newLayerSurface(wl_listener*, void*)
    (listener=0x63c2d0 <Events::listen_newLayerSurface>, data=0x1802fa0)
    at /home/errie/building/Hyprland/src/events/Layers.cpp:35
        WLRLAYERSURFACE = 0x1802fa0
        PMONITOR = 0x0
        layerSurface = 0x1800ed0
#2  0x00007f44117b8f6e in wl_signal_emit_mutable (signal=<optimized out>, data=0x1802fa0)
    at ../wayland-1.21.0/src/wayland-server.c:2179
        pos = 0x63c2d0 <Events::listen_newLayerSurface>
        l = 0x63c2d0 <Events::listen_newLayerSurface>

                  cursor = {link = {prev = 0x63c2d0 <Events::listen_newLayerSurface>, next = 0x7ffc91f506b0}, notify = 0x7f44117b6110 <handle_noop>}
        end = {link = {prev = 0x7ffc91f506d0, next = 0x123e520}, notify = 0x7f44117b6110 <handle_noop>}
#3  0x00007f4411925a9e in surface_commit_state ()
    at /home/errie/building/Hyprland/subprojects/wlroots/build/libwlroots.so.11032
#4  0x00007f4410b744f6 in ffi_call_unix64 () at ../src/x86/unix64.S:104
#5  0x00007f4410b70f5e in ffi_call_int
    (cif=<optimized out>, fn=<optimized out>, rvalue=<optimized out>, avalue=<optimized out>, closure=<optimized out>) at ../src/x86/ffi64.c:673
        classes = {X86_64_INTEGER_CLASS, 32764, 280426172, 32580}
        stack = <optimized out>
        argp = 0x7ffc91f50790 ""
        arg_types = <optimized out>
        gprcount = 2
        ssecount = <optimized out>
        ngpr = 1
        nsse = 0
        i = <optimized out>
        avn = <optimized out>
        flags = <optimized out>
        reg_args = <optimized out>
#6  0x00007f4410b73b73 in ffi_call
    (cif=cif@entry=0x7ffc91f50940, fn=<optimized out>, rvalue=rvalue@entry=0x0, avalue=avalue@entry=0x7ffc91f50a10) at ../src/x86/ffi64.c:710
        arg_types = 0x7ffc91f50960
        i = <optimized out>
        nargs = 2
        max_reg_struct_size = <optimized out>
#7  0x00007f44117b7ada in wl_closure_invoke (closure=closure@entry=0x17fb8e0, target=<optimized out>, 
    target@entry=0x1802f10, opcode=opcode@entry=6, data=<optimized out>, data@entry=0x17f52a0, flags=2)
    at ../wayland-1.21.0/src/connection.c:1025
        count = <optimized out>

                  cif = {abi = FFI_UNIX64, nargs = 2, arg_types = 0x7ffc91f50960, rtype = 0x7f4410b751a0 <ffi_type_void>, bytes = 0, flags = 0}

                  ffi_types = {0x7f4410b752a0 <ffi_type_pointer>, 0x7f4410b752a0 <ffi_type_pointer>, 0x7f4410b75240 <ffi_type_uint32>, 0x7f4410b75240 <ffi_type_uint32>, 0x7f4410b75330 <ffi_type_sint32>, 0x7f4410b75330 <ffi_type_sint32>, 0x7f4410b752a0 <ffi_type_pointer>, 0x7f4411918e4b <wlr_seat_keyboard_send_key+171>, 0x1b201, 0x1710dfe6bd, 0x63cf80 <g_pCompositor>, 0x1b201, 0x7ffc91f50a40, 0x1c, 0x0, 0x7f44117b6110 <handle_noop>, 0x7f4411a22000 <_rtld_global>, 0x7f4410dc6cfe <_int_malloc+3406>, 0x101802440, 0x1f, 0x7ffc91f50c60, 0x8--Type <RET> for more, q to quit, c to continue without paging--
035a9a8e9c2ec00}

                  ffi_args = {0x7ffc91f50920, 0x7ffc91f50928, 0x17fb8f8, 0x7f4410dc6aef <_int_malloc+2879>, 0x30, 0xc, 0xe, 0x7484f0, 0x0, 0x7f44117b9471 <log_closure+81>, 0x1803150, 0x9ba790, 0x7f4410f09ba0 <main_arena>, 0x0, 0x7f4411993b60 <zwlr_layer_surface_v1_requests>, 0x7f4410dc8416 <__libc_calloc+214>, 0x7f4410f09ba0 <main_arena>, 0x8035a9a8e9c2ec00, 0x7ffc91f50b50, 0x7f44117be42d, 0x7f44117c3470 <wl_surface_requests+144>, 0x0}
        implementation = <optimized out>
#8  0x00007f44117bc010 in wl_client_connection_data
    (fd=<optimized out>, mask=<optimized out>, data=<optimized out>)
    at ../wayland-1.21.0/src/wayland-server.c:437
        connection = <optimized out>
        resource = 0x1802f10
        object = 0x1802f10
        closure = <optimized out>
        message = 0x7f44117c3470 <wl_surface_requests+144>
        p = {40, 524294}
        resource_flags = 0
        opcode = 6
        size = <optimized out>
        since = <optimized out>
        len = <optimized out>
#9  0x00007f44117ba9e2 in wl_event_loop_dispatch (loop=0x9ba880, timeout=timeout@entry=-1)
    at ../wayland-1.21.0/src/event-loop.c:1027

                      ep = {{events = 1, data = {ptr = 0x17f27d0, fd = 25110480, u32 = 25110480, u64 = 25110480}}, {events = 1, data = {ptr = 0x14dc390, fd = 21873552, u32 = 21873552, u64 = 21873552}}, {events = 3921865728, data = {ptr = 0x8035a9a8, fd = -2143966808, u32 = 2151000488, u64 = 2151000488}}, {events = 0, data = {ptr = 0x18, fd = 24, u32 = 24, u64 = 24}}, {events = 25088960, data = {ptr = 0x91f50d9000000000, fd = 0, u32 = 0, u64 = 10517327416920113152}}, {events = 32764, data = {ptr = 0x17f03d8, fd = 25101272, u32 = 25101272, u64 = 25101272}}, {events = 25093064, data = {ptr = 0x91f50dd000000000, fd = 0, u32 = 0, u64 = 10517327691798020096}}, {events = 32764, data = {ptr = 0x7f44117b7500 <wl_connection_flush+304>, fd = 293303552, u32 = 293303552, u64 = 139930327807232}}, {events = 0, data = {ptr = 0x1800000000, fd = 0, u32 = 0, u64 = 103079215104}}, {events = 0, data = {ptr = 0x7ffc91f50df0, fd = -1846211088, u32 = 2448756208, u64 = 140722757242352}}, {events = 0, data = {ptr = 0x1e60, fd = 7776, u32 = 7776, u64 = 7776}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0xffffffff00000008, fd = 8, u32 = 8, u64 = 18446744069414584328}}, {events = 25096744, data = {ptr = 0x1800000000, fd = 0, u32 = 0, u64 = 103079215104}}, {events = 0, data = {ptr = 0x17fda38, fd = 25156152, u32 = 25156152, u64 = 25156152}}, {events = 584, data = {ptr = 0x1400000000, fd = 0, u32 = 0, u64 = 85899345920}}, {events = 0, data = {ptr = 0x100000001, fd = 1, u32 = 1, u64 = 4294967297}}, {events = 82, data = {ptr = 0x112356a000007f44, fd = 32580, u32 = 32580, u64 = 1234925968024436548}}, {events = 32580, data = {ptr = 0x1, fd = 1, u32 = 1, u64 = 1}}, {events = 3921865728, data = {ptr = 0x18035a9a8, fd = -2143966808, u32 = 2151000488, u64 = 6445967784}}, {events = 0, data = {ptr = 0x7f441190d08d <wlr_output_cursor_set_image+77>, fd = 294703245, u32 = 294703245, u64 = 139930329206925}}, {events = 294921596, data = {ptr = 0x400007f44, fd = 32580, u32 = 32580, u64 = 17179901764}}, {events = 0, data = {ptr = 0x15c3300, fd = 22819584, u32 = 22819584, u64 = 22819584}}, {events = 0, data = {ptr = 0x400000000, fd = 0, u32 = 0, u64 = 17179869184}}, {events = 0, data = {ptr = 0x1009babf0, fd = 10202096, u32 = 10202096, u64 = 4305169392}}, {events = 1065353216, data = {ptr = 0x400000018, fd = 24, u32 = 24, u64 = 17179869208}}, {events = 20294056, data = {ptr = 0x9babf0, fd = 10202096, u32 = 10202096, u64 = 10202096}}, {events = 3921865728, data = {ptr = 0x11734008035a9a8, fd = -2143966808, u32 = 2151000488, u64 = 78588695257917864}}, {events = 0, data = {ptr = 0x17f52a0, fd = 25121440, u32 = 25121440, u64 = 25121440}}}
        source = <optimized out>
        i = 0
        count = <optimized out>
--Type <RET> for more, q to quit, c to continue without paging--
        has_timers = <optimized out>
#10 0x00007f44117bb197 in wl_display_run (display=0x9ba790)
    at ../wayland-1.21.0/src/wayland-server.c:1431
#11 0x0000000000415e7f in CCompositor::startCompositor() (this=0x9b84a0)
    at /home/errie/building/Hyprland/src/Compositor.cpp:356
#12 0x000000000050e521 in main(int, char**) (argc=1, argv=0x7ffc91f51148)
    at /home/errie/building/Hyprland/src/main.cpp:65
        cmd = "./Hyprland"
        configPath = ""
        LOGWLR = 0x0
```
</details>

**Comment by vaxerski** [comment]
please check with 31aa357c17ab670041695da3d8ba8586063bf5a6

**Comment by eriedaberrie** [comment]
With 31aa357 it no longer crashes, but there is a new issue where it duplicates the bar.
(Again, this only happens when using a mirrored monitor.)
![image](https://user-images.githubusercontent.com/64395218/199863024-e1910652-d8a8-4aff-b170-b254fcce41a6.png)

**Comment by vaxerski** [comment]
yes, because your bar is trying to create a bar on the mirrored output, which gets now rejected and thrown to your main. That's a problem with your bar. Make it ignore the mirrored output.
